tests/core/basic20plus: run for core24

diff --git a/tests/core/basic20plus/task.yaml b/tests/core/basic20plus/task.yaml
--- a/tests/core/basic20plus/task.yaml
+++ b/tests/core/basic20plus/task.yaml
@@ -8,17 +8,23 @@ details: |
     properly
 
 systems:
-  - ubuntu-core-20-*
-  - ubuntu-core-22-*
+  - -ubuntu-core-16-*
+  - -ubuntu-core-18-*
 
 execute: |
     case "$SPREAD_SYSTEM" in
+      ubuntu-core-24-*)
+        base_snap=core24
+        ;;
       ubuntu-core-22-*)
         base_snap=core22
         ;;
       ubuntu-core-20-*)
         base_snap=core20
         ;;
+      *)
+        echo "Unsupported ubuntu core system, add missing case here"
+        exit 1
     esac
     echo "Check that the system snaps are there"
     snap list "${base_snap}"
@@ -32,12 +38,9 @@ execute: |
     snap changes | MATCH "Done.*Initialize system state"
 
     echo "Check that a simple shell snap"
-    if os.query is-core22; then
-        snap install --edge "test-snapd-sh-${base_snap}"
-    else
-        snap install "test-snapd-sh-${base_snap}"
-    fi
-    "test-snapd-sh-${base_snap}.sh" -c 'echo hello' | MATCH hello
+    SHELL_SNAP="test-snapd-sh-${base_snap}"
+    snap install "$SHELL_SNAP"
+    "${SHELL_SNAP}.sh" -c 'echo hello' | MATCH hello
 
     if python3 -m json.tool < /var/lib/snapd/system-key | grep '"build-id": ""'; then
         echo "The build-id of snapd must not be empty."
@@ -45,10 +48,10 @@ execute: |
     fi
 
     echo "Ensure passwd/group is available for snaps"
-    "test-snapd-sh-${base_snap}.sh" -c 'cat /var/lib/extrausers/passwd' | MATCH test
+    "${SHELL_SNAP}.sh" -c 'cat /var/lib/extrausers/passwd' | MATCH test
 
     # rpi devices don't use grub
-    if ( os.query is-core20 || os.query is-core22 ) && not snap list pi-kernel &>/dev/null; then
+    if not snap list pi-kernel &>/dev/null; then
         echo "Ensure extracted kernel.efi exists"
         kernel_name="$(snaps.name kernel)"
         test -e /boot/grub/"$kernel_name"*/kernel.efi
@@ -70,9 +73,13 @@ execute: |
 
     # ensure that our the-tool (and thus our snap-bootstrap ran)
     # for external backend the initramfs is not rebuilt
-    echo "Check that we booted with the rebuilt initramfs in the kernel snap"
-    if [ "$SPREAD_BACKEND" != "external" ] && [ "$SPREAD_BACKEND" != "testflinger" ]; then
-        test -e /writable/system-data/the-tool-ran
+    # On core24+ we repack the kernel snap differently, and thus do not
+    # touch the /writable/system-data/the-tool-ran
+    if os.query is-core20 || os.query is-core22; then
+        echo "Check that we booted with the rebuilt initramfs in the kernel snap"
+        if [ "$SPREAD_BACKEND" != "external" ] && [ "$SPREAD_BACKEND" != "testflinger" ]; then
+            test -e /writable/system-data/the-tool-ran
+        fi
     fi
 
     # ensure we handled cloud-init, either we have:
