Merge release/2.26.8 into master

diff --git a/tests/main/interfaces-upower-observe/task.yaml b/tests/main/interfaces-upower-observe/task.yaml
--- a/tests/main/interfaces-upower-observe/task.yaml
+++ b/tests/main/interfaces-upower-observe/task.yaml
@@ -4,8 +4,6 @@ systems:
     - -ubuntu-core-16-*
     # ppc64el disabled because of https://github.com/snapcore/snapd/issues/2504
     - -ubuntu-*-ppc64el
-    # No confinement (AppArmor, Seccomp) available on these systems
-    - -debian-*
 
 summary: |
     The upower-observe interface allows a snap to query UPower for power devices, history
@@ -21,12 +19,13 @@ prepare: |
     echo "Given a snap declaring a plug on the upower-observe interface is installed"
     snap install --edge test-snapd-upower-observe-consumer
 
-    apt-get install -y upower
+    . "$TESTSLIB/pkgdb.sh"
+    distro_install_package upower
 
 restore: |
     rm -f upower.error
-    apt-get remove --purge -y upower
-    apt-get autoremove --purge -y
+    . "$TESTSLIB/pkgdb.sh"
+    distro_purge_package upower
 
 execute: |
     CONNECTED_PATTERN=":upower-observe +test-snapd-upower-observe-consumer"
@@ -41,14 +40,16 @@ execute: |
     snap disconnect test-snapd-upower-observe-consumer:upower-observe
     snap interfaces | grep -Pzq "$DISCONNECTED_PATTERN"
 
-    echo "Then the snap is not able to dump info about the upower devices"
-    if su -l -c "test-snapd-upower-observe-consumer.upower --dump 2>${PWD}/upower.error" test; then
-        echo "Expected permission error accessing upower info with disconnected plug"
-        exit 1
-    fi
-    grep -q "Permission denied" upower.error
+    if [ "$(snap debug confinement)" = strict ] ; then
+        echo "Then the snap is not able to dump info about the upower devices"
+        if su -l -c "test-snapd-upower-observe-consumer.upower --dump 2>${PWD}/upower.error" test; then
+            echo "Expected permission error accessing upower info with disconnected plug"
+            exit 1
+        fi
+        grep -q "Permission denied" upower.error
 
-    echo "==================================="
+        echo "==================================="
+    fi
 
     echo "When the plug is connected"
     snap connect test-snapd-upower-observe-consumer:upower-observe
