Formatting updates to the spread login test

diff --git a/tests/main/login/task.yaml b/tests/main/login/task.yaml
--- a/tests/main/login/task.yaml
+++ b/tests/main/login/task.yaml
@@ -1,13 +1,17 @@
 summary: Checks for snap login
+
+restore: |
+    snap logout || true
+
 execute: |
-  echo "Checking missing email error"
-  expect -f missing_email_error.exp
+    echo "Checking missing email error"
+    expect -f missing_email_error.exp
 
-  echo "Checking wrong password error"
-  expect -f unsuccessful_login.exp
+    echo "Checking wrong password error"
+    expect -f unsuccessful_login.exp
 
-  if [[ $SPREAD_STORE_USER && $SPREAD_STORE_PASSWORD ]]; then
-    echo "Checking successful login"
-    expect -f successful_login.exp
-    snap logout
-  fi
+    if [[ $SPREAD_STORE_USER && $SPREAD_STORE_PASSWORD ]]; then
+        echo "Checking successful login"
+        expect -f successful_login.exp
+        snap logout
+    fi
