Enhanced spread test. Renaming fixes.

diff --git a/tests/main/snapctl-from-snap/task.yaml b/tests/main/snapctl-from-snap/task.yaml
--- a/tests/main/snapctl-from-snap/task.yaml
+++ b/tests/main/snapctl-from-snap/task.yaml
@@ -3,12 +3,13 @@ summary: Check that `snapctl` can be run from the snap
 prepare: |
     echo "Build basic test package"
     snapbuild $TESTSLIB/snaps/snapctl-from-snap .
-    snap install --dangerous snapctl-from-snap_1.0_all.snap
-
+  
 restore: |
     rm snapctl-from-snap_1.0_all.snap
 
 execute: |
+    snap install --dangerous snapctl-from-snap_1.0_all.snap
+
     echo "Verify that context file exists and has proper permissions"
     CONTEXT_FILE=/var/lib/snapd/context/snap.snapctl-from-snap
     if ! test -f $CONTEXT_FILE ; then
@@ -31,6 +32,19 @@ execute: |
 
     echo "Verify configuration value with snap get"
     snap get snapctl-from-snap foo | MATCH 123
+
+
+    echo "Given two revisions of a snap have been installed"
+    snap install --dangerous snapctl-from-snap_1.0_all.snap
+
+    echo "And a single revision gets removed"
+    snap remove snapctl-from-snap --revision=x1
+
+    echo "Verify that context file is still present"
+    if ! test -f $CONTEXT_FILE ; then
+        echo "Context file $CONTEXT_FILE is missing"
+        exit 1
+    fi
 
     echo "Verify that snap context is removed on snap removal"
     snap remove snapctl-from-snap
