tests/lib: test code to dump drivers inside test that usually fails with dropped drivers

diff --git a/tests/main/interfaces-firewall-control/task.yaml b/tests/main/interfaces-firewall-control/task.yaml
--- a/tests/main/interfaces-firewall-control/task.yaml
+++ b/tests/main/interfaces-firewall-control/task.yaml
@@ -44,6 +44,11 @@ restore: |
     fi
     rm -f "$REQUEST_FILE"
 
+debug: |
+    echo ">>> Dumping used modules:"
+    awk '{print $1}' < /proc/modules | sort > /tmp/mods
+    cat /tmp/mods
+
 execute: |
     echo "Then the plug is disconnected by default"
     snap interfaces -i firewall-control | MATCH '^- +firewall-control-consumer:firewall-control'
@@ -56,6 +61,13 @@ execute: |
 
     echo "Then the service listening on localhost is accessible through the destination IP in the rule"
     nc -w 2 "$DESTINATION_IP" "$PORT" < "$REQUEST_FILE" | MATCH 'ok$'
+
+    # Trigger error
+    MUST_EXIT="YES"
+    if [ "$MUST_EXIT" = "YES" ]; then
+        echo "Faking error..."
+        exit 1
+    fi
 
     echo "When the snap deletes the firewall rule"
     firewall-control-consumer.delete
