actually capture the expect return code

diff --git a/tests/main/create-key/task.yaml b/tests/main/create-key/task.yaml
--- a/tests/main/create-key/task.yaml
+++ b/tests/main/create-key/task.yaml
@@ -33,18 +33,28 @@ prepare: |
     echo pinentry-program /tmp/pinentry-fake > /root/.snap/gnupg/gpg-agent.conf
 
 execute: |
+    set +e
+
     echo "Checking passphrase mismatch error"
     expect -d -f passphrase_mismatch.exp
+    RET=$?
+    if [ $RET -ne 0 ]; then
+        echo "expect failed with exit code $RET"
+        exit 1
+    fi
 
     echo "Checking successful default key pair generation"
-    if ! expect -d -f successful_default.exp; then
-        echo "expect failed with exit code $?"
+    expect -d -f successful_default.exp
+    RET=$?
+    if [ $RET -ne 0 ]; then
+        echo "expect failed with exit code $RET"
         exit 1
     fi
 
     echo "Checking successful non-default key pair generation"
-    if ! expect -d -f successful_non_default.exp; then
-        echo "expect failed with exit code $?"
+    expect -d -f successful_non_default.exp
+    RET=$?
+    if [ $RET -ne 0 ]; then
+        echo "expect failed with exit code $RET"
         exit 1
     fi
-    
