more debug around the create-key test

diff --git a/tests/main/create-key/task.yaml b/tests/main/create-key/task.yaml
--- a/tests/main/create-key/task.yaml
+++ b/tests/main/create-key/task.yaml
@@ -37,7 +37,14 @@ execute: |
     expect -d -f passphrase_mismatch.exp
 
     echo "Checking successful default key pair generation"
-    expect -d -f successful_default.exp
+    if ! expect -d -f successful_default.exp; then
+        echo "expect failed with exit code $?"
+        exit 1
+    fi
 
     echo "Checking successful non-default key pair generation"
-    expect -d -f successful_non_default.exp
+    if ! expect -d -f successful_non_default.exp; then
+        echo "expect failed with exit code $?"
+        exit 1
+    fi
+    
