Not checking connection anymore and minor improvements

diff --git a/tests/main/interfaces-broadcom-asic-control/task.yaml b/tests/main/interfaces-broadcom-asic-control/task.yaml
--- a/tests/main/interfaces-broadcom-asic-control/task.yaml
+++ b/tests/main/interfaces-broadcom-asic-control/task.yaml
@@ -3,37 +3,62 @@ summary: Ensure that the broadcom-asic-control interface works.
 details: |
     The broadcom-asic-control interface allow access to broadcom asic kernel module.
 
-environment:
-    CONNECTED_PATTERN: ':ssh-keys +test-snapd-ssh-keys'
-    DISCONNECTED_PATTERN: '\- +test-snapd-ssh-keys:ssh-keys'
-
 prepare: |
     . $TESTSLIB/snaps.sh
     install_local test-snapd-broadcom-asic-control
 
     . $TESTSLIB/files.sh
-    ensure_dir_exists /sys/module/linux_bcm_knet/
-    ensure_dir_exists /sys/module/linux_kernel_bde/
-    ensure_dir_exists /sys/module/linux_user_bde/
+    ensure_file_exists_backup_real /dev/linux-user-bde
+    ensure_file_exists_backup_real /dev/linux-kernel-bde
+    ensure_file_exists_backup_real /dev/linux-bcm-knet
 
-    ensure_file_exists_move_real /dev/linux-user-bde
-    ensure_file_exists_move_real /dev/linux-kernel-bde
-    ensure_file_exists_move_real /dev/linux-bcm-knet
-
+    ensure_file_exists /run/udev/data/+pci:0test
 
 restore: |
     rm -f call.error
 
-execute: |
-    echo "The interface is not connected by default"
-    snap interfaces | MATCH "$DISCONNECTED_PATTERN"
+    . $TESTSLIB/files.sh
+    clean_file /dev/linux-user-bde
+    clean_file /dev/linux-kernel-bde
+    clean_file /dev/linux-bcm-knet
 
+    clean_dir /sys/devices/pci00test/
+    clean_file "/run/udev/data/+pci:0test"
+
+execute: |
     echo "When the interface is connected"
     snap connect test-snapd-broadcom-asic-control:broadcom-asic-control
-    snap interfaces | MATCH "$CONNECTED_PATTERN"
 
-    echo "Then the snap is able to check the ssh version"
-    test-snapd-broadcom-asic-control.sh -c "ls /sys/module/linux_bcm_knet/"
+    echo "Then the snap is able to read the system modules directories"
+    for module in "linux_bcm_knet" "linux_kernel_bde" "linux_user_bde"; do
+        if [ -d /sys/module/$module ]; then
+            test-snapd-broadcom-asic-control.sh -c "ls /sys/module/$module"
+        fi
+    done
+
+    echo "Then the snap is able to read/write the system modules devices"
+    for device in "linux-bcm-knet" "linux-kernel-bde" "linux-user-bde"; do
+        test-snapd-broadcom-asic-control.sh -c "cat /dev/$device"
+        test-snapd-broadcom-asic-control.sh -c "echo test >> /dev/$device"
+    done
+
+    echo "Then the snap is able to read pci devices info"
+    if [ -d "/sys/devices/pci0000:00/" ]; then
+        config="$(find /sys/devices/pci0000:00/ -name config | head -n1)"
+        vendor="$(find /sys/devices/pci0000:00/ -name vendor | head -n1)"
+        device="$(find /sys/devices/pci0000:00/ -name device | head -n1)"
+        subsystem_vendor="$(find /sys/devices/pci0000:00/ -name subsystem_vendor | head -n1)"
+        subsystem_device="$(find /sys/devices/pci0000:00/ -name subsystem_device | head -n1)"
+
+        for file in "$config" "$vendor" "$device" "$subsystem_vendor" "$subsystem_device"; do
+            if ! [ -z $file ]; then
+                test-snapd-broadcom-asic-control.sh -c "cat $file"
+            fi
+        done
+    fi
+
+    test-snapd-broadcom-asic-control.sh -c "ls /sys/bus/pci/devices/"
+    test-snapd-broadcom-asic-control.sh -c "cat /run/udev/data/+pci:0test"
 
     if [ "$(snap debug confinement)" = partial ] ; then
         exit 0
@@ -41,11 +66,10 @@ execute: |
 
     echo "When the plug is disconnected"
     snap disconnect test-snapd-broadcom-asic-control:broadcom-asic-control
-    snap interfaces | MATCH "$DISCONNECTED_PATTERN"
 
-    echo "Then the snap is not able to read a ssh private key"
-    if test-snapd-broadcom-asic-control.sh -c "ls /sys/module/linux_bcm_knet/" 2>${PWD}/call.error; then
-        echo "Expected permission error accessing to ssh"
+    echo "Then the snap is not able to read the device"
+    if test-snapd-broadcom-asic-control.sh -c "cat /dev/linux-bcm-knet" 2>${PWD}/call.error; then
+        echo "Expected permission error accessing to device"
         exit 1
     fi
     MATCH "Permission denied" < call.error
