daemon, overlord: add change and ensure registry (#15532)
* daemon, overlord: add change and ensure registry

* overlord, daemon: rename registry methods

* run-checks: add check for ensure function registrations

* daemon, run-checks: add unit tests to check all calls to newChange wrapper function in daemon are registered; add check in run-checks for all other change kind registrations

* daemon: register missing change kind

* daemon: change wrap to BeforeNewChange in export_test and move missing checks to api_base_test logic

* daemon: add missing action types for snaps endpoint

* daemon, overlord: move change reg vars to separate grouping

* daemon, overlord: correct slice initialization

* overlord: variable camelcase correction and remove superfluous unit test function

* overlord/swfeats: only add change kind to registry if it isn't already present

* run-checks, overlord: translate bash script to go unit test for change registration checking

* many: make the change and ensure registries package private

* daemon: correct change kind name

* daemon, overlord: change "reg" to "register"

diff --git a/run-checks b/run-checks
--- a/run-checks
+++ b/run-checks
@@ -518,6 +518,18 @@ if [ "$STATIC" = 1 ]; then
     else
         echo ">> [C] Skipping C source code formatting check"
     fi
+
+    echo ">> [Go] Checking that all ensure helper methods have been registered"
+    missing=0
+    while IFS=' ' read -r manager func; do
+        if ! grep -rq "swfeats.RegisterEnsure(\"$manager\",.*\"$func\")" .; then
+            echo "Missing ensure function registration. Add the following to the relevant file: swfeats.RegEnsure(\"$manager\", \"$func\")"
+            missing=1
+        fi
+    done < <(grep -r '.Trace("ensure"' overlord | sed -n 's/.*\.Trace("ensure",.*"manager",.*"\([^"]*\)",.*"func",.*"\([^"]*\)").*/\1 \2/p')
+    if [ $missing -eq 1 ]; then
+        exit 1
+    fi
 fi
 
 if [ "$UNIT" = 1 ]; then
