travis, tests/unit, run-checks: skip nakedret until upstream is fixed
Nakedret uptream broke and reports false positives for nested function literals
[1]. A PR with a fix is open already, but until it lands, we need to skip
nakedret errors.

1. https://github.com/alexkohler/nakedret/issues/11

Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>

diff --git a/run-checks b/run-checks
--- a/run-checks
+++ b/run-checks
@@ -235,7 +235,11 @@ if [ "$STATIC" = 1 ]; then
     got=$(go list ./... | grep -v '/osutil/udev/' | grep -v '/vendor/' | xargs nakedret 2>&1)
     if [ -n "$got" ]; then
         echo "$got"
-        exit 1
+        if [ -z "${SKIP_NAKEDRET:-}" ]; then
+            exit 1
+        else
+            echo "Ignoring nakedret errors as requested"
+        fi
     fi
 
     echo Checking all interfaces have minimal spread test
