run-checks: added golangci-lint to run-checks (#14464)
* run-checks: added golangci-lint run

* run-checks: review corrections - remove superfluous exit

* run-checks: review corrections

* run-checks: added check for go version of golangci-lint and go

* tests: added golagnci-lint skip in spread test

* run-checks: review corrections - run golangci-lint also on older go and made clearer env variable and comment

* run-checks: review corrections - allow for non-snap installation of golangci-lint

* run-checks: review corrections

diff --git a/run-checks b/run-checks
--- a/run-checks
+++ b/run-checks
@@ -393,6 +393,41 @@ if [ "$STATIC" = 1 ]; then
       echo "$got"
       exit 1
     fi
+
+    if [ -z "${SKIP_GOLANGCI_LINT-}" ]; then
+
+        echo "Checking installation of golangci-lint"
+        gcil="$(command -v golangci-lint || true)"
+        if [ -z "$gcil" ]; then 
+            echo "ERROR: Cannot find golangci-lint. You need to first install the golangci-lint"
+            exit 1
+        fi
+
+        if echo "$gcil" | grep -q '/snap/bin/' ; then
+            # golangci-lint was installed from the snap
+            if snap refresh --list | grep -q golangci-lint; then
+                echo "WARNING: your golangci-lint snap is out of date. The CI will install a fresh version, which may differ from yours."
+            fi
+            if ! snap list golangci-lint | grep -q latest; then
+                echo "WARNING: your golangci-lint snap is not installed from the latest/* channel."
+            fi
+        fi
+
+        # Check whether golangci-lint was built with go version >= the installed go version
+        gcil_go_ver=$(golangci-lint --version | grep -o 'go[0-9]*\.[0-9]*\.[0-9]*' | cut -c 3-)
+        go_ver=$(go version | grep -o 'go[0-9]*\.[0-9]*\.[0-9]*' | cut -c 3-)
+        if [ "$(printf '%s\n' "$go_ver" "$gcil_go_ver" | sort -V | head -n1)" != "$go_ver" ]; then
+           echo "WARNING: Your go version ($go_ver) is greater than the version of go that golangci-lint was built with ($gcil_go_ver)."
+        fi
+
+        if [ -n "${BASE_REF:-}" ]; then
+            echo "Running golangci-lint"
+            golangci-lint --new-from-rev="$BASE_REF" --path-prefix= run
+        else
+            echo "Running golangci-lint without the --new-from-rev option. If you would rather use that option, specify the branch in the BASE_REF environment variable."
+            golangci-lint --path-prefix= run
+        fi
+    fi
 fi
 
 if [ "$UNIT" = 1 ]; then
