Also report the subunit results on failre.

diff --git a/run-checks b/run-checks
--- a/run-checks
+++ b/run-checks
@@ -158,10 +158,15 @@ if [ ! -z "$INTEGRATION" ]; then
     # integration suite in kvm
     if which adt-run >/dev/null 2>&1; then
         echo "Running integration tests on rolling edge"
-        go run integration-tests/main.go --snappy-from-branch
+        result=0
+        go run integration-tests/main.go --snappy-from-branch || result=$?
         # print the results.
         if which subunit2pyunit >/dev/null 2>&1; then
             subunit2pyunit /tmp/snappy-test/output/artifacts/results.subunit
+        fi
+        if [ "$result" -ne 0 ]; then
+            echo "Integration tests failed"
+            exit $results
         fi
     fi
 fi
