run-checks: fail on equality checks w/ ErrNoState (#11816)
* run-checks: fail on equality checks w/ ErrNoState

Signed-off-by: Miguel Pires <miguel.pires@canonical.com>

* run-checks: use spaces instead of tabs

Signed-off-by: Miguel Pires <miguel.pires@canonical.com>

diff --git a/run-checks b/run-checks
--- a/run-checks
+++ b/run-checks
@@ -312,6 +312,13 @@ if [ "$STATIC" = 1 ]; then
         echo "Checking tests formatting"
         ./tests/lib/external/snapd-testing-tools/utils/check-test-format ./tests
     fi
+
+    echo "Checking for usages of !=, == or Equals with ErrNoState"
+    if got=$(grep -n -R -E "(\!=|==|Equals,) (state\.)?ErrNoState" --include=*.go) ; then
+      echo "Don't use equality checks with ErrNoState, use errors.Is() instead"
+      echo "$got"
+      exit 1
+    fi
 fi
 
 if [ "$UNIT" = 1 ]; then
