many: make the change and ensure registries package private

diff --git a/run-checks b/run-checks
--- a/run-checks
+++ b/run-checks
@@ -522,8 +522,8 @@ if [ "$STATIC" = 1 ]; then
     echo ">> [Go] Checking that all ensure helper methods have been registered"
     missing=0
     while IFS=' ' read -r manager func; do
-        if ! grep -rq "swfeats.EnsureReg.Add(\"$manager\",.*\"$func\")" .; then
-            echo "Missing ensure function registration. Add the following to the relevant file: swfeats.EnsureReg.Add(\"$manager\", \"$func\")"
+        if ! grep -rq "swfeats.RegEnsure(\"$manager\",.*\"$func\")" .; then
+            echo "Missing ensure function registration. Add the following to the relevant file: swfeats.RegEnsure(\"$manager\", \"$func\")"
             missing=1
         fi
     done < <(grep -r '.Trace("ensure"' overlord | sed -n 's/.*\.Trace("ensure",.*"manager",.*"\([^"]*\)",.*"func",.*"\([^"]*\)").*/\1 \2/p')
