run-checks: added golangci-lint run

diff --git a/run-checks b/run-checks
--- a/run-checks
+++ b/run-checks
@@ -393,6 +393,25 @@ if [ "$STATIC" = 1 ]; then
       echo "$got"
       exit 1
     fi
+
+    if [ -z "${SKIP_GOLANG_CI_LINT-}" ]; then
+
+        echo "Checking installation of golangci-lint"
+        if ! command -v golangci-lint > /dev/null ; then
+            echo "ERROR: Cannot find golangci-lint. You need to first install the golangci-lint snap"
+            exit 1
+        fi
+        if snap refresh --list | grep golangci-lint; then
+            echo "WARNING: your golangci-lint snap is out of date. The CI will install a fresh version, which may differ from yours."
+        fi
+
+        echo "Running golangci-lint"
+        if [ -n "${GITHUB_BASE_REF:-}" ]; then
+            golangci-lint --new-from-rev="$GITHUB_BASE_REF" --path-prefix= run || exit 1
+        else
+            golangci-lint --path-prefix= run || exit 1
+        fi
+    fi
 fi
 
 if [ "$UNIT" = 1 ]; then
