spread-shellcheck: fixes
Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>

diff --git a/spread-shellcheck b/spread-shellcheck
--- a/spread-shellcheck
+++ b/spread-shellcheck
@@ -1,18 +1,42 @@
 #!/bin/bash
 
+# Copyright (C) 2018 Canonical Ltd
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License version 3 as
+# published by the Free Software Foundation.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+# default shell for shellcheck
 SHELLCHECK_SHELL=${SHELLCHECK_SHELL:-bash}
+# set to non-empty to ignore all errors
 NO_FAIL=${NO_FAIL:-}
+# set to non empty to enable 'set -x'
 D=${D:-}
+# set to non-empty to enable verbose logging
 V=${V:-}
 # file with list of test file that must successfully validate, one file per line
 MUST_PASS=${MUST_PASS:-}
 
+set -e
+
 test -n "$D" && set -x
 
+logv() {
+    if [[ -z "$V" ]]; then return 0;  fi
+
+    echo "$@" >&2
+}
+
 log() {
-    if [[ -n "$V" ]]; then
-        echo "$@"
-    fi
+    echo "$@" >&2
 }
 
 check_file() {
@@ -21,11 +45,11 @@ check_file() {
     local failed
     file=$1
 
-    log "-- checking file $file"
+    logv "-- checking file $file"
     for k in $keys; do
-        log "--- checking section $k"
+        logv "--- checking section $k"
         if ! yq -r < "$file" ".[\"$k\"]" | shellcheck -s "$SHELLCHECK_SHELL" -x - ; then
-            echo "ERROR: $file: shellcheck failed in section '$k'"
+            log  "ERROR: $file: shellcheck failed in section '$k'"
             failed=1
         fi
     done
@@ -38,9 +62,9 @@ check_file() {
             # we need to drop the extra single quotes
             suite="${suite//\'/}"
             for k in $keys; do
-                log "--- checking $suite section $k"
+                logv "--- checking $suite section $k"
                 if ! yq -r < "$file" ".suites[\"$suite\"][\"$k\"]" | shellcheck -s "$SHELLCHECK_SHELL" -x - ; then
-                    echo "ERROR: $file: shellcheck failed in suite $suite section '$k'"
+                    log "ERROR: $file: shellcheck failed in suite $suite section '$k'"
                     failed=1
                 fi
             done
@@ -49,7 +73,7 @@ check_file() {
 
     if [[ "$failed" != 0 && -n "$MUST_PASS" ]] && ! grep -Eqx "$file" "$MUST_PASS" >/dev/null 2>&1 ; then
         failed=0
-        echo "WARNING: ignoring errors in file $file"
+        log "WARNING: ignoring errors in file $file"
     fi
     return $failed
 }
@@ -70,11 +94,12 @@ check_location() {
 }
 
 if ! which yq >/dev/null 2>&1; then
-    echo "please install 'yq'"
-    echo "eg: pip install --user yq"
+    log "please install 'yq'"
+    log "eg: pip install --user yq"
+    exit 1
 fi
 
-keys="prepare prepare-each restore restore-each debug execute"
+keys="prepare prepare-each restore restore-each debug debug-each execute repack"
 errored=0
 
 locations=( "$@" )
@@ -87,6 +112,7 @@ for loc in "${locations[@]}"; do
 done
 
 if [[ "$errored" == 1 && "$NO_FAIL" != "" ]]; then
+    log "WARNING: ignoring errors"
     exit 0
 fi
 
