tests: improve broken snaps detection
On some of the testflnger systems the `tests.invariant` test fails
with broken `core20` snaps after restore. However there is very
little debug information. This commit adds debug information and
also ensures that the `reset_all_snap` checks that all snaps are
okay, not just the active ones.

diff --git a/spread.yaml b/spread.yaml
--- a/spread.yaml
+++ b/spread.yaml
@@ -707,6 +707,16 @@ prepare: |
     # The idea is to have a single directory with all the testing tools
     cp -f "$TESTSLIB"/external/snapd-testing-tools/tools/* "$TESTSTOOLS"
 
+    # ensure there are no broken snaps or the invariant test will fail later
+    if command -v snap; then
+        BROKEN="$(snap list --all | awk '/,?broken,?/ {print $1,$3}')"
+        if [ -n "$BROKEN" ]; then
+            echo "Test system has broken snaps:"
+            snap list --all
+            exit 1
+        fi
+    fi
+    
     # NOTE: At this stage the source tree is available and no more special
     # considerations apply.
     "$TESTSLIB"/prepare-restore.sh --prepare-project
