add code to wait via polling for snapd to come up

diff --git a/tests/main/snap-system-key/task.yaml b/tests/main/snap-system-key/task.yaml
--- a/tests/main/snap-system-key/task.yaml
+++ b/tests/main/snap-system-key/task.yaml
@@ -1,18 +1,23 @@
 summary: Ensure security profile re-generation works with system-key
 
 execute: |
-    restart_snapd() {
+    stop_snapd() {
         systemctl stop snapd.service
         while [ "$(systemctl show -pActiveState snapd.service)" != "ActiveState=inactive" ]; do
             systemctl show -pActiveState snapd.service
             sleep 1
         done
-
+    }
+    start_snapd() {
         systemctl start snapd.service
         while [ "$(systemctl show -pActiveState snapd.service)" != "ActiveState=active" ]; do
             systemctl show -pActiveState snapd.service
             sleep 1
         done
+    }
+    restart_snapd() {
+        stop_snapd
+        start_snapd
     }
 
     echo "Ensure a valid system-key file is on-disk"
@@ -40,11 +45,22 @@ execute: |
     snap install test-snapd-tools
     echo "Change system-key, this ensure that snap run will wait"
     printf '{"version":1}' > /var/lib/snapd/system-key
+    stop_snapd
     if SNAPD_DEBUG_SYSTEM_KEY_WAIT_TIMEOUT_SEC=5 test-snapd-tools.echo bad; then
         echo "snap run should have errored because of changed system-key"
         exit 1
     fi
+    start_snapd
 
+    echo "Ensure snap run does not wait when it can talk to snapd"
+    echo "Change system-key, with running snapd"
+    printf '{"version":1}' > /var/lib/snapd/system-key
+    test-snapd-tools.echo good
+    
     echo "Things work again after a restart of snapd"
     restart_snapd
-    test-snapd-tools.echo good
+    test-snapd-tools.echo good-again
+    if grep '{"version":1}' /var/lib/snapd/system-key; then
+        echo "system-key *not* rewriten test broken"
+        exit 1
+    fi
