New subcommand names and small improvements

diff --git a/tests/core/core-to-snapd-failover16/task.yaml b/tests/core/core-to-snapd-failover16/task.yaml
--- a/tests/core/core-to-snapd-failover16/task.yaml
+++ b/tests/core/core-to-snapd-failover16/task.yaml
@@ -28,7 +28,7 @@ execute: |
   for _ in $(seq 1 2); do
     # get the number of times that snapd.failure was started before we do 
     # anything
-    started_before="$("$TESTSTOOLS"/journal-state get-journalctl-log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
+    started_before="$("$TESTSTOOLS"/journal-state get-log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
 
     echo "Now install the broken snapd"
     if snap install --dangerous ./snapd-broken/snapd_*.snap; then
@@ -40,7 +40,7 @@ execute: |
     #shellcheck disable=SC2165
     for _ in $(seq 60); do
         # get the number of times that snapd.failure was started
-        started_after="$("$TESTSTOOLS"/journal-state get-journalctl-log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
+        started_after="$("$TESTSTOOLS"/journal-state get-log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
         if [ "$started_after" -gt "$started_before" ] ; then
             break
         fi
