test/snapd-many: install snapd 2 times
Try to install snapd multiple times to show that we can invoke
snapd.failure as many times as needed during a single boot, and that we
can refresh the snapd snap on UC16 for the snapd16 test.

Signed-off-by: Ian Johnson <person.uwsome@gmail.com>

diff --git a/tests/core/core-to-snapd-failover16/task.yaml b/tests/core/core-to-snapd-failover16/task.yaml
--- a/tests/core/core-to-snapd-failover16/task.yaml
+++ b/tests/core/core-to-snapd-failover16/task.yaml
@@ -18,31 +18,36 @@ execute: |
   # pick up snap-failure from the current snapd
   (cd ./snapd-broken && snap pack .)
 
-  # get the number of times that snapd.failure was started before we do 
-  # anything
-  started_before="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
+  # try to install it multiple times to ensure that we can revert back to the 
+  # core snap as many times as needed, if a device for some reason keeps wanting
+  # to try to transition to the snapd snap and keeps failing
+  for _ in $(seq 1 2); do
+    # get the number of times that snapd.failure was started before we do 
+    # anything
+    started_before="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
 
-  echo "Now install the broken snapd"
-  if snap install --dangerous ./snapd-broken/snapd_*.snap; then
-      echo "installing a broken snapd should not work, test broken"
-      exit 1
-  fi
+    echo "Now install the broken snapd"
+    if snap install --dangerous ./snapd-broken/snapd_*.snap; then
+        echo "installing a broken snapd should not work, test broken"
+        exit 1
+    fi
 
-  echo "Verify that snapd.failure was activated when we tried to install a broken snapd"
-  for _ in $(seq 60); do
-      # get the number of times that snapd.failure was started
-      started_after="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
-      if [ "$started_after" -gt "$started_before" ] ; then
-          break
-      fi
-      sleep 1
+    echo "Verify that snapd.failure was activated when we tried to install a broken snapd"
+    for _ in $(seq 60); do
+        # get the number of times that snapd.failure was started
+        started_after="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
+        if [ "$started_after" -gt "$started_before" ] ; then
+            break
+        fi
+        sleep 1
+    done
+
+    echo "Verify we got the expected error message"
+    snap change --last=install|MATCH "there was a snapd rollback across the restart"
+    echo "No snapd snap is installed"
+    not snap list snapd
+
+    test ! -e /etc/systemd/system/snapd.service
+    test ! -e /etc/systemd/system/usr-lib-snapd.mount
+    test ! -e /snap/snapd/x1
   done
-
-  echo "Verify we got the expected error message"
-  snap change --last=install|MATCH "there was a snapd rollback across the restart"
-  echo "No snapd snap is installed"
-  not snap list snapd
-
-  test ! -e /etc/systemd/system/snapd.service
-  test ! -e /etc/systemd/system/usr-lib-snapd.mount
-  test ! -e /snap/snapd/x1
diff --git a/tests/core/snapd-failover/task.yaml b/tests/core/snapd-failover/task.yaml
--- a/tests/core/snapd-failover/task.yaml
+++ b/tests/core/snapd-failover/task.yaml
@@ -91,36 +91,44 @@ execute: |
         unsquashfs -d ./snapd-broken "$SNAPD_SNAP"
         echo "" > ./snapd-broken/usr/lib/snapd/snapd
         (cd ./snapd-broken && snap pack .)
-        echo "Now install the broken snapd"
-        if snap install --dangerous ./snapd-broken/snapd_*.snap; then
-            echo "installing a broken snapd should not work, test broken"
-            exit 1
-        fi
 
-        echo "Verify that snapd.failure was activated when we tried to install a broken snapd"
-        for _ in $(seq 60); do
-            # get the number of times that snapd.failure was started
-            started_after="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
-            if [ "$started_after" -gt "$started_before" ] ; then
-                break
+        # try to install a broken snapd snap multiple times, so that if a device
+        # wants to keep trying a refresh to a broken snapd snap for some reason
+        # it will be able to revert and fallback as many times as needed
+        for _ in $(seq 1 2); do
+            started_before="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
+
+            echo "Install the broken snapd"
+            if snap install --dangerous ./snapd-broken/snapd_*.snap; then
+                echo "installing a broken snapd should not work, test broken"
+                exit 1
             fi
-            sleep 1
+
+            echo "Verify that snapd.failure was activated when we tried to install a broken snapd"
+            for _ in $(seq 60); do
+                # get the number of times that snapd.failure was started
+                started_after="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
+                if [ "$started_after" -gt "$started_before" ] ; then
+                    break
+                fi
+                sleep 1
+            done
+
+            # just because snapd.failure.service is active doesn't mean that we are 
+            # fully ready; we should wait until the snap command shows up again
+            echo "And verify that snap commands still work and snapd is reverted"
+            retry-tool -n 30 --wait 1 bash -c 'snap list | MATCH "^snapd .* $current .*"'
+
+            echo "Verify we got the expected error message"
+            snap change --last=install|MATCH "there was a snapd rollback across the restart"
+
+            echo "restart snapd and ensure we can still talk to it"
+            systemctl restart snapd.socket snapd.service
+
+            # we should still have the snapd snap and it should have the revision we had
+            # before the broken one was installed
+            snap list | MATCH "^snapd .* $current .*"
         done
-
-        # just because snapd.failure.service is active doesn't mean that we are 
-        # fully ready; we should wait until the snap command shows up again
-        echo "And verify that snap commands still work and snapd is reverted"
-        retry-tool -n 30 --wait 1 bash -c 'snap list | MATCH "^snapd .* $current .*"'
-
-        echo "Verify we got the expected error message"
-        snap change --last=install|MATCH "there was a snapd rollback across the restart"
-
-        echo "restart snapd and ensure we can still talk to it"
-        systemctl restart snapd.socket snapd.service
-
-        # we should still have the snapd snap and it should have the revision we had
-        # before the broken one was installed
-        snap list | MATCH "^snapd .* $current .*"
 
         # we cannot undo the core -> snapd installation we did in the prepare 
         # section during restore, because we can't reboot during restore, so instead
diff --git a/tests/core/snapd16/task.yaml b/tests/core/snapd16/task.yaml
--- a/tests/core/snapd16/task.yaml
+++ b/tests/core/snapd16/task.yaml
@@ -22,13 +22,22 @@ execute: |
         echo "And snapd from the snap is run in the CGroup"
         systemctl status snapd|MATCH "/snap/snapd/x1/usr/lib/snapd/snapd"
 
+        echo "And we can refresh the snapd snap again"
+        prev=$(readlink /snap/snapd/current)
+        snap install snapd-from-core.snap --dangerous
+        next=$(readlink /snap/snapd/current)
+        if [ "$next" = "$prev" ]; then
+            echo "Failed to refresh the snapd snap, still on same revision"
+            exit 1
+        fi
+
         echo "And after a reboot the snapd snap is still ok"
         REBOOT
     elif [ "$SPREAD_REBOOT" = 1 ]; then
         echo "still installed"
         snap list snapd
         echo "and running the right snapd"
-        systemctl status snapd|MATCH "/snap/snapd/x1/usr/lib/snapd/snapd"
+        systemctl status snapd|MATCH "/snap/snapd/x2/usr/lib/snapd/snapd"
 
         # RESTORE CODE
         # we cannot restore in "restore:" because we need a reboot
