tests/main: convert all remaining tests to use forced-devmode switch

diff --git a/tests/main/interfaces-network-observe/task.yaml b/tests/main/interfaces-network-observe/task.yaml
--- a/tests/main/interfaces-network-observe/task.yaml
+++ b/tests/main/interfaces-network-observe/task.yaml
@@ -1,9 +1,5 @@
 summary: Ensure that the network-observe interface works
 
-systems:
-    # No confinement (AppArmor, Seccomp) available on these systems
-    - -debian-*
-
 details: |
     The network-observe interface allows a snap to query the network status information.
 
@@ -55,14 +51,18 @@ execute: |
     echo "Then the snap command can query network status information"
     network-observe-consumer | grep -P "0.0.0.0:$PORT.*?LISTEN"
 
-    echo "===================================="
+    if ! snap forced-devmode ; then
+        echo "===================================="
 
-    echo "When the plug is disconnected"
-    snap disconnect network-observe-consumer:network-observe
-    snap interfaces | grep -Pzq "$DISCONNECTED_PATTERN"
+        echo "When the plug is disconnected"
+        snap disconnect network-observe-consumer:network-observe
+        snap interfaces | grep -Pzq "$DISCONNECTED_PATTERN"
 
-    echo "Then the snap command can not query network status information"
-    if network-observe-consumer 2>net-query.output; then
-        echo "Expected error caling command with disconnected plug"
+        echo "Then the snap command can not query network status information"
+        if network-observe-consumer 2>net-query.output; then
+            echo "Expected error caling command with disconnected plug"
+        fi
+        cat net-query.output | grep -Pq "Permission denied"
+    else
+        echo "WARNING: Skipping confinement checks as snapd runs in forced devmode"
     fi
-    cat net-query.output | grep -Pq "Permission denied"
diff --git a/tests/main/interfaces-system-observe/task.yaml b/tests/main/interfaces-system-observe/task.yaml
--- a/tests/main/interfaces-system-observe/task.yaml
+++ b/tests/main/interfaces-system-observe/task.yaml
@@ -1,9 +1,5 @@
 summary: Ensures that the system-observe interface works.
 
-systems:
-    # No confinement (AppArmor, Seccomp) available on these systems
-    - -debian-*
-
 details: |
     A snap declaring the system-observe plug is defined, its command
     just calls ps -ax.
@@ -37,14 +33,18 @@ execute: |
     expected="(?s)/dev/tty.*?serial"
     su -l -c "system-observe-consumer" test | grep -Pq "$expected"
 
-    echo "==========================================="
+    if ! snap forced-devmode ; then
+        echo "==========================================="
 
-    echo "When the plug is disconnected"
-    snap disconnect system-observe-consumer:system-observe
-    snap interfaces | grep -Pzq "$DISCONNECTED_PATTERN"
+        echo "When the plug is disconnected"
+        snap disconnect system-observe-consumer:system-observe
+        snap interfaces | grep -Pzq "$DISCONNECTED_PATTERN"
 
-    echo "Then the snap is not able to get system information"
-    if su -l -c "system-observe-consumer" test; then
-        echo "Expected error with plug disconnected"
-        exit 1
+        echo "Then the snap is not able to get system information"
+        if su -l -c "system-observe-consumer" test; then
+            echo "Expected error with plug disconnected"
+            exit 1
+        fi
+    else
+        echo "WARNING: Skipping confinement checks as snapd runs in forced devmode"
     fi
