tests:core:netplan: skip 'netplan generate' on UC16

diff --git a/tests/core/netplan/task.yaml b/tests/core/netplan/task.yaml
--- a/tests/core/netplan/task.yaml
+++ b/tests/core/netplan/task.yaml
@@ -44,10 +44,14 @@ execute: |
             exit 1
         fi
 
-        echo "Running netplan generate without network-setup-control fails"
-        if netplan-snap.netplan generate; then
-            echo "Expected access denied error for netplan generate"
-            exit 1
+        if ! os.query is-core16; then
+            echo "Running netplan generate without network-setup-control fails"
+            if netplan-snap.netplan generate; then
+                echo "Expected access denied error for netplan generate"
+                exit 1
+            fi
+        else
+            echo "Skipping netplan generate on UC16"
         fi
 
         echo "Count how many network service restarts happened before calling netplan apply"
@@ -65,10 +69,14 @@ execute: |
             exit 1
         fi
 
-        echo "Running netplan generate now works"
-        if ! netplan-snap.netplan generate; then
-            echo "Unexpected error running netplan generate"
-            exit 1
+        if ! os.query is-core16; then
+            echo "Running netplan generate now works"
+            if ! netplan-snap.netplan generate; then
+                echo "Unexpected error running netplan generate"
+                exit 1
+            fi
+        else
+            echo "Skipping netplan generate on UC16"
         fi
 
         echo "Ensure that network config was stopped and restarted from netplan"
