kerberos-tickets: Allow writes to the ticket cache.
The kerberos-tickets interface allows reading the Kerberos cache, which allows
connecting snaps to authenticate to Kerberos-gated services by presenting the
ticket granting ticket (TGT) therein.

However, the snaps cannot save the service ticket (ST) thereby received to
the cache. This causes the snaps to have to present the TGT every time,
repeatly hitting the key distribution center and causing noticeable delays
(LP:2138268) for non-trivial servers.

diff --git a/tests/main/interfaces-kerberos-tickets/kerberos-tickets-consumer/bin/kerberos-tickets-consumer b/tests/main/interfaces-kerberos-tickets/kerberos-tickets-consumer/bin/kerberos-tickets-consumer
--- a/tests/main/interfaces-kerberos-tickets/kerberos-tickets-consumer/bin/kerberos-tickets-consumer
+++ b/tests/main/interfaces-kerberos-tickets/kerberos-tickets-consumer/bin/kerberos-tickets-consumer
@@ -3,4 +3,4 @@ ticket=${KRB5CCNAME#FILE:}
 echo "KRB5CCNAME:$KRB5CCNAME"
 cat "$ticket" 2>/dev/null || echo "cannot read ticket $ticket"
 # Try to write anything random to the ticket file.
-echo 8 2>/dev/null >>"$ticket" || echo "cannot write to ticket $ticket"
+echo "appended contents" 2>/dev/null >>"$ticket" || echo "cannot write to ticket $ticket"
