i/builtin,tests: restrict kerberos cache directory access
Signed-off-by: Oliver Calder <oliver.calder@canonical.com>

diff --git a/tests/main/interfaces-kerberos-tickets/kerberos-tickets-consumer/bin/kerberos-tickets-consumer b/tests/main/interfaces-kerberos-tickets/kerberos-tickets-consumer/bin/kerberos-tickets-consumer
--- a/tests/main/interfaces-kerberos-tickets/kerberos-tickets-consumer/bin/kerberos-tickets-consumer
+++ b/tests/main/interfaces-kerberos-tickets/kerberos-tickets-consumer/bin/kerberos-tickets-consumer
@@ -2,12 +2,13 @@
 cache=${KRB5CCNAME#*:}
 ticket=$cache
 if [ "${KRB5CCNAME#DIR:}" != "$KRB5CCNAME" ]; then
-    ticket="$cache/ticket"
+    ticket="$cache/tkt_foo"
 fi
 echo "KRB5CCNAME:$KRB5CCNAME"
 cat "$ticket" 2>/dev/null || echo "cannot read ticket $ticket"
 # Try to write anything random to the ticket file/dir.
 echo "appended contents" 2>/dev/null >>"$ticket" || echo "cannot write to ticket $ticket"
 if [ "${KRB5CCNAME#DIR:}" != "$KRB5CCNAME" ]; then
-    echo "created contents" 2>/dev/null >"$cache/created" || echo "cannot create ticket in $cache"
+	cat "$cache/primary" 2>/dev/null || echo "cannot read cache primary $cache/primary"
+    echo "created contents" 2>/dev/null >"$cache/tkt_bar" || echo "cannot create ticket in $cache"
 fi
