Extra check in the spread test.

diff --git a/tests/main/snapctl-services/task.yaml b/tests/main/snapctl-services/task.yaml
--- a/tests/main/snapctl-services/task.yaml
+++ b/tests/main/snapctl-services/task.yaml
@@ -72,3 +72,7 @@ execute: |
     echo "Reinstalling the snap with configure hook calling snapctl restart works"
     snap set test-snapd-service command=restart
     install_local test-snapd-service
+    if journalctl|grep -q "error running snapctl"; then
+        echo "snapctl should not report errors"
+        exit 1
+    fi
