Refactor to use open/openat/mkdirat instead of just mkdir.

diff --git a/tests/test_create_user_data b/tests/test_create_user_data
--- a/tests/test_create_user_data
+++ b/tests/test_create_user_data
@@ -32,156 +32,131 @@ exit_group
 i-dont-exit
 EOF
 
-# Set current user data variable
-export SNAP_USER_DATA=$TMP/user_data
+# $1: Path to check existence for and potentially remove at the end
+# $2: Profile name
+# $3: True if success is expected, false otherwise
+run_launcher() {
+   pass=false
+   if $L appid $2 /bin/true 2>/dev/null; then
+      if $3; then
+         if [ ! -d "$1" ]; then
+            pass=false
+         fi
 
-printf "Test that an unrestricted launcher creates \$SNAP_USER_DATA"
-if $L appid unrestricted /bin/true / >/dev/null; then
-   if [ ! -d "$SNAP_USER_DATA" ]; then
-      FAIL
+         pass=true
+      else
+         pass=false
+      fi
+   else
+      if $3; then
+         pass=false
+      else
+         pass=true
+      fi
    fi
 
-   PASS
-else
-   FAIL
-fi
-
-rmdir $SNAP_USER_DATA
-
-printf "Test that a restricted launcher creates \$SNAP_USER_DATA"
-if $L appid restricted /bin/true 2>/dev/null; then
-   if [ ! -d "$SNAP_USER_DATA" ]; then
-      FAIL
+   if [ -d "$1" ]; then
+      rmdir $1
    fi
 
-   PASS
-else
-   FAIL
-fi
+   if $pass; then
+      return 0
+   else
+      return 1
+   fi
+}
 
-# At this point, $SNAP_USER_DATA should exist. Now make sure that the launcher
-# will run if it already exists.
-printf "Test that an unrestricted launcher works when \$SNAP_USER_DATA exists"
-if $L appid unrestricted /bin/true / >/dev/null; then
-   if [ ! -d "$SNAP_USER_DATA" ]; then
+# $1 = $SNAP_USER_DATA definition
+# $2 = Profile name
+# $3 = True if success is expected, false otherwise
+run_current() {
+   export SNAP_USER_DATA=$1
+   run_launcher $1 $2 $3
+   pass=$?
+   unset SNAP_USER_DATA
+
+   return $pass
+}
+
+# $1 = $SNAP_APP_USER_DATA_PATH definition
+# $2 = Profile name
+# $3 = True if success is expected, false otherwise
+run_deprecated() {
+   export SNAP_APP_USER_DATA_PATH=$1
+   run_launcher $1 $2 $3
+   pass=$?
+   unset SNAP_APP_USER_DATA_PATH
+
+   return $pass
+}
+
+# $1 = User data path
+# $2 = Profile name
+# $3 = True if success is expected, false otherwise
+run_both() {
+   run_current $1 $2 $3
+   current_pass=$?
+   run_deprecated $1 $2 $3
+   deprecated_pass=$?
+
+   if [ $current_pass -a $deprecated_pass ]; then
+      PASS
+   else
       FAIL
    fi
+}
 
+printf "Test that an unrestricted launcher creates user data"
+run_both $TMP/user_data unrestricted true
+
+printf "Test that a restricted launcher creates user data"
+run_both $TMP/user_data restricted true
+
+printf "Test that an unrestricted launcher creates user data with parent directory"
+run_both $TMP/parent/user_data unrestricted true
+
+printf "Test that a restricted launcher creates user data with parent directory"
+run_both $TMP/parent/user_data restricted true
+
+printf "Test that user data can contain multiple path separators"
+run_both $TMP//user_data unrestricted true
+
+printf "Test that user data must be absolute"
+run_both "../foo" unrestricted false
+
+printf "Testing that user data cannot be contained within a symlink"
+mkdir $TMP/nefarious_parent
+ln -s $TMP/nefarious_parent $TMP/parent
+run_both $TMP/parent/user_data unrestricted, false
+
+printf "Test that an unrestricted launcher works when user data exists (current)"
+mkdir $TMP/user_data
+if run_current $TMP/user_data unrestricted true; then
    PASS
 else
    FAIL
 fi
 
-printf "Test that an restricted launcher works when \$SNAP_USER_DATA exists"
-if $L appid restricted /bin/true 2>/dev/null; then
-   if [ ! -d "$SNAP_USER_DATA" ]; then
-      FAIL
-   fi
-
+printf "Test that an restricted launcher works when user data exists (current)"
+mkdir $TMP/user_data
+if run_current $TMP/user_data restricted true; then
    PASS
 else
    FAIL
 fi
 
-rmdir $SNAP_USER_DATA
-
-# Set the user data dir to be nested under a non-existing parent directory
-export SNAP_USER_DATA=$TMP/parent/user_data
-
-printf "Test that an unrestricted launcher creates \$SNAP_USER_DATA with parent directory"
-if $L appid unrestricted /bin/true / >/dev/null; then
-   if [ ! -d "$SNAP_USER_DATA" ]; then
-      FAIL
-   fi
-
+printf "Test that an unrestricted launcher works when user data exists (deprecated)"
+mkdir $TMP/user_data
+if run_deprecated $TMP/user_data unrestricted true; then
    PASS
 else
    FAIL
 fi
 
-rmdir $SNAP_USER_DATA
-
-printf "Test that a restricted launcher creates \$SNAP_USER_DATA with parent directory"
-if $L appid restricted /bin/true 2>/dev/null; then
-   if [ ! -d "$SNAP_USER_DATA" ]; then
-      FAIL
-   fi
-
+printf "Test that an restricted launcher works when user data exists (deprecated)"
+mkdir $TMP/user_data
+if run_deprecated $TMP/user_data restricted true; then
    PASS
 else
    FAIL
-fi
-
-rmdir $SNAP_USER_DATA
-
-printf "Test that \$SNAP_USER_DATA must be absolute"
-export SNAP_USER_DATA="../foo"
-if $L appid restricted /bin/true 2>/dev/null; then
-   FAIL
-else
-   PASS
-fi
-
-# Unset current user data variable so we can test the deprecated one
-unset SNAP_USER_DATA
-
-# Set deprecated user data variable
-export SNAP_APP_USER_DATA_PATH=$TMP/user_data
-
-printf "Test that an unrestricted launcher creates \$SNAP_APP_USER_DATA_PATH"
-if $L appid unrestricted /bin/true / >/dev/null; then
-   if [ ! -d "$SNAP_APP_USER_DATA_PATH" ]; then
-      FAIL
-   fi
-
-   PASS
-else
-   FAIL
-fi
-
-rmdir $SNAP_APP_USER_DATA_PATH
-
-printf "Test that a restricted launcher creates \$SNAP_APP_USER_DATA_PATH"
-if $L appid restricted /bin/true 2>/dev/null; then
-   if [ ! -d "$SNAP_APP_USER_DATA_PATH" ]; then
-      FAIL
-   fi
-
-   PASS
-else
-   FAIL
-fi
-
-# At this point, $SNAP_APP_USER_DATA_PATH should exist. Now make sure that the
-# launcher will still run if it already exists.
-printf "Test that an unrestricted launcher works when \$SNAP_APP_USER_DATA_PATH exists"
-if $L appid unrestricted /bin/true / >/dev/null; then
-   if [ ! -d "$SNAP_APP_USER_DATA_PATH" ]; then
-      FAIL
-   fi
-
-   PASS
-else
-   FAIL
-fi
-
-printf "Test that an restricted launcher works when \$SNAP_APP_USER_DATA_PATH exists"
-if $L appid restricted /bin/true 2>/dev/null; then
-   if [ ! -d "$SNAP_APP_USER_DATA_PATH" ]; then
-      FAIL
-   fi
-
-   PASS
-else
-   FAIL
-fi
-
-rmdir $SNAP_APP_USER_DATA_PATH
-
-printf "Test that \$SNAP_APP_USER_DATA_PATH must be absolute"
-export SNAP_APP_USER_DATA_PATH="../foo"
-if $L appid restricted /bin/true 2>/dev/null; then
-   FAIL
-else
-   PASS
 fi
