tests/nested/manual/core20-cloud-init-maas-signed-seed-data: add gadget variant
Add variants for the gadget snap having cloud.conf that allows MAAS and a
cloud.conf which disallows any datasource in it.

Also add an unrelated datasource file to ubuntu-seed always that gets ignored
since it is for a currently unsupported datasource (GCE).

Signed-off-by: Ian Johnson <ian.johnson@canonical.com>

diff --git a/tests/nested/manual/core20-cloud-init-maas-signed-seed-data/task.yaml b/tests/nested/manual/core20-cloud-init-maas-signed-seed-data/task.yaml
--- a/tests/nested/manual/core20-cloud-init-maas-signed-seed-data/task.yaml
+++ b/tests/nested/manual/core20-cloud-init-maas-signed-seed-data/task.yaml
@@ -3,8 +3,17 @@ summary: Test that UC20 can use cloud-init config on ubuntu-seed with grade sign
 systems: [ubuntu-20.04-64]
 
 environment:
+  # three variants
+  # one with gadget that says maas
+  GADGET_DATASOURCE/gadgetsaysmaas: maas
+  # one that says explicitly no datasource
+  GADGET_DATASOURCE/gadgetsaysnone: explicitly-none
+  # and one that has no opinion (like the default pc gadget)
+  GADGET_DATASOURCE/gadgetwithoutopinion: absent
+
   # use tpm + secure boot to get full disk encryption, this is explicitly needed
-  # for grade: secured
+  # for grade: secured but is just nice to have for proof of conception with
+  # grade signed too
   NESTED_ENABLE_TPM: true
   NESTED_ENABLE_SECURE_BOOT: true
 
@@ -24,7 +33,7 @@ environment:
   NESTED_CUSTOM_AUTO_IMPORT_ASSERTION: $TESTSLIB/assertions/developer1-auto-import.assert
 
   NESTED_CUSTOM_MODEL: $TESTSLIB/assertions/developer1-20-signed.model
-  NESTED_IMAGE_ID: grade-signed-cloud-init-maas
+  NESTED_IMAGE_ID: grade-signed-cloud-init-maas-$GADGET_DATASOURCE
 
   # for the fake store
   NESTED_FAKESTORE_BLOB_DIR: $(pwd)/fake-store-blobdir
@@ -39,6 +48,8 @@ prepare: |
       echo "This test needs test keys to be trusted"
       exit
   fi
+
+  snap install remarshal jq
 
   #shellcheck source=tests/lib/nested.sh
   . "$TESTSLIB/nested.sh"
@@ -60,7 +71,9 @@ prepare: |
 
   # modify and repack gadget snap to add a defaults section and use our own
   # prepare-device hook to use the fakedevicesvc
-  mkdir "$(nested_get_extra_snaps_path)"
+  EXTRA_SNAPS_PATH="$(nested_get_extra_snaps_path)"
+  mkdir -p "$EXTRA_SNAPS_PATH"
+  tests.cleanup defer rm -rf "$EXTRA_SNAPS_PATH"
 
   # Get the snakeoil key and cert for signing gadget assets (shim)
   KEY_NAME=$(nested_get_snakeoil_key)
@@ -78,6 +91,20 @@ prepare: |
   sed defaults.yaml -e "s/@HOLD-TIME@/$(date --date='next week' +%Y-%m-%dT%H:%M:%S%:z)/" >> \
     pc-gadget/meta/gadget.yaml
 
+  # install the cloud.conf for the variant
+  case "$GADGET_DATASOURCE" in 
+    maas)
+      cp gadget-says-maas.conf pc-gadget/cloud.conf
+      ;;
+    "explicitly-none")
+      cp gadget-says-none.conf pc-gadget/cloud.conf
+      ;;
+    absent)
+      # do nothing - no opinion from gadget.yaml about cloud-init, this is the
+      # default case like with our published images using the pc/pi gadget snaps
+      ;;
+  esac
+
   # copy the prepare-device hook to use our fakedevicesvc
   mkdir -p pc-gadget/meta/hooks/
   cp prepare-device pc-gadget/meta/hooks/
@@ -90,6 +117,8 @@ prepare: |
 
   #shellcheck disable=SC2148
   systemd-run --collect --unit fakedevicesvc fakedevicesvc localhost:11029
+  # stop fake device svc after we are done
+  tests.cleanup defer systemctl stop fakedevicesvc
 
   tests.nested build-image core
 
@@ -106,6 +135,7 @@ prepare: |
   nested_add_file_to_vm "$img" 50-cloudconfig-maas-reporting.cfg
   nested_add_file_to_vm "$img" 50-cloudconfig-maas-ubuntu-sso.cfg
   nested_add_file_to_vm "$img" 50-curtin-networking.cfg
+  nested_add_file_to_vm "$img" 50-cloudconfig-gce-unsupported-config.cfg
 
   # first boot will now copy the cloud-init config we put on ubuntu-seed to 
   # the run system, filtering it in the process
@@ -116,9 +146,6 @@ restore: |
       echo "This test needs test keys to be trusted"
       exit
   fi
-
-  # stop fake device svc
-  # systemctl stop fakedevicesvc
 
   #shellcheck source=tests/lib/store.sh
   . "$TESTSLIB"/store.sh
@@ -141,53 +168,117 @@ execute: |
   . "$TESTSLIB/nested.sh"
 
   echo "Waiting for snapd to react to cloud-init"
-  seen=0
-  # the first message is about snapd noticing that cloud-init is in error, and
-  # for how long snapd will wait for cloud-init, this message should show up
-  # relatively quickly
-  for i in $(seq 60); do
-      if tests.nested exec "sudo journalctl --no-pager -u snapd" | MATCH "cloud-init reported to be in error state, will disable in 3 minutes"; then
-          seen=1
-          break
-      fi
-      sleep 1
-  done
-  if [ "$seen" = "0" ]; then
-      echo "snapd did not notice cloud-init in error state, test failed"
-      exit 1
-  fi
-  seen=0
 
-  # we now wait for 3 minutes before snapd gives up waiting and disables 
-  # cloud-init
-  for i in $(seq 200); do
-      if tests.nested exec "sudo journalctl --no-pager -u snapd" | MATCH "reported to be in error state after 3 minutes"; then
-          seen=1
-          break
-      fi
-      sleep 1
-  done
+  # there are two options here, one is where we actually let cloud-init stay 
+  # enabled with the variant where the gadget allowed it, in which case 
+  # cloud-init will be in error, and we actually have to check for two messages,
+  # and the other is where cloud-init is not allowed to run at all by disabling
+  # all datasources in which case snapd notices cloud-init as being disabled
+  if [ "$GADGET_DATASOURCE" = "explicitly-none" ]; then
+    seen=0
 
-  if [ "$seen" = "0" ]; then
-      echo "snapd did not disable cloud-init, test failed"
-      exit 1
+    for i in $(seq 60); do
+        if tests.nested exec "sudo journalctl --no-pager -u snapd" | MATCH "cloud-init reported to be in disabled state"; then
+            seen=1
+            break
+        fi
+        sleep 1
+    done
+    if [ "$seen" = "0" ]; then
+        echo "snapd did not notice cloud-init in disabled state, test failed"
+        exit 1
+    fi
+
+    tests.nested exec "cloud-init status" | MATCH "status: disabled"
+
+  else
+    seen=0
+
+    # the first message is about snapd noticing that cloud-init is in error, and
+    # for how long snapd will wait for cloud-init, this message should show up
+    # relatively quickly
+    for i in $(seq 60); do
+        if tests.nested exec "sudo journalctl --no-pager -u snapd" | MATCH "cloud-init reported to be in error state, will disable in 3 minutes"; then
+            seen=1
+            break
+        fi
+        sleep 1
+    done
+    if [ "$seen" = "0" ]; then
+        echo "snapd did not notice cloud-init in error state, test failed"
+        exit 1
+    fi
+    seen=0
+
+    # we now wait for 3 minutes before snapd gives up waiting and disables 
+    # cloud-init
+    for i in $(seq 200); do
+        if tests.nested exec "sudo journalctl --no-pager -u snapd" | MATCH "reported to be in error state after 3 minutes"; then
+            seen=1
+            break
+        fi
+        sleep 1
+    done
+
+    if [ "$seen" = "0" ]; then
+        echo "snapd did not disable cloud-init, test failed"
+        exit 1
+    fi
+
+    tests.nested exec "cloud-init status" | MATCH "status: error"
   fi
 
   echo "Ensuring that cloud-init got disabled"
-  tests.nested exec "cloud-init status" | MATCH "status: error"
+  # either in the case of the gadget saying no datasources or in the case of the
+  # MAAS datasource being broken and thus getting eventually disabled by snapd
   tests.nested exec "test -f /etc/cloud/cloud-init.disabled"
 
   echo "Relevant files were copied"
-  tests.nested exec "test -f /etc/cloud/cloud.cfg.d/90_50-cloudconfig-maas-cloud-config.cfg"
-  tests.nested exec "test -f /etc/cloud/cloud.cfg.d/90_50-cloudconfig-maas-datasource.cfg"
-  tests.nested exec "test -f /etc/cloud/cloud.cfg.d/90_50-cloudconfig-maas-reporting.cfg"
-  tests.nested exec "test -f /etc/cloud/cloud.cfg.d/90_50-curtin-networking.cfg"
+  if [ "$GADGET_DATASOURCE" = "explicitly-none" ]; then
+    # gadget said no datasources so nothing was copied
+    tests.nested exec "! test -f /etc/cloud/cloud.cfg.d/90_50-cloudconfig-maas-cloud-config.cfg"
+    tests.nested exec "! test -f /etc/cloud/cloud.cfg.d/90_50-cloudconfig-maas-datasource.cfg"
+    tests.nested exec "! test -f /etc/cloud/cloud.cfg.d/90_50-cloudconfig-maas-reporting.cfg"
+    tests.nested exec "! test -f /etc/cloud/cloud.cfg.d/90_50-curtin-networking.cfg"
+  else
+    tests.nested exec "test -f /etc/cloud/cloud.cfg.d/90_50-cloudconfig-maas-cloud-config.cfg"
+    tests.nested exec "test -f /etc/cloud/cloud.cfg.d/90_50-cloudconfig-maas-datasource.cfg"
+    tests.nested exec "test -f /etc/cloud/cloud.cfg.d/90_50-cloudconfig-maas-reporting.cfg"
+    tests.nested exec "test -f /etc/cloud/cloud.cfg.d/90_50-curtin-networking.cfg"
+  fi
 
   echo "Filtered files were not copied"
   tests.nested exec "! test -f /etc/cloud/cloud.cfg.d/90_50-cloudconfig-maas-ubuntu-sso.cfg"
+  tests.nested exec "! test -f /etc/cloud/cloud.cfg.d/90_50-cloudconfig-gce-unsupported-config.cfg"
 
-  echo "The datasource_list restriction file was installed"
-  tests.nested exec "test -f /etc/cloud/cloud.cfg.d/99_snapd_datasource.cfg"
+  # check that the gadget cloud.conf was copied too if it exists and is 
+  # meaningful
+  echo "The gadget cloud.conf was copied if it was in the gadget"
+  if [ "$GADGET_DATASOURCE" = absent ]; then
+    tests.nested exec "! test -f /etc/cloud/cloud.cfg.d/80_device_gadget.cfg"
+  else
+    tests.nested exec "test -f /etc/cloud/cloud.cfg.d/80_device_gadget.cfg"
+  fi
+
+  echo "The datasource_list restriction file was installed if we copied files"
+
+  echo "and has the expected contents"
+  if [ "$GADGET_DATASOURCE" = "explicitly-none" ]; then
+    # we only copied files from ubuntu-seed if the intersection between what we
+    # statically support and what the gadget says and what ubuntu-seed says is
+    # not empty, so the only case where files don't get installed of the 3 
+    # variants is where the gadget datasource says explicitly none
+    tests.nested exec "! test -f /etc/cloud/cloud.cfg.d/99_snapd_datasource.cfg"
+  else
+    tests.nested exec "test -f /etc/cloud/cloud.cfg.d/99_snapd_datasource.cfg"
+    tests.nested exec "cat /etc/cloud/cloud.cfg.d/99_snapd_datasource.cfg" > datasource_restrict.cfg
+    # check that it has only MAAS
+    #shellcheck disable=SC2002
+    cat datasource_restrict.cfg | yaml2json | jq -r '."datasource_list" | .[]' | MATCH MAAS
+    #shellcheck disable=SC2002
+    test "$(cat datasource_restrict.cfg | yaml2json | jq -r '."datasource_list" | .[]' | wc -l)" = 1
+    
+  fi
 
   # note that zzzz_snapd.cfg is not installed because cloud-init is in error and
   # thus we just disable cloud-init
