tests: make prompting-client integration tests support temporal cache
Ubuntu kernels 7.0 and should support a temporal cache at the AppArmor
profile level. That is, if snapd sends back a reply to the kernel, that
reply will be cached for that filepath if there is a request for the
same path in the future, within the time limit.

Because of this, various prompting integration tests need to change, as
they assume e.g. that piping echo to a file will require two requests,
one for creating the file and one for writing to it, which is no longer
the case with the temporal cache.

To accomplish this, the scripts for the prompting client are now split,
with separate scripts with the `-temporal` suffix included when there
must be a difference in the expected prompts depending on whether the
temporal cache is enabled. In the test prepare, check whether the kernel
supports the temporal cache by checking for the presence of
`/proc/sys/kernel/apparmor_cache_timeout`, and if so, replaces the
default script with the script with the `-temporal` suffix.

Additionally, add several more test variants to exercise the temporal
cache.

Signed-off-by: Oliver Calder <oliver.calder@canonical.com>

diff --git a/tests/main/apparmor-prompting-integration-tests/task.yaml b/tests/main/apparmor-prompting-integration-tests/task.yaml
--- a/tests/main/apparmor-prompting-integration-tests/task.yaml
+++ b/tests/main/apparmor-prompting-integration-tests/task.yaml
@@ -31,7 +31,9 @@ environment:
     VARIANT/create_multiple_not_actioned_by_other_pid_single_deny: create_multiple_not_actioned_by_other_pid_single_deny
     VARIANT/write_read_multiple_actioned_by_other_pid_allow_deny: write_read_multiple_actioned_by_other_pid_allow_deny
     VARIANT/write_read_multiple_actioned_by_other_pid_deny_allow: write_read_multiple_actioned_by_other_pid_deny_allow
-    VARIANT/create_write_chmod_single_allow: create_write_chmod_single_allow
+    VARIANT/create_write_chmod_same_fd_single_allow: create_write_chmod_same_fd_single_allow
+    VARIANT/create_write_chmod_same_path_single_allow: create_write_chmod_same_path_single_allow
+    VARIANT/create_write_write_same_path_single_deny: create_write_write_same_path_single_deny
 
     TIMEOUT: "30" # Define common timeout which can be modified as needed
 
@@ -47,33 +49,46 @@ skip:
       reason: Ubuntu 22.04 AppArmor parser doesn't support prompting without reexec
 
 prepare: |
-    # create_write_chmod_single requires kernel 7.0 or later and go
-    if [ "$VARIANT" = create_write_chmod_single_allow ]; then
-        if os.query is-kernel-lt 7.0; then
-            echo "Kernel 7.0 is required for temporal caching for lifespan single" && exit 0
+    # Check whether kernel supports temporal cache, and whether it should, and
+    # whether the there is a temporal cache script for this variant.
+    if [ -e /proc/sys/kernel/apparmor_cache_timeout ] ; then
+        echo "Kernel supports apparmor temporal cache"
+        if [ -f "${VARIANT}-temporal.json" ] ; then
+            echo "Using script intended for kernels with temporal cache"
+            touch using-temporal-script
+            cp "${VARIANT}-temporal.json" "${VARIANT}.json"
+        else
+            echo "Test variant does not have a script for temporal cache"
         fi
+    elif os.query is-kernel-ge 7.0 ; then
+        echo "ERROR: kernel is at least 7.0, but doesn't support temporal cache"
+        exit 1
+    fi
+
+    # create_write_chmod_same_fd_single_allow requires go compiler
+    if [ "$VARIANT" = create_write_chmod_same_fd_single_allow ]; then
         if ! go version ; then
             snap install go --classic
         fi
     fi
 
     tests.session prepare -u test
+    tests.cleanup defer tests.session restore -u test
     tests.session -u test exec sh -c 'mkdir -p "/home/test/integration-tests"'
+    tests.cleanup defer rm -rf /home/test/integration-tests
     snap install prompting-client
 
 restore: |
-    # create_write_chmod_single requires kernel 7.0 or later and go
-    if [ "$VARIANT" = create_write_chmod_single_allow ]; then
-        if os.query is-kernel-lt 7.0; then
-            echo "Kernel 7.0 is required for temporal caching for lifespan single" && exit 0
-        fi
-    fi
-
     snap set system experimental.apparmor-prompting=false
-    tests.session -u test exec sh -c 'rm -rf "/home/test/integration-tests"'
-    tests.session restore -u test
 
 debug: |
+    uname -a
+    if [ -f using-temporal-script ] ; then
+        echo "Used script intended for kernels with temporal cache"
+    else
+        echo "Used standard script, not script for temporal cache"
+    fi
+
     TEST_UID="$(id -u test)"
     echo "outstanding prompts:"
     snap debug api "/v2/interfaces/requests/prompts?user-id=$TEST_UID" || true
@@ -81,13 +96,6 @@ debug: |
     snap debug api "/v2/interfaces/requests/rules?user-id=$TEST_UID" || true
 
 execute: |
-    # create_write_chmod_single requires kernel 7.0 or later and go
-    if [ "$VARIANT" = create_write_chmod_single_allow ]; then
-        if os.query is-kernel-lt 7.0; then
-            echo "Kernel 7.0 is required for temporal caching for lifespan single" && exit 0
-        fi
-    fi
-
     echo "Precondition check that snapd is active"
     systemctl is-active snapd.service snapd.socket
 
