tests: add prompting integration test for FD caching with lifespan single
Signed-off-by: Oliver Calder <oliver.calder@canonical.com>

diff --git a/tests/main/apparmor-prompting-integration-tests/task.yaml b/tests/main/apparmor-prompting-integration-tests/task.yaml
--- a/tests/main/apparmor-prompting-integration-tests/task.yaml
+++ b/tests/main/apparmor-prompting-integration-tests/task.yaml
@@ -31,6 +31,7 @@ environment:
     VARIANT/create_multiple_not_actioned_by_other_pid_single_deny: create_multiple_not_actioned_by_other_pid_single_deny
     VARIANT/write_read_multiple_actioned_by_other_pid_allow_deny: write_read_multiple_actioned_by_other_pid_allow_deny
     VARIANT/write_read_multiple_actioned_by_other_pid_deny_allow: write_read_multiple_actioned_by_other_pid_deny_allow
+    VARIANT/create_write_chmod_single_allow: create_write_chmod_single_allow
 
     TIMEOUT: "30" # Define common timeout which can be modified as needed
 
@@ -46,11 +47,28 @@ skip:
       reason: Ubuntu 22.04 AppArmor parser doesn't support prompting without reexec
 
 prepare: |
+    # create_write_chmod_single requires kernel 7.0 or later and go
+    if [ "$VARIANT" = create_write_chmod_single_allow ]; then
+        if os.query is-kernel-lt 7.0; then
+            echo "Kernel 7.0 is required for temporal caching for lifespan single" && exit 0
+        fi
+        if ! go version ; then
+            snap install go --classic
+        fi
+    fi
+
     tests.session prepare -u test
     tests.session -u test exec sh -c 'mkdir -p "/home/test/integration-tests"'
     snap install prompting-client
 
 restore: |
+    # create_write_chmod_single requires kernel 7.0 or later and go
+    if [ "$VARIANT" = create_write_chmod_single_allow ]; then
+        if os.query is-kernel-lt 7.0; then
+            echo "Kernel 7.0 is required for temporal caching for lifespan single" && exit 0
+        fi
+    fi
+
     snap set system experimental.apparmor-prompting=false
     tests.session -u test exec sh -c 'rm -rf "/home/test/integration-tests"'
     tests.session restore -u test
@@ -63,6 +81,13 @@ debug: |
     snap debug api "/v2/interfaces/requests/rules?user-id=$TEST_UID" || true
 
 execute: |
+    # create_write_chmod_single requires kernel 7.0 or later and go
+    if [ "$VARIANT" = create_write_chmod_single_allow ]; then
+        if os.query is-kernel-lt 7.0; then
+            echo "Kernel 7.0 is required for temporal caching for lifespan single" && exit 0
+        fi
+    fi
+
     echo "Precondition check that snapd is active"
     systemctl is-active snapd.service snapd.socket
 
