tests: fix docker tests by using a local images (#15653)
* tests: fir docker tests by using a local registry

There is a new docker-state tool which uses images previously uploaded
to gce bucket to create local images. The tests now instead of using the
default registry are using the local one

The microk8s test is updated to use rocks.canonical.com instead of
docker.io

* Fix task order in docker-smoke

* download registry:2 from gce instead of pulling from docker.io

Also use ubuntu 24.04 in lp-1910456 test

* user curl instead of wget and remove local registry

* retry until docker is ready lo load images

* fixes to make tests work for arm and updated microk8s

* skip systems in microk8s which are not loading properly rockcraft images

* use rocks.canonical.com just when SNAPD_USE_PROXY is true

diff --git a/tests/main/docker-smoke/task.yaml b/tests/main/docker-smoke/task.yaml
--- a/tests/main/docker-smoke/task.yaml
+++ b/tests/main/docker-smoke/task.yaml
@@ -9,6 +9,24 @@ systems: [ubuntu-*]
 environment:
   # downloading docker snap occasionally triggers OOM
   SNAPD_NO_MEMORY_LIMIT: 1
+  CHANNEL: "latest/stable"
+  IMAGE_URL: https://storage.googleapis.com/snapd-spread-tests/images/docker/hello-world.tar
+
+prepare: |
+  if ! snap install --channel="$CHANNEL" docker; then
+      echo "failed to install the docker snap!"
+      exit 1
+  fi
+
+  if [ "${SNAPD_USE_PROXY:-}" = true ]; then
+    if ! command -v curl; then
+        snap install --devmode --edge test-snapd-curl
+        snap alias test-snapd-curl.curl curl
+    fi    
+    curl -sL "$IMAGE_URL" -o hello-world.tar
+    # retry until docker is ready lo load images
+    retry -n 30 --wait 1 docker load -i hello-world.tar  
+  fi
 
 debug: |
   "$TESTSTOOLS"/journal-state get-log -u snap.docker.dockerd
@@ -18,14 +36,7 @@ execute: |
     # ubuntu trusty is not supported anymore
     if os.query is-trusty; then
         exit
-    fi
-
-    CHANNEL=latest/stable
-
-    if ! snap install --channel="$CHANNEL" docker; then
-      echo "failed to install the docker snap!"
-      exit 1
-    fi
+    fi    
 
     # the retry here is because there's a race between installing the docker snap
     # and dockerd to be "ready" enough such that docker can talk to it properly
