tests: fir docker tests by using a local registry
There is a new docker-state tool which uses images previously uploaded
to gce bucket to create local images. The tests now instead of using the
default registry are using the local one

The microk8s test is updated to use rocks.canonical.com instead of
docker.io

diff --git a/tests/main/docker-smoke/task.yaml b/tests/main/docker-smoke/task.yaml
--- a/tests/main/docker-smoke/task.yaml
+++ b/tests/main/docker-smoke/task.yaml
@@ -9,23 +9,27 @@ systems: [ubuntu-*]
 environment:
   # downloading docker snap occasionally triggers OOM
   SNAPD_NO_MEMORY_LIMIT: 1
+  CHANNEL: "latest/stable"
+  IMAGE_URL: https://storage.googleapis.com/snapd-spread-tests/images/docker/hello-world.tar
 
 debug: |
   "$TESTSTOOLS"/journal-state get-log -u snap.docker.dockerd
+
+prepare: |
+  if ! snap install --channel="$CHANNEL" docker; then
+      echo "failed to install the docker snap!"
+      exit 1
+  fi
+  wget --quiet "$IMAGE_URL" -O hello-world.tar
+  "$TESTSTOOLS"/docker-state setup-local-registry
+  "$TESTSTOOLS"/docker-state add-local-image hello-world hello-world.tar
 
 execute: |
   if [ "$SPREAD_REBOOT" = 0 ]; then
     # ubuntu trusty is not supported anymore
     if os.query is-trusty; then
         exit
-    fi
-
-    CHANNEL=latest/stable
-
-    if ! snap install --channel="$CHANNEL" docker; then
-      echo "failed to install the docker snap!"
-      exit 1
-    fi
+    fi    
 
     # the retry here is because there's a race between installing the docker snap
     # and dockerd to be "ready" enough such that docker can talk to it properly
