tests: expect snapctl to fail with invalid context ID.
Signed-off-by: Kyle Fazzari <kyle@canonical.com>

diff --git a/tests/main/snapctl/task.yaml b/tests/main/snapctl/task.yaml
--- a/tests/main/snapctl/task.yaml
+++ b/tests/main/snapctl/task.yaml
@@ -55,12 +55,20 @@ restore: |
 
 execute: |
     echo "Run the hook that calls snapctl"
-    export SNAP_CONTEXT="foo" # Just enough to hit the API
-    if ! snap run --hook=apply-config snapctl-hooks; then
-        echo "Failed to run hook"
+
+    # This context is enough to hit the API, but the hook will fail since this
+    # context is obviously invalid. That failure still means we're correctly
+    # hitting the API, though, which is all we care about here.
+    export SNAP_CONTEXT="foo"
+    if output="$(snap run --hook=apply-config snapctl-hooks)""; then
+        echo "Expected the hook to fail"
         exit 1
     fi
 
+    if [[ ! "$output" =~ .*no context for ID: \"foo\".* ]]; then
+        echo "Expected failure to be due to missing context, but it was \"$output\""
+        exit 1
+    fi
 
     echo "Verify that the snapd API is only available via the snapd socket"
 
