many: finish `snap set` API. (#2013)
This involves adding support for an initial context for the hook.

Updates: #1596629

Signed-off-by: Kyle Fazzari <kyle@canonical.com>

diff --git a/tests/lib/snaps/snapctl-hooks/meta/hooks/apply-config b/tests/lib/snaps/snapctl-hooks/meta/hooks/apply-config
--- a/tests/lib/snaps/snapctl-hooks/meta/hooks/apply-config
+++ b/tests/lib/snaps/snapctl-hooks/meta/hooks/apply-config
@@ -1,37 +1,60 @@
 #!/bin/sh
 
-echo "Getting a configuration value that shouldn't be there"
-if snapctl get foo; then
-	echo "Expected getting a non-existing value to be an error"
-	exit 1
-fi
+test_nonexisting() {
+	echo "Getting a configuration value that shouldn't be there"
+	if snapctl get non-existing; then
+		echo "Expected getting a non-existing value to be an error"
+		exit 1
+	fi
+}
 
-echo "Setting a configuration value"
-if ! snapctl set foo=bar; then
-	echo "snapctl set unexpectedly failed"
-	exit 1
-fi
+test_snapctl_set_foo() {
+	echo "Setting foo"
+	if ! snapctl set foo=bar; then
+		echo "snapctl set unexpectedly failed"
+		exit 1
+	fi
+}
 
-echo "Getting that same configuration value back"
-if ! output=$(snapctl get foo); then
-	echo "Expected snapctl get to be able to retrieve value just set"
-	exit 1
-fi
+test_snapctl_get_foo() {
+	echo "Getting foo"
+	if ! output=$(snapctl get foo); then
+		echo "Expected snapctl get to be able to retrieve value just set"
+		exit 1
+	fi
 
-expected_output="bar"
-if "$output" -ne "$expected_output"; then
-	echo "Expected output to be '$expected_output', but it was '$output'"
-	exit 1
-fi
+	expected_output="bar"
+	if "$output" -ne "$expected_output"; then
+		echo "Expected output to be '$expected_output', but it was '$output'"
+		exit 1
+	fi
 
-echo "Getting configuration with full document"
-if ! output=$(snapctl get -d foo); then
-	echo "Expected snapctl get to be able to retrieve value just set"
-	exit 1
-fi
+	echo "Getting foo with full document"
+	if ! output=$(snapctl get -d foo); then
+		echo "Expected snapctl get to be able to retrieve value just set"
+		exit 1
+	fi
 
-expected_output='{\n"foo": "bar"\n}'
-if "$output" -ne "$expected_output"; then
-	echo "Expected output to be '$expected_output', but it was '$output'"
-	exit 1
-fi
+	expected_output='{\n"foo": "bar"\n}'
+	if "$output" -ne "$expected_output"; then
+		echo "Expected output to be '$expected_output', but it was '$output'"
+		exit 1
+	fi
+}
+
+command=$(snapctl get command)
+case $command in
+	'"test-nonexisting"')
+		test_nonexisting
+		;;
+	'"test-snapctl-set-foo"')
+		test_snapctl_set_foo
+		;;
+	'"test-snapctl-get-foo"')
+		test_snapctl_get_foo
+		;;
+	*)
+		echo "Invalid command: '$command'"
+		exit 1
+		;;
+esac
