tests: fix indent in tests/lib/snaps/snapctl-hooks/meta/hooks/configure

diff --git a/tests/lib/snaps/snapctl-hooks/meta/hooks/configure b/tests/lib/snaps/snapctl-hooks/meta/hooks/configure
--- a/tests/lib/snaps/snapctl-hooks/meta/hooks/configure
+++ b/tests/lib/snaps/snapctl-hooks/meta/hooks/configure
@@ -93,8 +93,8 @@ test_snapctl_foo_null() {
 test_snapctl_unset() {
 	  echo "Unsetting an option"
 	  if ! snapctl set root.key2! ; then
-	  echo "snapctl set unexpectedly failed when un-setting root.key2"
-			exit 1
+	            echo "snapctl set unexpectedly failed when un-setting root.key2"
+		    exit 1
 	  fi
 }
 
