Spread test.

diff --git a/tests/lib/snaps/snapctl-hooks/meta/hooks/configure b/tests/lib/snaps/snapctl-hooks/meta/hooks/configure
--- a/tests/lib/snaps/snapctl-hooks/meta/hooks/configure
+++ b/tests/lib/snaps/snapctl-hooks/meta/hooks/configure
@@ -16,6 +16,14 @@ test_snapctl_set_foo() {
 	fi
 }
 
+test_snapctl_set_foo_doc() {
+    echo "Setting foo document"
+    if ! snapctl set foo="{\"a\":{\"aa\":1,\"ab\":2},\"b\":3}"; then
+		    echo "snapctl set unexpectedly failed"
+		    exit 1
+    fi
+}
+
 test_snapctl_get_foo() {
 	echo "Getting foo"
 	if ! output="$(snapctl get foo)"; then
@@ -56,6 +64,9 @@ case $command in
 	"test-nonexisting")
 		test_nonexisting
 		;;
+  "test-snapctl-set-foo-doc")
+    test_snapctl_set_foo_doc
+    ;;
 	"test-snapctl-set-foo")
 		test_snapctl_set_foo
 		;;
@@ -64,7 +75,7 @@ case $command in
 		;;
 	"test-snapctl-get-foo-null")
 		  test_snapctl_get_foo_null
-		  ;;
+	 ;;
 	"test-exit-one")
 		test_exit_one
 		;;
diff --git a/tests/main/snap-get/task.yaml b/tests/main/snap-get/task.yaml
--- a/tests/main/snap-get/task.yaml
+++ b/tests/main/snap-get/task.yaml
@@ -44,6 +44,17 @@ execute: |
         exit 1
     fi
 
+    echo "Test that keys of json documents can be obtained via snap get"
+    if ! snap set snapctl-hooks command=test-snapctl-set-foo-doc; then
+        echo "snap set unexpectedly failed"
+        exit 1
+    fi
+    output=$(snap get snapctl-hooks foo 2>&1)
+    echo "$output" | MATCH "^Key:$"
+    echo "$output" | MATCH "^foo.a.aa$"
+    echo "$output" | MATCH "^foo.a.ab$"
+    echo "$output" | MATCH "^foo.b$"
+
     echo "Test that config values are not available once snap is removed"
     snap remove snapctl-hooks
     if output=$(snap get snapctl-hooks foo); then
