Spread test, fixes.

diff --git a/tests/main/interfaces-hooks/task.yaml b/tests/main/interfaces-hooks/task.yaml
--- a/tests/main/interfaces-hooks/task.yaml
+++ b/tests/main/interfaces-hooks/task.yaml
@@ -19,11 +19,17 @@ restore: |
     rm -f "$PRODUCER_DATA/connect-slot-producer-done"
     rm -f "$CONSUMER_DATA/disconnect-plug-consumer-done"
     rm -f "$PRODUCER_DATA/disconnect-slot-producer-done"
+    rm -f "$CONSUMER_DATA/unprepare-plug-consumer-done"
+    rm -f "$PRODUCER_DATA/unprepare-slot-producer-done"
     snap remove basic-iface-hooks-consumer
     snap remove basic-iface-hooks-producer
 
 execute: |
     . "$TESTSLIB/snaps.sh"
+    remove_markers() {
+        rm -f $CONSUMER_DATA/*-plug-*done
+        rm -f $PRODUCER_DATA/*-slot-*done
+    }
     check_attributes(){
         # static values should have the values defined in snap's yaml
         jq -r '.data["conns"]["basic-iface-hooks-consumer:consumer basic-iface-hooks-producer:producer"]["plug-static"]["consumer-attr-1"]' /var/lib/snapd/state.json | MATCH "consumer-value-1"
@@ -57,9 +63,36 @@ execute: |
     check_attributes
     systemctl start snapd.service snapd.socket
 
+    remove_markers
+
     # make sure disconnect hooks are executed
     snap disconnect basic-iface-hooks-consumer:consumer basic-iface-hooks-producer:producer
+    snap change --last=disconnect | MATCH "Run hook disconnect-slot-producer of snap \"basic-iface-hooks-producer"
+    snap change --last=disconnect | MATCH "Run hook disconnect-plug-consumer of snap \"basic-iface-hooks-consumer"
 
-    # producer/consumer disconnect hooks dump marker files, check if they exist to verify hooks were run
     [ -f "$CONSUMER_DATA/disconnect-plug-consumer-done" ]
     [ -f "$PRODUCER_DATA/disconnect-slot-producer-done" ]
+
+    remove_markers
+
+    # make connect hooks fail, check that undo hooks were executed
+    snap set basic-iface-hooks-consumer fail=connect
+    if snap connect basic-iface-hooks-consumer:consumer basic-iface-hooks-producer:producer ; then
+        echo "Expected snap connect to fail"
+        exit 1
+    fi
+
+    [ -f "$CONSUMER_DATA/unprepare-plug-consumer-done" ]
+    [ -f "$PRODUCER_DATA/unprepare-slot-producer-done" ]
+    [ -f "$PRODUCER_DATA/connect-slot-producer-done" ]
+    [ -f "$PRODUCER_DATA/disconnect-slot-producer-done" ]
+
+    remove_markers
+
+    # disconnect hooks should be executed on snap removal
+    snap set basic-iface-hooks-consumer fail=none
+    snap connect basic-iface-hooks-consumer:consumer basic-iface-hooks-producer:producer
+    snap remove basic-iface-hooks-consumer
+    [ -f "$PRODUCER_DATA/disconnect-slot-producer-done" ]
+    snap change --last=remove | MATCH "Run hook disconnect-slot-producer of snap \"basic-iface-hooks-producer"
+    snap change --last=remove | MATCH "Run hook disconnect-plug-consumer of snap \"basic-iface-hooks-consumer"
