fix also core20-install-mode-shutdown-via-hook test
used the code we have in nested.sh to check "cloud-init status --wait"

diff --git a/tests/nested/manual/core20-install-mode-shutdown-via-hook/task.yaml b/tests/nested/manual/core20-install-mode-shutdown-via-hook/task.yaml
--- a/tests/nested/manual/core20-install-mode-shutdown-via-hook/task.yaml
+++ b/tests/nested/manual/core20-install-mode-shutdown-via-hook/task.yaml
@@ -87,7 +87,11 @@ execute: |
     # Wait for snap seeding to be done
     remote.exec "sudo snap wait system seed.loaded"
     # Wait for cloud init to be done
-    remote.exec "cloud-init status --wait"
+    remote.exec "cloud-init status --wait" || ret=$?
+    if [ "$ret" -ne 0 ] && [ "$ret" -ne 2 ]; then
+        echo "cloud-init finished with error $ret"
+        exit 1
+    fi
 
     echo "The device is using encrypted ubuntu-data and is in run mode now"
     remote.exec test -L /dev/disk/by-label/ubuntu-data-enc
