tests: check for /snap/core16/current in core16-provided-by-core
The core16-provided-by-core test requires that /snap/core16/current
is not there. This PR ensures it is really gone and adds extra
checks for that.

diff --git a/tests/main/core16-provided-by-core/task.yaml b/tests/main/core16-provided-by-core/task.yaml
--- a/tests/main/core16-provided-by-core/task.yaml
+++ b/tests/main/core16-provided-by-core/task.yaml
@@ -6,6 +6,15 @@ execute: |
         snap install core
     fi
 
+    echo "Ensure there is no core16 installed"
+    snap remove core16
+
+    echo "Double check that no earlier test left garbage around"
+    if [ -e /snap/core16/current ] || [ test -L /snap/core16/current ]; then
+        echo "internal error: a core16 snap is installed, earlier test cleanup did not work"
+        exit 1
+    fi
+
     #shellcheck source=tests/lib/snaps.sh
     . "$TESTSLIB/snaps.sh"
     install_local test-snapd-sh-core16
