reafactor: validation and spread tests

diff --git a/tests/lib/snaps/test-snapd-success-exit-status/bin/service-exit-code b/tests/lib/snaps/test-snapd-success-exit-status/bin/service-exit-code
--- a/tests/lib/snaps/test-snapd-success-exit-status/bin/service-exit-code
+++ b/tests/lib/snaps/test-snapd-success-exit-status/bin/service-exit-code
@@ -2,11 +2,14 @@
 
 set -e
 
-trap 'echo "Exiting with 42 (SUCCESS)"; exit 42' USR1
-trap 'echo "Exiting with 250 (SUCCESS)"; exit 250' USR2
-trap 'echo "Exiting with 1 (FAILURE)"; exit 1' TRAP
+trap 'echo "Exiting with 42 (SUCCESS)"; rm "$SNAP_COMMON/ready"; exit 42' USR1
+trap 'echo "Exiting with 250 (SUCCESS)"; rm "$SNAP_COMMON/ready"; exit 250' USR2
+trap 'echo "Exiting with 1 (FAILURE)"; rm "$SNAP_COMMON/ready"; exit 1' TRAP
 
 echo "Service starting (PID: $$)..."
+
+# drop ready marker
+touch "$SNAP_COMMON/ready"
 
 while true; do
     echo "Service running..."
