i/builtin: extend polkit interface to support custom polkit rules (#15115)
* i/builtin: extend polkit interface to support custom polkit rules

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* tests: extend interfaces-polkit to test custom polkit rules installation

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! i/builtin/polkit: s/getInstallRules/parseAndValidateInstallRules

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! i/builtin: s/load/add/

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! i/builtin: fix s/read/add/ for polkit helpers

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! address review comments

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! i/builtin: add upper bound limit to rule file size

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! tests: fix polkit policy prefix mismatch

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! i/builtin: enforce plug-name prefix for polkit rule file names

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! i/builtin: remove redundant missing attr check

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* i/builtin: support polkit policies on Ubuntu 20.04 and Debian 11

Ubuntu 20.04 and Debian 11 has the polkitd executable under
/usr/lib/policykit-1/polkitd.

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! Revert "i/builtin: support polkit policies on Ubuntu 20.04 and Debian 11"

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! i/builtin: validate writable polkit policy/rule dirs for plugs

Remove restriction on the core implicit slot to have writable polkit
policy and rule dirs writable and only check that the daemon executable
exists. The writable paths checks are now run in the plug checks only
if the corresponding attribute (action-prefix or install-rules) exists.

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! i/builtin: fix polkit interface change of behavior on core

Ubunutu Core < 24 don't have writable polkit action or rules
directories, so they should not have an implicit core polkit slot.

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! tests: skip polkit rules checks for Ubuntu <= 20.04

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

* fixup! tests: skip polkit rules checks for 22.04

Jammy uses polkit version 0.105 and support for dropping
rules under /etc/polkit-1/rules.d started with 0.106.

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

---------

Signed-off-by: Zeyad Gouda <zeyad.gouda@canonical.com>

diff --git a/tests/main/interfaces-polkit/task.yaml b/tests/main/interfaces-polkit/task.yaml
--- a/tests/main/interfaces-polkit/task.yaml
+++ b/tests/main/interfaces-polkit/task.yaml
@@ -1,14 +1,21 @@
 summary: Ensure that the polkit interface works.
 
 details: |
-    The polkit interface allows snap applications to obtain limited access to
-    the policy kit service. The test installs a snap with a plug controlling
-    permissions with a specific prefix, checks that the policy file is installed
-    and that the snap can request policy operations with the same prefix as is
-    declared in the plug.
+    The polkit interface allows snap applications to (1) Obtain limited access to
+    the policy kit service (2) Install custom polkit rules. The test installs a snap
+    with a plug for each of the mentioned use cases. A plug for controlling permissions
+    with a specific prefix, checking that the policy file is installed and that the
+    snap can request policy operations with the same prefix as is declared in the
+    plug. The other is for checking that custom polkit rules are properly installed.
 
 # amazon-linux-2023: polkit not installed by default
-systems: [-ubuntu-core-*, -amazon-linux-2023-*]
+# ubuntu-core < uc24: polkit rules path is not writable 
+systems:
+    - -ubuntu-core-16-*
+    - -ubuntu-core-18-*
+    - -ubuntu-core-20-*
+    - -ubuntu-core-22-*
+    - -amazon-linux-2023-64
 
 prepare: |
     if ! tests.session has-session-systemd-and-dbus; then
@@ -33,28 +40,54 @@ execute: |
     echo "Install the test snap"
     "$TESTSTOOLS"/snaps-state install-local test-snapd-pk-service
 
-    echo "The polkit interface is disconnected by default"
-    snap connections test-snapd-pk-service | MATCH "polkit +test-snapd-pk-service:polkit +- +-"
+    # Run policy checks only on classic because /usr/share/polkit-1/actions is not writable on Ubuntu Core.
+    if ! os.query is-core; then
+        echo "Test polkit actions"
 
-    echo "The polkit policy file is not installed"
-    test ! -f /usr/share/polkit-1/actions/snap.test-snapd-pk-service.interface.polkit.foo.policy
+        echo "The polkit-action plug is disconnected by default"
+        snap connections test-snapd-pk-service | MATCH "polkit +test-snapd-pk-service:polkit-action +- +-"
 
-    echo "The interface can be connected"
-    snap connect test-snapd-pk-service:polkit
-    snap connections test-snapd-pk-service | MATCH "polkit +test-snapd-pk-service:polkit +:polkit +manual"
+        echo "The polkit policy file is not installed"
+        test ! -f /usr/share/polkit-1/actions/snap.test-snapd-pk-service.interface.polkit-action.foo.policy
 
-    echo "Snapd has installed the policy file for the service"
-    test -f /usr/share/polkit-1/actions/snap.test-snapd-pk-service.interface.polkit.foo.policy
-    echo "The contents match the file provided by the snap"
-    cmp /usr/share/polkit-1/actions/snap.test-snapd-pk-service.interface.polkit.foo.policy ./test-snapd-pk-service/meta/polkit/polkit.foo.policy
+        echo "The polkit-action plug can be connected"
+        snap connect test-snapd-pk-service:polkit-action
+        snap connections test-snapd-pk-service | MATCH "polkit +test-snapd-pk-service:polkit-action +:polkit +manual"
 
-    echo "Create a non-privileged process, and get its pid"
-    tests.session -u test exec systemd-run --user --unit test-snapd-sleep.service sh -c 'touch /home/test/sleep.stamp && exec sleep 1h'
-    retry -n 30 --wait 0.1 test -e /home/test/sleep.stamp
-    user_pid=$(tests.session -u test exec systemctl --user show --property=MainPID test-snapd-sleep.service | cut -d = -f 2)
+        echo "Snapd has installed the policy file for the service"
+        test -f /usr/share/polkit-1/actions/snap.test-snapd-pk-service.interface.polkit-action.foo.policy
+        echo "The contents match the file provided by the snap"
+        cmp /usr/share/polkit-1/actions/snap.test-snapd-pk-service.interface.polkit-action.foo.policy ./test-snapd-pk-service/meta/polkit/polkit-action.foo.policy
 
-    echo "The snap can talk to polkitd"
-    test-snapd-pk-service.check-pid "$user_pid" org.example.foo.AlwaysAllow \
-      | MATCH '^\(bba\{ss\}\) true false '
-    test-snapd-pk-service.check-pid "$user_pid" org.example.foo.AlwaysDeny \
-      | MATCH '^\(bba\{ss\}\) false false '
+        echo "Create a non-privileged process, and get its pid"
+        tests.session -u test exec systemd-run --user --unit test-snapd-sleep.service sh -c 'touch /home/test/sleep.stamp && exec sleep 1h'
+        retry -n 30 --wait 0.1 test -e /home/test/sleep.stamp
+        user_pid=$(tests.session -u test exec systemctl --user show --property=MainPID test-snapd-sleep.service | cut -d = -f 2)
+
+        echo "The snap can talk to polkitd"
+        test-snapd-pk-service.check-pid "$user_pid" org.example.foo.AlwaysAllow \
+            | MATCH '^\(bba\{ss\}\) true false '
+        test-snapd-pk-service.check-pid "$user_pid" org.example.foo.AlwaysDeny \
+            | MATCH '^\(bba\{ss\}\) false false '
+    fi
+
+    # Skip rule checks for Ubuntu <= 22.04 and Debian 11 because they don't support the
+    # /etc/polkit-1/rules.d rules directory i.e polkit version < 0.106
+    if ! os.query is-ubuntu-le 22.04 && ! os.query is-debian 11 ;then
+        echo "Test polkit rules installation"
+
+        echo "The polkit-rule plug is disconnected by default"
+        snap connections test-snapd-pk-service | MATCH "polkit +test-snapd-pk-service:polkit-rule +- +-"
+
+        echo "The polkit rule file is not installed"
+        test ! -f /etc/polkit-1/rules.d/70-snap.test-snapd-pk-service.polkit-rule.bar.rules
+
+        echo "The polkit-rule plug can be connected"
+        snap connect test-snapd-pk-service:polkit-rule
+        snap connections test-snapd-pk-service | MATCH "polkit +test-snapd-pk-service:polkit-rule +:polkit +manual"
+
+        echo "Snapd has installed the rule file for the service"
+        test -f /etc/polkit-1/rules.d/70-snap.test-snapd-pk-service.polkit-rule.bar.rules
+        echo "The contents match the file provided by the snap"
+        cmp /etc/polkit-1/rules.d/70-snap.test-snapd-pk-service.polkit-rule.bar.rules ./test-snapd-pk-service/meta/polkit/polkit-rule.bar.rules
+    fi
