Add retry until the xdg dir can be removed
It is failing trying to remove the xdg share directory.

Error:
https://paste.ubuntu.com/p/9P6jsm6b7t/

diff --git a/tests/main/interfaces-calendar-service/task.yaml b/tests/main/interfaces-calendar-service/task.yaml
--- a/tests/main/interfaces-calendar-service/task.yaml
+++ b/tests/main/interfaces-calendar-service/task.yaml
@@ -7,9 +7,10 @@ systems:
     - -ubuntu-14.04-*
 
 environment:
-    XDG_CONFIG_HOME: $(pwd)/config
-    XDG_DATA_HOME: $(pwd)/share
-    XDG_CACHE_HOME: $(pwd)/cache
+    XDG: $(pwd)/xdg
+    XDG_CONFIG_HOME: $XDG/config
+    XDG_DATA_HOME: $XDG/share
+    XDG_CACHE_HOME: $XDG/cache
 
 prepare: |
     #shellcheck source=tests/lib/pkgdb.sh
@@ -21,7 +22,14 @@ prepare: |
 restore: |
     kill "$(cat dbus-launch.pid)"
     rm -f dbus-launch.pid
-    rm -rf "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_CACHE_HOME"
+    for i in $(seq 3); do
+        if rm -rf "$XDG"; then
+            exit 0
+        fi
+        sleep 1
+    done
+    echo "Could not be deleted: $XDG"
+    exit 1
 
 execute: |
     echo "Setting up D-Bus session bus"
