tests: add debug section to pulseaudio tests
The test just failed with:

    + session-tool -u test systemctl --user start pulseaudio.service
    Job for pulseaudio.service failed because the control process exited with error code.
    See "systemctl --user status pulseaudio.service" and "journalctl --user -xe" for details.

Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>

diff --git a/tests/main/interfaces-pulseaudio/task.yaml b/tests/main/interfaces-pulseaudio/task.yaml
--- a/tests/main/interfaces-pulseaudio/task.yaml
+++ b/tests/main/interfaces-pulseaudio/task.yaml
@@ -45,11 +45,23 @@ prepare: |
     # Start pulseaudio to give it a chance to write the pulseaudio cookie file.
     # Otherwise paplay invocation will race with pulse startup, and will race
     # with cookie file being available.
-    session-tool -u test systemctl --user start pulseaudio.service
+    if not session-tool -u test systemctl --user start pulseaudio.service; then
+        echo "cannot start pulseaudio server"
+        session-tool -u test systemctl --user status pulseaudio.service
+        exit 1
+    fi
 
     # Ensure, that the cookie file is present.
     test -e ~test/.config/pulse/cookie || test -e ~test/.config/pulse/.pulse-cookie
     echo "rm -rf ~test/.config/pulse" >>defer.sh
+
+debug: |
+    echo "Files present in the test user's home directory"
+    test -d /home/test && find /home/test
+    echo "Files present in the test user's runtime directory"
+    test -d /home/user/12345 && find /run/user/12345
+    echo "Processes running as the test user"
+    ps -u test
 
 restore: |
     # Restore system to the previous state by running deferred commands in
