Test that symlink to incorrect version is re-created.

diff --git a/tests/main/snap-run-userdata-current/task.yaml b/tests/main/snap-run-userdata-current/task.yaml
--- a/tests/main/snap-run-userdata-current/task.yaml
+++ b/tests/main/snap-run-userdata-current/task.yaml
@@ -13,10 +13,8 @@ execute: |
       echo "Could not determine current version of $SNAP"
       exit 1
     fi
-    /snap/bin/test-snapd-tools.echo -n
-    id
-    find $HOME
 
+    /snap/bin/test-snapd-tools.echo -n
     UDATA_CURRENT=$(readlink $HOME/snap/test-snapd-tools/current)
     if [ "$CURRENT" != "$UDATA_CURRENT" ]; then
       echo "Invalid 'current' symlink in user-data directory, expected $CURRENT, got $UDATA_CURRENT"
@@ -28,5 +26,14 @@ execute: |
     /snap/bin/test-snapd-tools.echo -n
     if [ ! -L $HOME/snap/test-snapd-tools/current ]; then
       echo "The 'current' symlink not present in user-data directory"
+      exit 1
+    fi
+
+    echo "Test that 'current' symlink is updated if incorrect"
+    ln -fs $HOME/snap/test-snapd-tools/wrong $HOME/snap/test-snapd-tools/current
+    /snap/bin/test-snapd-tools.echo -n
+    UDATA_CURRENT=$(readlink $HOME/snap/test-snapd-tools/current)
+    if [ "$CURRENT" != "$UDATA_CURRENT" ]; then
+      echo "Invalid 'current' symlink in user-data directory, expected $CURRENT, got $UDATA_CURRENT"
       exit 1
     fi
