tests: add explicit test that apparmor generates the right snap-confine from core profile

diff --git a/tests/main/snap-confine-from-core/task.yaml b/tests/main/snap-confine-from-core/task.yaml
--- a/tests/main/snap-confine-from-core/task.yaml
+++ b/tests/main/snap-confine-from-core/task.yaml
@@ -16,6 +16,7 @@ restore: |
 execute: |
     # shellcheck source=tests/lib/journalctl.sh
     . "$TESTSLIB/journalctl.sh"
+    . "$TESTSLIB/systemd.sh"
 
     if [ "${SNAP_REEXEC:-}" = "0" ]; then
         echo "skipping test when SNAP_REEXEC is disabled"
@@ -34,5 +35,36 @@ execute: |
     get_journalctl_log | MATCH "DEBUG: restarting into"
 
     echo "Ensure snap-confine from the core snap is run"
-    # do not use "strace -f" for unknown reasons that hangs
     test-snapd-tools.echo hello
+
+
+
+
+    echo "Ensure snapd generates the right apparmor profile on restart"
+    PROFILES="$(find /etc/apparmor.d/ -maxdepth 1 -name "snap.core.*.snap-confine")"
+    if [ -z "$PROFILES" ]; then
+        echo "cannot find apparmor profiles for snap-confine from core"
+        echo "test broken"
+        ls -al /etc/apparmor.d
+        exit 1
+    fi
+
+    echo "Force system-key change"
+    systemd_stop_units snapd.service snapd.socket
+    printf '{"version":1}' > /var/lib/snapd/system-key
+    rm -f /etc/apparmor.d/snap.core.*.snap-confine
+    systemctl start snapd.service snapd.socket
+    wait_for_service snapd.service
+
+    echo "Ensure this also re-generates the snap-confine from core profile"
+    for _ in $(seq 30); do
+        if ls /etc/apparmor.d/snap.core.*.snap-confine*; then
+            break
+        fi
+    done
+    PROFILES="$(find /etc/apparmor.d/ -maxdepth 1 -name "snap.core.*.snap-confine")"
+    if [ -z "$PROFILES" ]; then
+        echo "apparmor profiles for snap-confine from core were not re-generated"
+        echo "test broken"
+        exit 1
+    fi
