t/n/c/core20-fault-inject-on-refresh: do not fail if 2 reboots are not detected
Because we do not count reboots correctly, if we did not see the
second reboot, we should not fail.

diff --git a/tests/nested/core/core20-fault-inject-on-refresh/task.yaml b/tests/nested/core/core20-fault-inject-on-refresh/task.yaml
--- a/tests/nested/core/core20-fault-inject-on-refresh/task.yaml
+++ b/tests/nested/core/core20-fault-inject-on-refresh/task.yaml
@@ -126,7 +126,11 @@ execute: |
     fi
 
     if [ "$SECOND_REBOOT" = true ]; then
-        remote.wait-for reboot "$boot_id"
+        # we might not count the first reboot correctly, so we should
+        # not fail if we do not think we have rebooted twice.
+        # FIXME: it is slow to wait for timeout, we should count boot
+        # another way.
+        remote.wait-for reboot "$boot_id" || true
     fi
 
     echo "And snap refresh is completed"
