tests/lib/tools/tests.invariant: look for unexpected snap cgroups (#15145)
* tests/lib/tools/tests.invariant: look for unexpected snap cgroups

Snap cgroups should be cleaned up as a result of removing the snaps
during restore.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/lib/tools/tests.invariant: skip snap.mount

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests: remove test snaps and quotas

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/lib/tools/cleanup-state: remove freezer and device cgroups in restore

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* cmd, packaging: systemctl kill remaining processes during removal

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/services-stop-mode-sigkill: move testing os sigterm stop-modes into separate snap

Split out testing of sigterm{,-all} stop modes into a separate snap. The
sigterm stop mode has a tendency to leak processes, which is a direct
effect of the requested KillMode=process and so requires additional
cleanup. However, the original snap test-snapd-service is used in a
number of tests, so in order to avoid additional changes for cleanup
needing to be added to each of those tests, the patchs splits out
relevant parts of the original snap into a new one which is used only in
a specific test targeting the stop-mode feature.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main: remove snaps with user services

Make sure to remove snaps with user services, as those may have been
started in user sessions that are not directly related to the tests and
removal gives us a chance to stop them.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/snap-mgmt: add a workaround for stopping user services

User services cannot be stopped during purge, so work around that by
stopping the processes manually.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/snap-quota: clean up leaking systemd slices

On Ubuntu 18.04 and 20.04, despite removing the quota groups and snaps,
systemd slices with resource configuration were still leaking from the
tests. Clean them up manually.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/services-stop-mode-sigkill: fix sunchronization between test and snap service

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/lib/tools/cleanup-state: clean up leftover user services

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/snap-mgmt: workaround kernel compatibility

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/lib/tools/tests.invariant: skip socket units, leave TODO

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/postrm-purge: snap user service slices do not necessarily exist in all setups

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main: cleanup cgroups on old Ubuntu releases in lxd/docker/microk8s tests

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests: cleanup cgroups on 16.04 and 18.04

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/postrm-purge: drop incorrect check

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/lib/tools/cleanup-state: fix indentation

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/canonical-livepatch: cleanup remaining cgroups

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

---------

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

diff --git a/cmd/snap-mgmt/snap-mgmt.sh.in b/cmd/snap-mgmt/snap-mgmt.sh.in
--- a/cmd/snap-mgmt/snap-mgmt.sh.in
+++ b/cmd/snap-mgmt/snap-mgmt.sh.in
@@ -35,10 +35,17 @@ systemctl_stop() {
         echo "Waiting until unit $unit is stopped [attempt $i]"
         if ! systemctl is-active -q "$unit"; then
             echo "$unit is stopped."
-            return
+            break
         fi
         sleep .5
     done
+
+    if echo "$unit" | grep -q '.*\.service' ; then
+        # snap services can request KillMode=process, which would result in only
+        # the main process getting stopped, however during purge we are doing a
+        # full cleanup
+        systemctl kill -q "$unit" || true
+    fi
 }
 
 is_component_mount_unit() {
