cmd/snap-mgmt: split stopping of services and mount units, cleanup mount ns
Split stopping of snap services and snap mount units. Make sure to call
snap-discard-ns for removed snaps to clean up the mount namespace that may
contain bind mounted objects from the rootfs. Make sure that units from services
are stopped before respective mount units.

Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>

diff --git a/cmd/snap-mgmt/snap-mgmt.sh.in b/cmd/snap-mgmt/snap-mgmt.sh.in
--- a/cmd/snap-mgmt/snap-mgmt.sh.in
+++ b/cmd/snap-mgmt/snap-mgmt.sh.in
@@ -32,6 +32,13 @@ systemctl_stop() {
     fi
 }
 
+is_snap_unit() {
+    local unit
+    unit="$1"
+    # ensure its really a snap mount unit or systemd unit
+    grep -q 'What=/var/lib/snapd/snaps/' "/etc/systemd/system/$unit" || grep -q 'X-Snappy=yes' "/etc/systemd/system/$unit"
+}
+
 purge() {
     # shellcheck disable=SC1091
     distribution=$(. /etc/os-release; echo "${ID}-${VERSION_ID}")
@@ -52,64 +59,15 @@ purge() {
     mounts=$(echo "$units" | grep "^${SNAP_UNIT_PREFIX}[-.].*\\.mount" | cut -f1 -d ' ')
     # services from snaps
     services=$(echo "$units" | grep '^snap\..*\.service' | cut -f1 -d ' ')
-    for unit in $services $mounts; do
+    for unit in $services; do
         # ensure its really a snap mount unit or systemd unit
-        if ! grep -q 'What=/var/lib/snapd/snaps/' "/etc/systemd/system/$unit" && ! grep -q 'X-Snappy=yes' "/etc/systemd/system/$unit"; then
+        if ! is_snap_unit "$unit" ; then
             echo "Skipping non-snapd systemd unit $unit"
             continue
         fi
 
         echo "Stopping $unit"
         systemctl_stop "$unit"
-
-        if echo "$unit" | grep -q '.*\.mount' ; then
-            # Transform ${SNAP_MOUNT_DIR}/core/3440 -> core/3440 removing any
-            # extra / preceding snap name, eg:
-            #  /var/lib/snapd/snap/core/3440  -> core/3440
-            #  /snap/core/3440                -> core/3440
-            #  /snap/core//3440               -> core/3440
-            # NOTE: we could have used `systemctl show $unit -p Where --value`
-            # but systemd 204 shipped with Ubuntu 14.04 does not support this
-            snap_rev=$(systemctl show "$unit" -p Where | sed -e 's#Where=##' -e "s#$SNAP_MOUNT_DIR##" -e 's#^/*##')
-            snap=$(echo "$snap_rev" |cut -f1 -d/)
-            rev=$(echo "$snap_rev" |cut -f2 -d/)
-            if [ -n "$snap" ]; then
-                echo "Removing snap $snap"
-                # aliases
-                if [ -d "${SNAP_MOUNT_DIR}/bin" ]; then
-                    find "${SNAP_MOUNT_DIR}/bin" -maxdepth 1 -lname "$snap" -delete
-                    find "${SNAP_MOUNT_DIR}/bin" -maxdepth 1 -lname "$snap.*" -delete
-                fi
-                # generated binaries
-                rm -f "${SNAP_MOUNT_DIR}/bin/$snap"
-                rm -f "${SNAP_MOUNT_DIR}/bin/$snap".*
-                # snap mount dir
-                umount -l "${SNAP_MOUNT_DIR}/$snap/$rev" 2> /dev/null || true
-                rm -rf "${SNAP_MOUNT_DIR:?}/$snap/$rev"
-                rm -f "${SNAP_MOUNT_DIR}/$snap/current"
-                # snap data dir
-                rm -rf "/var/snap/$snap/$rev"
-                rm -rf "/var/snap/$snap/common"
-                rm -f "/var/snap/$snap/current"
-                # opportunistic remove (may fail if there are still revisions left)
-                for d in "${SNAP_MOUNT_DIR}/$snap" "/var/snap/$snap"; do
-                    if [ -d "$d" ]; then
-                        rmdir --ignore-fail-on-non-empty "$d"
-                    fi
-                done
-                # udev rules
-                find /etc/udev/rules.d -name "*-snap.${snap}.rules" -execdir rm -f "{}" \;
-                # dbus policy files
-                if [ -d /etc/dbus-1/system.d ]; then
-                    find /etc/dbus-1/system.d -name "snap.${snap}.*.conf" -execdir rm -f "{}" \;
-                fi
-                # timer files
-                find /etc/systemd/system -name "snap.${snap}.*.timer" | while read -r f; do
-                    systemctl_stop "$(basename "$f")"
-                    rm -f "$f"
-                done
-            fi
-        fi
 
         echo "Removing $unit"
         rm -f "/etc/systemd/system/$unit"
@@ -121,6 +79,8 @@ purge() {
     if [ -d /run/snapd/ns ]; then
         if [ "$(find /run/snapd/ns/ -name "*.mnt" | wc -l)" -gt 0 ]; then
             for mnt in /run/snapd/ns/*.mnt; do
+                name=$(echo "$mnt" | sed -e 's/snap\.//' -e 's/\.mnt$//')
+                @libexecdir@/snap-discard-ns "$name" || true
                 umount -l "$mnt" || true
                 rm -f "$mnt"
             done
@@ -132,6 +92,68 @@ purge() {
         fi
         umount -l /run/snapd/ns/ || true
     fi
+
+    for unit in $mounts; do
+        # ensure its really a snap mount unit or systemd unit
+        if ! is_snap_unit "$unit" ; then
+            echo "Skipping non-snapd systemd unit $unit"
+            continue
+        fi
+
+        echo "Stopping $unit"
+        systemctl_stop "$unit"
+
+        # Transform ${SNAP_MOUNT_DIR}/core/3440 -> core/3440 removing any
+        # extra / preceding snap name, eg:
+        #  /var/lib/snapd/snap/core/3440  -> core/3440
+        #  /snap/core/3440                -> core/3440
+        #  /snap/core//3440               -> core/3440
+        # NOTE: we could have used `systemctl show $unit -p Where --value`
+        # but systemd 204 shipped with Ubuntu 14.04 does not support this
+        snap_rev=$(systemctl show "$unit" -p Where | sed -e 's#Where=##' -e "s#$SNAP_MOUNT_DIR##" -e 's#^/*##')
+        snap=$(echo "$snap_rev" |cut -f1 -d/)
+        rev=$(echo "$snap_rev" |cut -f2 -d/)
+        if [ -n "$snap" ]; then
+            echo "Removing snap $snap"
+            # aliases
+            if [ -d "${SNAP_MOUNT_DIR}/bin" ]; then
+                find "${SNAP_MOUNT_DIR}/bin" -maxdepth 1 -lname "$snap" -delete
+                find "${SNAP_MOUNT_DIR}/bin" -maxdepth 1 -lname "$snap.*" -delete
+            fi
+            # generated binaries
+            rm -f "${SNAP_MOUNT_DIR}/bin/$snap"
+            rm -f "${SNAP_MOUNT_DIR}/bin/$snap".*
+            # snap mount dir
+            umount -l "${SNAP_MOUNT_DIR}/$snap/$rev" 2> /dev/null || true
+            rm -rf "${SNAP_MOUNT_DIR:?}/$snap/$rev"
+            rm -f "${SNAP_MOUNT_DIR}/$snap/current"
+            # snap data dir
+            rm -rf "/var/snap/$snap/$rev"
+            rm -rf "/var/snap/$snap/common"
+            rm -f "/var/snap/$snap/current"
+            # opportunistic remove (may fail if there are still revisions left)
+            for d in "${SNAP_MOUNT_DIR}/$snap" "/var/snap/$snap"; do
+                if [ -d "$d" ]; then
+                    rmdir --ignore-fail-on-non-empty "$d"
+                fi
+            done
+            # udev rules
+            find /etc/udev/rules.d -name "*-snap.${snap}.rules" -execdir rm -f "{}" \;
+            # dbus policy files
+            if [ -d /etc/dbus-1/system.d ]; then
+                find /etc/dbus-1/system.d -name "snap.${snap}.*.conf" -execdir rm -f "{}" \;
+            fi
+            # timer files
+            find /etc/systemd/system -name "snap.${snap}.*.timer" | while read -r f; do
+                systemctl_stop "$(basename "$f")"
+                rm -f "$f"
+            done
+        fi
+
+        echo "Removing $unit"
+        rm -f "/etc/systemd/system/$unit"
+        rm -f "/etc/systemd/system/multi-user.target.wants/$unit"
+    done
 
     echo "Removing downloaded snaps"
     rm -rf /var/lib/snapd/snaps/*
