snap-{seccomp,confine}: rework seccomp denylist
When a denylist was introduced in PR#12849 we reached the limits
of the API of libseccomp and some things are now hard to reason
about [1]. This is mostly because what we try to do does not
match the libseccomp API very well and a slightly different
approach is probably more aligned with it's design (see also
this libseccomp issue [2] that is related to our issue).

So this commit changes the approach and instead of trying to use
a single filter the work is split into two filters:
1. explicit allow list
2. explicit deny list

and then load both filters into the kernel. The way the kernel
works is that it selects the most restrictive action.

So in the case of PR#12849:
```
~ioctl - TIOCSTI
~ioctl - TIOCLINUX
ioctl
```
For `ioctl(TIOCLINUX)` the first allow filter would pass `ioctl`
but the second deny filter would correctly deny the TIOCLINUX.

[1] https://github.com/snapcore/snapd/pull/12849#discussion_r1206855700
[2] https://github.com/seccomp/libseccomp/issues/44

diff --git a/tests/main/snap-seccomp/task.yaml b/tests/main/snap-seccomp/task.yaml
--- a/tests/main/snap-seccomp/task.yaml
+++ b/tests/main/snap-seccomp/task.yaml
@@ -1,8 +1,6 @@
 summary: Ensure that the snap-seccomp bpf handling works
 
-# FIXME: once $(snap debug confinment) can be used (in 2.27+) remove
-#        the systems line
-systems: [ubuntu-16*, ubuntu-18*]
+systems: [ubuntu-*]
 
 # Start early as it takes a long time.
 priority: 100
@@ -25,7 +23,7 @@ execute: |
 
     # from the old test_complain
     echo "Test that the @complain keyword works"
-    rm -f "${PROFILE}.bin"
+    rm -f "${PROFILE}.bin"*
     cat >"${PROFILE}.src" <<EOF
     # some comment
     @complain
@@ -35,7 +33,7 @@ execute: |
     test-snapd-sh.sh -c 'echo hello' | MATCH hello
 
     # from the old test_complain_missed
-    rm -f "${PROFILE}.bin"
+    rm -f "${PROFILE}.bin"*
     cat >"${PROFILE}.src" <<EOF
     # super strict filter
     @complai
@@ -53,7 +51,7 @@ execute: |
     
     # from the old test_unrestricted
     echo "Test that the @unrestricted keyword works"
-    rm -f "${PROFILE}.bin"
+    rm -f "${PROFILE}.bin"*
     cat >"${PROFILE}.src" <<EOF
     # some comment
     @unrestricted
@@ -63,7 +61,7 @@ execute: |
     test-snapd-sh.sh -c 'echo hello' | MATCH hello
 
     # from the old test_unrestricted_missed
-    rm -f "${PROFILE}.bin"
+    rm -f "${PROFILE}.bin"*
     cat >"${PROFILE}.src" <<EOF
     # super strict filter
     @unrestricte
@@ -80,7 +78,7 @@ execute: |
     fi
 
     # from the old test_noprofile
-    rm -f "${PROFILE}.bin"
+    rm -f "${PROFILE}.bin"*
     echo "Ensure the code cannot not run due to missing filter"
     if SNAP_CONFINE_MAX_PROFILE_WAIT=3 test-snapd-sh.sh -c 'echo hello'; then
         echo "filtering broken: program should have failed to run"
@@ -88,31 +86,35 @@ execute: |
     fi
 
     echo "Break snapd.test-snapd-sh.bin to ensure (kernel) validation works"
-    dd if=/dev/urandom of="${PROFILE}.bin" count=1 bs=1024
-    if output=$(test-snapd-sh.sh -c 'echo hello' 2>&1 ); then
-        echo "test-snapd-sh.sh should fail with invalid seccomp profile"
-        exit 1
-    fi
+    for ext in allow deny; do
+        dd if=/dev/urandom of="${PROFILE}.bin.$ext" count=1 bs=1024
+        if output=$(test-snapd-sh.sh -c 'echo hello' 2>&1 ); then
+            echo "test-snapd-sh.sh should fail with invalid seccomp profile"
+            exit 1
+        fi
+    done
     echo "$output" | MATCH "cannot apply seccomp profile: Invalid argument"
 
     echo "Add huge snapd.test-snapd-sh.bin to ensure size limit works"
-    dd if=/dev/zero of="${PROFILE}.bin" count=50 bs=1M
-    if output=$(test-snapd-sh.sh -c 'echo hello' 2>&1 ); then
-        echo "test-snapd-sh.sh should fail with big seccomp profile"
-        exit 1
-    fi
+    for ext in allow deny; do
+        dd if=/dev/zero of="${PROFILE}.bin.$ext" count=50 bs=1M
+        if output=$(test-snapd-sh.sh -c 'echo hello' 2>&1 ); then
+            echo "test-snapd-sh.sh should fail with big seccomp profile"
+            exit 1
+        fi
+    done
     echo "$output" | MATCH "cannot fit .* to memory buffer"
 
     
     echo "Ensure the code cannot not run with a missing .bin profile"
-    rm -f "${PROFILE}.bin"
+    rm -f "${PROFILE}.bin"*
     if test-snapd-sh.sh -c 'echo hello'; then
         echo "filtering broken: program should have failed to run"
         exit 1
     fi
 
     echo "Ensure the code cannot not run with an empty seccomp profile"
-    rm -f "${PROFILE}.bin"
+    rm -f "${PROFILE}.bin"*
     echo "" > "${PROFILE}.src"
     $SNAP_SECCOMP compile "${PROFILE}.src" "${PROFILE}.bin"
     if test-snapd-sh.sh -c 'echo hello'; then
@@ -121,7 +123,7 @@ execute: |
     fi
 
     echo "Ensure snap-confine waits for security profiles to appear"
-    rm -f "${PROFILE}.bin"
+    rm -f "${PROFILE}.bin"*
     cat >"${PROFILE}.src" <<EOF
     @unrestricted
     EOF
