rewrite error checks

diff --git a/tests/main/install-errors/task.yaml b/tests/main/install-errors/task.yaml
--- a/tests/main/install-errors/task.yaml
+++ b/tests/main/install-errors/task.yaml
@@ -19,19 +19,18 @@ restore: |
 
 execute: |
   echo "Install unexisting snap prints error"
-  expected="(?s)error: cannot perform the following tasks:\n\
-  - Download snap \"unexisting.canonical\" from channel \"stable\" \\(snap not found\\)\n"
-  actual=$(snap install unexisting.canonical 2>&1) || EXPECTED_FAILURE="unexisting"
-  [ "$EXPECTED_FAILURE" = "unexisting" ]
-  echo "$actual" | grep -Pzq "$expected"
+  if snap install unexisting.canonical; then
+    echo "Installing unexisting snap should fail"
+    exit 1
+  fi
 
   echo "============================================"
 
   echo "Install without snap name shows error"
-  expected="(?s)error: the required argument \`<snap>\` was not provided\n"
-  actual=$(snap install 2>&1) || EXPECTED_FAILURE="nosnap"
-  [ "$EXPECTED_FAILURE" = "nosnap" ]
-  echo "$actual" | grep -Pzq "$expected"
+  if snap install; then
+    echo "Installing without snap name should fail"
+    exit 1
+  fi
 
   echo "============================================"
 
@@ -39,22 +38,22 @@ execute: |
   expected="snap login --help"
   actual=$(sudo -i -u test /bin/sh -c "snap install hello-world 2>&1") || EXPECTED_FAILURE="unauthenticated"
   [ "$EXPECTED_FAILURE" = "unauthenticated" ]
-  echo "$actual" | grep -Pzq "$expected"
+  echo "$actual" | grep -q "$expected"
 
   echo "============================================"
 
-  echo "When a failing command from a snap is called"
-  basic-binaries.fail || EXPECTED_FAILURE="command-failed"
-
-  echo "Then it must fail"
-  [ "$EXPECTED_FAILURE" = "command-failed" ]
+  echo "Calñling a failing command from a snap should fail"
+  if basic-binaries.fail; then
+    echo "Failing snap commands should keep failing after installed"
+    exit 1
+  fi
 
   echo "============================================"
 
-  echo "When we try to install a snap already installed from the store"
-  snap install $STORE_SNAP_NAME || EXPECTED_FAILURE="install-failed"
-
-  echo "Then it must fail"
-  [ "$EXPECTED_FAILURE" = "install-failed" ]
+  echo "Install a snap already installed fails"
+  if snap install $STORE_SNAP_NAME; then
+    echo "Trying to install an already installed snap should fail"
+    exit 1
+  fi
 
   echo "============================================"
