do not allow to install ubuntu-core anymore
There is no need to install ubuntu-core anymore with current snapd.
People with existing installs will auto-transition to core on the
next refresh.

LP: #1689332

diff --git a/tests/main/install-errors/task.yaml b/tests/main/install-errors/task.yaml
--- a/tests/main/install-errors/task.yaml
+++ b/tests/main/install-errors/task.yaml
@@ -52,3 +52,12 @@ execute: |
     echo "but does "exit 0" (LP: #1622782)"
     snap install $SNAP_NAME 2> stderr.out
     cat stderr.out | MATCH "snap \"$SNAP_NAME\" is already installed"
+
+    echo "============================================"
+
+    echo "Install ubuntu-core"
+    if snap install ubuntu-core 2> stderr.out; then
+        echo "Installing ubuntu-core should fail"
+        exit 1
+    fi
+    cat stderr.out | MATCH "cannot install \"ubuntu-core\", please use \"core\" instead"
