snapstate: do not allow classic mode for strict snaps
Right now it is possible to install a strictly confined snap as in
classic confinement mode with:
```
snap install --classic test-snapd-tools
```
This should not work.

diff --git a/tests/main/install-errors/task.yaml b/tests/main/install-errors/task.yaml
--- a/tests/main/install-errors/task.yaml
+++ b/tests/main/install-errors/task.yaml
@@ -76,3 +76,10 @@ execute: |
         exit 1
     fi
     MATCH 'characters that look like dashes but are not' < stderr.out
+
+    echo "Installing a strict snap in classic mode does not work"
+    if snap install --classic test-snapd-tools 2>stderr.out; then
+        echo "snap install ––classic test-snapd-tools should have failed but did not"
+        exit 1
+    fi
+    MATCH 'classic confinment requested for a non classic confined snap' < stderr.out
