i/builtin: allow timeserver-control to manage per-link ntp settings via systemd-networkd

diff --git a/tests/main/interfaces-timeserver-control/task.yaml b/tests/main/interfaces-timeserver-control/task.yaml
--- a/tests/main/interfaces-timeserver-control/task.yaml
+++ b/tests/main/interfaces-timeserver-control/task.yaml
@@ -81,6 +81,16 @@ execute: |
         exit 1
     fi
 
+    if systemctl list-unit-files | grep systemd-networkd | awk '{print $2}' | MATCH "enabled"; then
+        echo "Check that subcommands ntp-servers and revert work"
+        iface="$(find /sys/class/net -maxdepth 1 ! -name lo ! -path "/sys/class/net" | head -n1 | xargs basename)"
+        test-snapd-timedate-control-consumer.timedatectl-timeserver ntp-servers "${iface}" 127.0.0.1
+        test-snapd-timedate-control-consumer.timedatectl-timeserver revert "${iface}"
+    elif os.query is-core-ge 20; then
+        echo "Error: insufficient test coverage of timedatectl per-link NTP commands"
+        exit 1
+    fi
+
     if [ "$(snap debug confinement)" = partial ] ; then
         exit 0
     fi
