tests: merge mnt tests into removable-media
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>

diff --git a/tests/main/interfaces-removable-media/task.yaml b/tests/main/interfaces-removable-media/task.yaml
--- a/tests/main/interfaces-removable-media/task.yaml
+++ b/tests/main/interfaces-removable-media/task.yaml
@@ -21,6 +21,10 @@ prepare: |
     mkdir -p /run/media/testdir
     touch /run/media/testdir/testfile
 
+    echo "Mount a filesystem in /tmp/testing and put some data there"
+    mkdir -p /mnt/testing/
+    mount -t tmpfs none /mnt/testing
+    echo canary > /mnt/testing/data
 
 restore: |
     rm -f call.error
@@ -34,6 +38,9 @@ restore: |
     if [ -f /run/media/fake ]; then
         rm -rf /run/media/
     fi
+
+    umount /mnt/testing
+    rmdir /mnt/testing || true # in case the user had /mnt/testing
 
 execute: |
     echo "The interface is not connected by default"
@@ -54,8 +61,18 @@ execute: |
     test-snapd-removable-media.sh -c "ls /run/media/testdir"
     test-snapd-removable-media.sh -c "echo test >> /run/media/testdir/testfile"
 
+    echo "And the snap has read-write access to /mnt/testing/data"
+    test-snapd-removable-media.sh -c 'cat /mnt/testing/data' | MATCH canary
+    test-snapd-removable-media.sh -c 'echo modified > /mnt/testing/data'
+    MATCH modified < /mnt/testing/data
+
     if [ "$(snap debug confinement)" = partial ]; then
         exit 0
+    fi
+
+    echo "The snap cannot create new things in /mnt"
+    if test-snapd-removable-media.sh -c 'echo foo > /mnt/bad'; then
+        echo "/mnt/bad should never be writable" && exit 1
     fi
 
     echo "When the plug is disconnected"
@@ -67,3 +84,8 @@ execute: |
         exit 1
     fi
     MATCH "Permission denied" < call.error
+
+    echo "Then /mnt/testing/data is no longer readable"
+    if test-snapd-removable-media.sh -c 'cat /mnt/testing/data'; then
+        echo "/mnt/testing/data should no longer be readable" && exit 1
+    fi
