automatically restart all-snap devices after os/kernel updates

diff --git a/tests/main/ubuntu-core-upgrade-core/task.yaml b/tests/main/ubuntu-core-upgrade-core/task.yaml
--- a/tests/main/ubuntu-core-upgrade-core/task.yaml
+++ b/tests/main/ubuntu-core-upgrade-core/task.yaml
@@ -26,6 +26,19 @@ execute: |
         grub-editenv list | grep "snap_try_core=ubuntu-core_$(cat nextBoot).snap"
         grub-editenv list | grep 'snap_mode=try'
 
+        echo "Ensure the device is scheduled for auto-reboot"
+        output=$(dbus-send --print-reply \
+            --type=method_call \
+            --system \
+            --dest=org.freedesktop.login1 \
+            /org/freedesktop/login1 \
+            org.freedesktop.DBus.Properties.Get \
+            string:org.freedesktop.login1.Manager string:ScheduledShutdown)
+        if ! echo $output|grep 'string "reboot"'; then
+            echo "Failed to detect scheduled reboot in logind output:"
+            echo "$output"
+            exit 1
+        fi
         REBOOT
     fi
 
