Remove PWD use and normalize interfaces tests

diff --git a/tests/main/interfaces-avahi-observe/task.yaml b/tests/main/interfaces-avahi-observe/task.yaml
--- a/tests/main/interfaces-avahi-observe/task.yaml
+++ b/tests/main/interfaces-avahi-observe/task.yaml
@@ -26,18 +26,20 @@ execute: |
     echo "Then the plug is disconnected by default"
     snap interfaces -i avahi-observe | MATCH '^\- +generic-consumer:avahi-observe'
 
-    if [ "$(snap debug confinement)" = strict ] ; then
-        echo "And the snap is not able to access avahi provided info"
-        if avahi_dbus_call 2>avahi.error; then
-            echo "Expected error with disconnected plug didn't happen"
-            exit 1
-        fi
-        MATCH "org.freedesktop.DBus.Error.AccessDenied" < avahi.error
-    fi
-
     echo "When the plug is connected"
     snap connect generic-consumer:avahi-observe
 
     echo "Then the snap is able to access avahi provided info"
     hostname=$(hostname)
     avahi_dbus_call | MATCH "$hostname"
+
+    if [ "$(snap debug confinement)" = partial ] ; then
+        exit 0
+    fi
+
+    echo "And the snap is not able to access avahi provided info"
+    if avahi_dbus_call 2> avahi.error; then
+        echo "Expected error with disconnected plug didn't happen"
+        exit 1
+    fi
+    MATCH "org.freedesktop.DBus.Error.AccessDenied" < avahi.error
