actual implementation; old test removed

diff --git a/tests/main/op-install-failed-undone/task.yaml b/tests/main/op-install-failed-undone/task.yaml
--- a/tests/main/op-install-failed-undone/task.yaml
+++ b/tests/main/op-install-failed-undone/task.yaml
@@ -1,20 +1,50 @@
 summary: Check that all tasks of a failed installtion are undone
 
+restore: |
+  rm -rf /snap/test-snapd-tools/current/foo
+
 execute: |
+  check_empty_glob(){
+    local base_path=$1
+    local glob=$2
+    [ $(find $base_path -maxdepth 1 -name "$glob" | wc -l) -eq 0 ]
+  }
+
   echo "Given we make a snap uninstallable"
+  mkdir -p /snap/test-snapd-tools/current/foo
 
   echo "And we try to install it"
+  if snap install test-snapd-tools; then
+    echo "A snap shouldn't be installable if its mount point is busy"
+    exit 1
+  fi
 
-  echo "Then it should't be installed"
+  echo "Then the snap isn't installed"
+  ! snap list | grep -q test-snapd-tools
 
-  echo "And the installation task should be reported as an error"
-
-  echo "And the installation subtasks up to the error should be reported as undone"
+  echo "And the installation task is reported as an error"
+  task_id=$(perl -ne 'print $1 if /(\d+) +Error.*?Install \"test-snapd-tools\" snap/')
+  if [ -z $task_id ]; then
+    echo "Installation task should be reported as error"
+    exit 1
+  fi
 
   echo "And the Download subtask is actually undone"
+  snap change $task_id | grep -q "Undone +.*?Download snap 'test-snapd-tools'"
 
-  echo "And the Mount msubtask is actually undone"
+  echo "And the Mount subtask is actually undone"
+  snap change $task_id | grep -q "Undone +.*?Mount snap 'test-snapd-tools'"
+  check_empty_glob /snap/test-snapd-tools [0-9]+
+  check_empty_glob /var/lib/snapd/snaps test-snapd-tools_[0-9]+.snap
 
   echo "And the Data Copy subtask is actually undone"
+  snap change $task_id | grep -q "Undone +.*?Copy snap 'test-snapd-tools' data"
+  check_empty_glob $HOME/snap/test-snapd-tools [0-9]+
+  check_empty_glob /var/snap/test-snapd-tools [0-9]+
 
   echo "And the Security Profiles Setup subtask is actually undone"
+  snap change $task_id | grep -q "Undone +.*?Setup snap 'test-snapd-tools' security profiles"
+  check_empty_glob /var/lib/snapd/apparmor/profiles snap.test-snapd-tools.*
+  check_empty_glob /var/lib/snapd/seccomp/profiles snap.test-snapd-tools.*
+  check_empty_glob /etc/dbus-1/system.d snap.test-snapd-tools.*.conf
+  check_empty_glob /etc/udev/rules.d 70-snap.test-snapd-tools.*.rules
