address review comments (thanks gustavo)

diff --git a/tests/main/interfaces-browser-support/task.yaml b/tests/main/interfaces-browser-support/task.yaml
--- a/tests/main/interfaces-browser-support/task.yaml
+++ b/tests/main/interfaces-browser-support/task.yaml
@@ -4,29 +4,31 @@ environment:
     ALLOW_SANDBOX/allow: true
     ALLOW_SANDBOX/disallow: false
     OWNED_FILES: "/var/tmp/etilqs_test"
-    READABLE_FILES: "/run/udev/data/+platform:test
-    /etc/opt/chrome/test"
-    READABLE_WITH_SANDBOX_FILES: "/run/udev/data/c1:1-test
-    /run/udev/data/c10:1-test
-    /run/udev/data/c13:1-test
-    /run/udev/data/c180:1-test
-    /run/udev/data/c4:1-test
-    /run/udev/data/c5:1-test
-    /run/udev/data/c7:1-test
-    /run/udev/data/+hid:test
-    /run/udev/data/+input:input1-test
-    /run/udev/data/c29:1-test
-    /run/udev/data/+backlight:test
-    /run/udev/data/+leds:test
-    /run/udev/data/c116:1-test
-    /run/udev/data/+sound:card1-test
-    /run/udev/data/c108:1-test
-    /run/udev/data/c189:1-test
-    /run/udev/data/c89:1-test
-    /run/udev/data/c81:1-test
-    /run/udev/data/+acpi:test
-    /run/udev/data/+hwmon:hwmon1-test
-    /run/udev/data/+i2c:test"
+    READABLE_FILES:
+        /run/udev/data/+platform:test
+        /etc/opt/chrome/test
+    READABLE_WITH_SANDBOX_FILES:
+        /run/udev/data/c1:1-test
+        /run/udev/data/c10:1-test
+        /run/udev/data/c13:1-test
+        /run/udev/data/c180:1-test
+        /run/udev/data/c4:1-test
+        /run/udev/data/c5:1-test
+        /run/udev/data/c7:1-test
+        /run/udev/data/+hid:test
+        /run/udev/data/+input:input1-test
+        /run/udev/data/c29:1-test
+        /run/udev/data/+backlight:test
+        /run/udev/data/+leds:test
+        /run/udev/data/c116:1-test
+        /run/udev/data/+sound:card1-test
+        /run/udev/data/c108:1-test
+        /run/udev/data/c189:1-test
+        /run/udev/data/c89:1-test
+        /run/udev/data/c81:1-test
+        /run/udev/data/+acpi:test
+        /run/udev/data/+hwmon:hwmon1-test
+        /run/udev/data/+i2c:test
 
 prepare: |
     echo "Given a snap declaring a plug on browser-support with allow-sandbox set to $ALLOW_SANDBOX is installed"
@@ -83,19 +85,33 @@ execute: |
         su -l -c "$SNAPMOUNTDIR/bin/browser-support-consumer.cmd cat $readable_file" test | MATCH test
     done
 
+    for readable_file in $READABLE_WITH_SANDBOX_FILES; do
+        parent_dir=$(dirname $readable_file)
+        if [ ! -d $parent_dir ]; then
+            mkdir -p $parent_dir
+            echo "$parent_dir" >> created_dirs
+        fi
+        echo "test" > "$readable_file"
+    done
+
     if [ "$ALLOW_SANDBOX" = "true" ]; then
         for readable_file in $READABLE_WITH_SANDBOX_FILES; do
-            parent_dir=$(dirname $readable_file)
-            if [ ! -d $parent_dir ]; then
-                mkdir -p $parent_dir
-                echo "$parent_dir" >> created_dirs
-            fi
-            echo "test" > "$readable_file"
             su -l -c "$SNAPMOUNTDIR/bin/browser-support-consumer.cmd cat $readable_file" test | MATCH test
         done
     fi
 
     if [ "$(snap debug confinement)" = strict ] ; then
+        echo "And the resources available with sandbox are not reachable without it"
+        if [ "$ALLOW_SANDBOX" = "false" ]; then
+            for readable_file in $READABLE_WITH_SANDBOX_FILES; do
+                if su -l -c "$SNAPMOUNTDIR/bin/browser-support-consumer.cmd cat $readable_file 2>${PWD}/readable-without-sandbox-read.err" test; then
+                    echo "Expected error without sandbox didn't happen"
+                    exit 1
+                fi
+                MATCH "Permission denied" < readable-without-sandbox-read.err
+            done
+        fi
+
         echo "When the plug is disconnected"
         snap disconnect browser-support-consumer:browser-support
         snap interfaces | MATCH "$DISCONNECTED_PATTERN"
