t/core/*-single-reboot-*: extend to core20+, use sideload instead of refresh for robustness

diff --git a/tests/core/kernel-base-gadget-pair-single-reboot/task.yaml b/tests/core/kernel-base-gadget-pair-single-reboot/task.yaml
--- a/tests/core/kernel-base-gadget-pair-single-reboot/task.yaml
+++ b/tests/core/kernel-base-gadget-pair-single-reboot/task.yaml
@@ -5,8 +5,11 @@ details: |
     together with a single reboot. The test then reverts each of the snaps to ensure system is left
     in untouched state. (Otherwise our spread checks will complain).
 
-# TODO make the test work with ubuntu-core-20
-systems: [ubuntu-core-18-*]
+systems: [ubuntu-core-18-*, ubuntu-core-2*]
+
+# run before remodel test, unfortunately some tests mess with snaps installed
+# and this causes this test to be messed with
+priority: 600
 
 environment:
     SNAP_ONE/kernel_base: core
@@ -18,56 +21,106 @@ environment:
     SNAP_ONE/kernel_gadget: pc
     SNAP_TWO/kernel_gadget: pc-kernel
 
-    BLOB_DIR: $(pwd)/fake-store-blobdir
+    GADGET_CHANNEL: edge
+    CORE18_GADGET_REPACK: true
+
+    # We are uploading too much in terms of size for the snaps
+    # we sideload. On UC18 this is disabled automatically, but
+    # on UC20+ this has proved to be an issue
+    SNAPD_NO_MEMORY_LIMIT: 1
 
 prepare: |
-    if [ "$TRUST_TEST_KEYS" = "false" ]; then
-        echo "This test needs test keys to be trusted"
-        exit
-    fi
+    # To get VERSION_ID defined
+    . /etc/os-release
 
-    core_snap=core20
-    if os.query is-core18; then
-        core_snap=core18
-    fi
+    # does not work for 16, but we don't support 16 for this
+    core_snap="core${VERSION_ID}"
 
     # read all for simplification
     readlink /snap/pc-kernel/current > pc-kernel.rev
     readlink "/snap/$core_snap/current" > core.rev
-    readlink "/snap/pc/current" > pc.rev
+    readlink /snap/pc/current > pc.rev
 
-restore: |
-    if [ "$TRUST_TEST_KEYS" = "false" ]; then
-        echo "This test needs test keys to be trusted"
-        exit
-    fi
-    "$TESTSTOOLS"/store-state teardown-fake-store "$BLOB_DIR"
+debug: |
+    change_id="$(cat refresh-change-id)"
+    snap debug state --change "$change_id" /var/lib/snapd/state.json
 
 execute: |
-    if [ "$TRUST_TEST_KEYS" = "false" ]; then
-        echo "This test needs test keys to be trusted"
-        exit
+    # To get VERSION_ID defined
+    . /etc/os-release
+
+    if not snap list pc; then
+        echo "This test needs a host using 'pc' gadget snap"
+        exit 1
     fi
 
-    core_snap=core20
-    if os.query is-core18; then
-        core_snap=core18
-    fi
-
+    # does not work for 16, but we don't support 16 for this
+    core_snap="core${VERSION_ID}"
+    
+    # correct the naming based on the system we are testing
     if [ "$SNAP_ONE" = "core" ]; then
         SNAP_ONE=$core_snap
     elif [ "$SNAP_TWO" = "core" ]; then
         SNAP_TWO=$core_snap
     fi
 
+    wait_and_verify_change() {
+        local CHANGE_ID="$1"
+        snap watch "$CHANGE_ID" || true
+        snap changes | MATCH "$CHANGE_ID\s+Done"
+        snap change "$CHANGE_ID" > tasks.done
+        # nothing has failed
+        NOMATCH '^Error' < tasks.done
+        # nothing was undone
+        NOMATCH '^Undone' < tasks.done
+        # nothing is waiting
+        NOMATCH '^Wait' < tasks.done
+
+        # we did not even try to hijack shutdown (/bin/systemctl) because that
+        # could race with snapd (if that wanted to call it), so just check that
+        # the system is in a stable state once we have already determined that
+        # the change is complete
+        # XXX systemctl exits with non-0 when in degraded state
+        # Note: on bionic, is-system-running does not support --wait
+        retry -n 30 sh -c '(systemctl is-system-running || true) | MATCH "(running|degraded)"'
+    }
+
     if [ "$SPREAD_REBOOT" = 0 ]; then
-        snap ack "$TESTSLIB/assertions/testrootorg-store.account-key"
-        "$TESTSTOOLS"/store-state setup-fake-store "$BLOB_DIR"
+        echo Downloading snaps needed
+        snap download pc-kernel --channel="$VERSION_ID"/edge
 
-        "$TESTSTOOLS"/store-state init-fake-refreshes "$BLOB_DIR" "$SNAP_ONE"
-        "$TESTSTOOLS"/store-state init-fake-refreshes "$BLOB_DIR" "$SNAP_TWO"
+        snap download "$core_snap" --edge --basename=core-for-repack
+        unsquashfs -d base-snap core-for-repack.snap
+        rm core-for-repack.snap core-for-repack.assert
+        snap pack base-snap
 
-        snap refresh --no-wait "$SNAP_ONE" "$SNAP_TWO" > refresh-change-id
+        # prepare gadget update if gadget variant
+        if [[ "$SNAP_ONE" == "pc" ]] || [[ "$SNAP_TWO" == "pc" ]]; then
+            # unsquash gadget for modification
+            cp /var/lib/snapd/snaps/pc_*.snap gadget.snap
+            unsquashfs -d pc-snap gadget.snap
+
+            cp pc-snap/meta/gadget.yaml gadget.yaml.orig
+
+            system_seed=""
+            if os.query is-core-ge 20; then
+                system_seed="--system-seed"
+            fi
+
+            # prepare update
+            python3 ../gadget-update-pc/generate.py ./gadget.yaml.orig v1 $system_seed > pc-snap/meta/gadget.yaml
+            echo 'this is foo-x2' > foo-x2.img
+            cp foo-x2.img pc-snap/foo.img
+            echo 'this is foo.cfg' > pc-snap/foo.cfg
+            if os.query is-core-ge 20; then
+                echo 'this is foo-seed.cfg' > pc-snap/foo-seed.cfg
+            fi
+            sed -i -e 's/^version: \(.*\)-1/version: \1-2/' pc-snap/meta/snap.yaml
+            snap pack pc-snap --filename=pc_x1.snap
+        fi
+
+        snap install "$(ls ${SNAP_ONE}_*.snap)" "$(ls ${SNAP_TWO}_*.snap)" --dangerous --no-wait > refresh-change-id
+
         test -n "$(cat refresh-change-id)"
         change_id="$(cat refresh-change-id)"
         
@@ -97,13 +150,13 @@ execute: |
                 MATCH 'snap_mode=try' < boot-vars.dump
                 MATCH 'snap_try_kernel=pc-kernel_.*.snap' < boot-vars.dump
             fi
-        elif os.query is-core20; then
+        elif os.query is-core-ge 20; then
             if [[ "$SNAP_ONE" == "pc-kernel" ]] || [[ "$SNAP_TWO" == "pc-kernel" ]]; then
-                stat /boot/grub/try-kernel.efi | MATCH 'pc_kernel.*.snap/kernel.efi'
+                stat /boot/grub/try-kernel.efi | MATCH 'pc-kernel.*.snap/kernel.efi'
                 stat -L /boot/grub/try-kernel.efi
             fi
             if [[ "$SNAP_ONE" == *"core"* ]] || [[ "$SNAP_TWO" == *"core"* ]]; then
-                MATCH 'try_base=core20_.*.snap' < /var/lib/snapd/modeenv
+                MATCH "try_base=core${VERSION_ID}_.*.snap" < /var/lib/snapd/modeenv
             fi
         else
             echo "unsupported Ubuntu Core system"
@@ -113,60 +166,65 @@ execute: |
         REBOOT
     elif [ "$SPREAD_REBOOT" = 1 ]; then
         change_id="$(cat refresh-change-id)"
-        # XXX: is this sufficiently robust?
-        snap watch "$change_id" || true
-        snap changes | MATCH "$change_id\s+(Done|Error)"
-        # we expect re-refresh to fail since the tests uses a fake store
-        snap change "$change_id" > tasks.done
-        MATCH '^Error .* Monitoring .* to determine whether extra refresh steps are required' < tasks.done
-        # no other errors
-        grep -v 'Monitoring .* to determine whether extra refresh steps are required' < tasks.done | NOMATCH '^Error'
-        # nothing was undone
-        grep -v 'Monitoring .* to determine whether extra refresh steps are required' < tasks.done | NOMATCH '^Undone'
-        # we did not even try to hijack shutdown (/bin/systemctl) because that
-        # could race with snapd (if that wanted to call it), so just check that
-        # the system is in a stable state once we have already determined that
-        # the change is complete
-        # XXX systemctl exits with non-0 when in degraded state
-        # Note: on bionic, is-system-running does not support --wait
-        retry -n 30 sh -c '(systemctl is-system-running || true) | MATCH "(running|degraded)"'
+        wait_and_verify_change "$change_id"
+        
+        expecting_kernel="$(($(grep -o -E '[0-9]+' < pc-kernel.rev) + 1))"
+        expecting_gadget="$(($(grep -o -E '[0-9]+' < pc.rev) + 1))"
+        expecting_core="$(($(grep -o -E '[0-9]+' < core.rev) + 1))"
+        if ! grep "x" ./core.rev; then
+            expecting_core="1"
+        fi
 
         # fake refreshes generate revision numbers that are n+1
         # verify that current points to new revisions
         if [[ "$SNAP_ONE" == *"core"* ]] || [[ "$SNAP_TWO" == *"core"* ]]; then
-            expecting_core="$(($(cat core.rev) + 1))"
-            test "$(readlink /snap/$core_snap/current)" = "$expecting_core"
+            test "$(readlink /snap/$core_snap/current | grep -o -E '[0-9]+')" = "$expecting_core"
         fi
         if [[ "$SNAP_ONE" == "pc" ]] || [[ "$SNAP_TWO" == "pc" ]]; then
-            expecting_gadget="$(($(cat pc.rev) + 1))"
-            test "$(readlink /snap/pc/current)" = "$expecting_gadget"
+            test "$(readlink /snap/pc/current | grep -o -E '[0-9]+')" = "$expecting_gadget"
         fi
         if [[ "$SNAP_ONE" == "pc-kernel" ]] || [[ "$SNAP_TWO" == "pc-kernel" ]]; then
-            expecting_kernel="$(($(cat pc-kernel.rev) + 1))"
-            test "$(readlink /snap/pc-kernel/current)" = "$expecting_kernel"
+            test "$(readlink /snap/pc-kernel/current | grep -o -E '[0-9]+')" = "$expecting_kernel"
         fi
 
         # now we need to revert both snaps for restore to behave properly, go from
         # reverse order
-        snap revert "$SNAP_TWO" --revision "$(cat ${SNAP_TWO}.rev)"
+        snap revert "$SNAP_TWO" --no-wait > revert-change-id
+
+        # no reboot on pc revert
+        if [[ "$SNAP_TWO" == "pc" ]]; then
+            change_id="$(cat revert-change-id)"
+            wait_and_verify_change "$change_id"
+
+            # now the first
+            snap revert "$SNAP_ONE" --no-wait > revert-change-id
+        fi
+
+        retry -n 50 --wait 1 sh -c 'journalctl -b -u snapd | MATCH "Waiting for system reboot"'
         REBOOT
-    elif [ "$SPREAD_REBOOT" = 2 ]; then
-        snap watch --last=revert\?
+    elif [ "$SPREAD_REBOOT" = 2 ] && [[ "$SNAP_ONE" != "pc" ]] && [[ "$SNAP_TWO" != "pc" ]]; then
+        change_id="$(cat revert-change-id)"
+        wait_and_verify_change "$change_id"
+
         # now the first
-        snap revert "$SNAP_ONE" --revision "$(cat ${SNAP_ONE}.rev)"
+        snap revert "$SNAP_ONE" --no-wait > revert-change-id
+
+        retry -n 50 --wait 1 sh -c 'journalctl -b -u snapd | MATCH "Waiting for system reboot"'
         REBOOT
-    elif [ "$SPREAD_REBOOT" = 3 ]; then
-        snap watch --last=revert\?
+    elif [ "$SPREAD_REBOOT" = 2 ] || [ "$SPREAD_REBOOT" = 3 ]; then
+        change_id="$(cat revert-change-id)"
+        wait_and_verify_change "$change_id"
+
+        if [[ "$SNAP_ONE" == "pc" ]]; then
+            snap revert "$SNAP_ONE" --no-wait > revert-change-id
+            change_id="$(cat revert-change-id)"
+            wait_and_verify_change "$change_id"
+        fi
+        
         # we're done, verify current symlinks to the right revisions
-        if [[ "$SNAP_ONE" == *"core"* ]] || [[ "$SNAP_TWO" == *"core"* ]]; then
-            test "$(readlink /snap/$core_snap/current)" = "$(cat core.rev)"
-        fi
-        if [[ "$SNAP_ONE" == "pc" ]] || [[ "$SNAP_TWO" == "pc" ]]; then
-            test "$(readlink /snap/pc/current)" = "$(cat pc.rev)"
-        fi
-        if [[ "$SNAP_ONE" == "pc-kernel" ]] || [[ "$SNAP_TWO" == "pc-kernel" ]]; then
-            test "$(readlink /snap/pc-kernel/current)" = "$(cat pc-kernel.rev)"
-        fi
+        test "$(readlink /snap/$core_snap/current)" = "$(cat core.rev)"
+        test "$(readlink /snap/pc/current)" = "$(cat pc.rev)"
+        test "$(readlink /snap/pc-kernel/current)" = "$(cat pc-kernel.rev)"
     else
         echo "unexpected reboot"
         exit 1
