tests/core/*-single-reboot: robustness for revert cases, ensure we wait for system to be ready before continuing revert

diff --git a/tests/core/kernel-base-gadget-pair-single-reboot/task.yaml b/tests/core/kernel-base-gadget-pair-single-reboot/task.yaml
--- a/tests/core/kernel-base-gadget-pair-single-reboot/task.yaml
+++ b/tests/core/kernel-base-gadget-pair-single-reboot/task.yaml
@@ -60,6 +60,27 @@ execute: |
         SNAP_TWO=$core_snap
     fi
 
+    wait_and_verify_change {
+        local CHANGE_ID="$1"
+        snap watch "$CHANGE_ID" || true
+        snap changes | MATCH "$CHANGE_ID\s+Done"
+        snap change "$CHANGE_ID" > tasks.done
+        # nothing has failed
+        NOMATCH '^Error' < tasks.done
+        # nothing was undone
+        NOMATCH '^Undone' < tasks.done
+        # nothing is waiting
+        NOMATCH '^Wait' < tasks.done
+
+        # we did not even try to hijack shutdown (/bin/systemctl) because that
+        # could race with snapd (if that wanted to call it), so just check that
+        # the system is in a stable state once we have already determined that
+        # the change is complete
+        # XXX systemctl exits with non-0 when in degraded state
+        # Note: on bionic, is-system-running does not support --wait
+        retry -n 30 sh -c '(systemctl is-system-running || true) | MATCH "(running|degraded)"'
+    }
+
     if [ "$SPREAD_REBOOT" = 0 ]; then
         echo Downloading snaps needed
         snap download pc-kernel --channel="$VERSION_ID"/edge
@@ -141,24 +162,8 @@ execute: |
         REBOOT
     elif [ "$SPREAD_REBOOT" = 1 ]; then
         change_id="$(cat refresh-change-id)"
-        # XXX: is this sufficiently robust?
-        snap watch "$change_id" || true
-        snap changes | MATCH "$change_id\s+Done"
-        snap change "$change_id" > tasks.done
-        # nothing has failed
-        NOMATCH '^Error' < tasks.done
-        # nothing was undone
-        NOMATCH '^Undone' < tasks.done
-        # nothing is waiting
-        NOMATCH '^Wait' < tasks.done
-        # we did not even try to hijack shutdown (/bin/systemctl) because that
-        # could race with snapd (if that wanted to call it), so just check that
-        # the system is in a stable state once we have already determined that
-        # the change is complete
-        # XXX systemctl exits with non-0 when in degraded state
-        # Note: on bionic, is-system-running does not support --wait
-        retry -n 30 sh -c '(systemctl is-system-running || true) | MATCH "(running|degraded)"'
-
+        wait_and_verify_change "$change_id"
+        
         # fake refreshes generate revision numbers that are n+1
         # verify that current points to new revisions
         if [[ "$SNAP_ONE" == *"core"* ]] || [[ "$SNAP_TWO" == *"core"* ]]; then
@@ -177,15 +182,22 @@ execute: |
 
         # now we need to revert both snaps for restore to behave properly, go from
         # reverse order
-        snap revert "$SNAP_TWO"
+        snap revert "$SNAP_TWO" --no-wait > revert-change-id
+        retry -n 50 --wait 1 sh -c 'journalctl -b -u snapd | MATCH "Waiting for system reboot"'
+
         REBOOT
     elif [ "$SPREAD_REBOOT" = 2 ]; then
-        snap watch --last=revert\?
+        change_id="$(cat revert-change-id)"
+        wait_and_verify_change "$change_id"
+
         # now the first
-        snap revert "$SNAP_ONE"
+        snap revert "$SNAP_ONE" --no-wait > revert-change-id
+        retry -n 50 --wait 1 sh -c 'journalctl -b -u snapd | MATCH "Waiting for system reboot"'
+
         REBOOT
     elif [ "$SPREAD_REBOOT" = 3 ]; then
-        snap watch --last=revert\?
+        change_id="$(cat revert-change-id)"
+        wait_and_verify_change "$change_id"
         
         # we're done, verify current symlinks to the right revisions
         test "$(readlink /snap/$core_snap/current)" = "$(cat core.rev)"
