tests: change release/distro-upgrade test to allow for missing interim

diff --git a/tests/release/distro-upgrade/task.yaml b/tests/release/distro-upgrade/task.yaml
--- a/tests/release/distro-upgrade/task.yaml
+++ b/tests/release/distro-upgrade/task.yaml
@@ -53,25 +53,31 @@ restore: |
     sed -i 's/Prompt=normal/Prompt=never/' /etc/update-manager/release-upgrades
 
 execute: |
+    # Grab all supported distros except for the first one, which presumably we're running on
+    mapfile -t upgrades < <(ubuntu-distro-info --supported --release | awk '{print $1}' | sed 1d)
+
+    #####################################################################################
+    # The upgrades array contains the distros that we will be upgrading to.
+    # To manually supply the upgrades, uncomment this next line with desired versions.
+    # upgrades=(24.04 25.10 26.04)
+    #####################################################################################
+
     # Don't fail the test if the distro is missing the latest snapd version. Sometimes one distro
     # doesn't have the latest yet.
     ./check-snapd-version.sh "$(cat initial-snapd-version.txt)" || [ "$SRU_VALIDATION" = "1" ]
     snap version --verbose > snapd-versions/"$(lsb_release -c -s)"
 
-    while not os.query is-ubuntu-devel; do
+    while ! os.query is-ubuntu "${upgrades[${#upgrades[@]}-1]}"; do
         # We can only upgrade the distro if we have all upgrades installed
         apt update
         apt upgrade -y
         if [[ "$SPREAD_REBOOT" = 0 ]]; then
             REBOOT
         fi
-        devel_option=
-        if os.query is-ubuntu-interim; then
-            devel_option="-d"
-        fi
 
         echo "Upgrading $(grep -oP 'CODENAME=\K.*' /etc/os-release | head -1)"
-        sudo do-release-upgrade "$devel_option" -f DistUpgradeViewNonInteractive
+        sudo do-release-upgrade -f DistUpgradeViewNonInteractive || \
+            sudo do-release-upgrade -d -f DistUpgradeViewNonInteractive
 
         if [ "$SRU_VALIDATION" = "1" ] || [ -n "$PPA_VALIDATION_NAME" ]; then
             #shellcheck source=tests/lib/pkgdb.sh
@@ -89,25 +95,13 @@ execute: |
         ./check-snapd-version.sh "$(cat initial-snapd-version.txt)" || [ "$SRU_VALIDATION" = "1" ]
         snap version --verbose > snapd-versions/"$(lsb_release -c -s)"
 
-        if os.query is-ubuntu-latest-lts; then
-            touch lts-upgrade-done
-        elif os.query is-ubuntu-interim; then
-            touch interim-upgrade-done
-        elif os.query is-ubuntu-devel; then
-            touch devel-upgrade-done
-        fi
+        touch "$(grep -oP 'VERSION_ID="\K.*[^"]+' /etc/os-release)-done"
         SPREAD_REBOOT=0
     done
 
-    if not [ -f lts-upgrade-done ]; then
-        echo "We should have done an LTS upgrade but didn't"
-        exit 1
-    fi
-    if not [ -f interim-upgrade-done ]; then
-        echo "We should have done an interim upgrade but didn't"
-        exit 1
-    fi
-    if not [ -f devel-upgrade-done ]; then
-        echo "We should have done a devel upgrade but didn't"
-        exit 1
-    fi
+    for upgrade in "${upgrades[@]}"; do
+        if [ ! -f "$upgrade-done" ]; then
+            echo "Upgrade to $upgrade failed."
+            exit 1
+        fi
+    done
