fixed indentation in shell blocks

diff --git a/tests/main/abort/task.yaml b/tests/main/abort/task.yaml
--- a/tests/main/abort/task.yaml
+++ b/tests/main/abort/task.yaml
@@ -6,9 +6,9 @@ environment:
 execute: |
     echo "Abort with invalid id"
     if snap abort 10000000; then
-      echo "abort with invalid id should fail"
-      exit 1
-      fi
+        echo "abort with invalid id should fail"
+        exit 1
+    fi
 
     echo "===================================="
 
@@ -16,12 +16,12 @@ execute: |
     subdirPath="/snap/$SNAP_NAME/current/foo"
     mkdir -p $subdirPath
     if snap install $SNAP_NAME; then
-      echo "install should fail when the target directory exists"
-      exit 1
+        echo "install should fail when the target directory exists"
+        exit 1
     fi
     if snap abort 1; then
-      echo "abort with valid failed id should fail"
-      exit 1
+        echo "abort with valid failed id should fail"
+        exit 1
     fi
     rm -rf $subdirPath
 
@@ -30,6 +30,6 @@ execute: |
     echo "Abort with valid id - done"
     snap install $SNAP_NAME
     if snap abort 2; then
-      echo "abort with valid done id should fail"
-      exit 1
+        echo "abort with valid done id should fail"
+        exit 1
     fi
diff --git a/tests/main/change-errors/task.yaml b/tests/main/change-errors/task.yaml
--- a/tests/main/change-errors/task.yaml
+++ b/tests/main/change-errors/task.yaml
@@ -3,5 +3,5 @@ summary: Checks for cli errors of the change command.
 execute: |
     echo "When an invalid ID is given to the change command it shows an error"
     if snap change 10000000; then
-      echo "Expected error when trying change on invalid ID" && exit 1
+        echo "Expected error when trying change on invalid ID" && exit 1
     fi
diff --git a/tests/main/install-errors/task.yaml b/tests/main/install-errors/task.yaml
--- a/tests/main/install-errors/task.yaml
+++ b/tests/main/install-errors/task.yaml
@@ -20,24 +20,24 @@ restore: |
 execute: |
     echo "Install unexisting snap prints error"
     if snap install unexisting.canonical; then
-      echo "Installing unexisting snap should fail"
-      exit 1
+        echo "Installing unexisting snap should fail"
+        exit 1
     fi
 
     echo "============================================"
 
     echo "Install without snap name shows error"
     if snap install; then
-      echo "Installing without snap name should fail"
-      exit 1
+        echo "Installing without snap name should fail"
+        exit 1
     fi
 
     echo "============================================"
 
     echo "Install points to login when not authenticated"
     if sudo -i -u test /bin/sh -c "snap install hello-world 2>${PWD}/install.output"; then
-      echo "Unauthenticated install should fail"
-      exit 1
+        echo "Unauthenticated install should fail"
+        exit 1
     fi
     grep "snap login --help" install.output
 
@@ -45,14 +45,14 @@ execute: |
 
     echo "Calling a failing command from a snap should fail"
     if test-snapd-tools.fail; then
-      echo "Failing snap commands should keep failing after installed"
-      exit 1
+        echo "Failing snap commands should keep failing after installed"
+        exit 1
     fi
 
     echo "============================================"
 
     echo "Install a snap already installed fails"
     if snap install $STORE_SNAP_NAME; then
-      echo "Trying to install an already installed snap should fail"
-      exit 1
+        echo "Trying to install an already installed snap should fail"
+        exit 1
     fi
diff --git a/tests/main/remove-errors/task.yaml b/tests/main/remove-errors/task.yaml
--- a/tests/main/remove-errors/task.yaml
+++ b/tests/main/remove-errors/task.yaml
@@ -3,8 +3,8 @@ summary: Check remove command errors
 execute: |
     echo "An error is returned when trying to remove an non installed snap"
     if snap remove hello-world; then
-      echo "An error is expected when trying to remove a non installed snap"
-      exit 1
+        echo "An error is expected when trying to remove a non installed snap"
+        exit 1
     fi
     echo "================================"
 
@@ -13,6 +13,6 @@ execute: |
 
     echo "An error is returned whrn trying to remove ubuntu-core"
     if snap remove ubuntu-core; then
-      echo "An error is expected when trying to remove ubuntu-core"
-      exit 1
+        echo "An error is expected when trying to remove ubuntu-core"
+        exit 1
     fi
