changed yaml indentation to 4 spaces

diff --git a/tests/main/change-errors/task.yaml b/tests/main/change-errors/task.yaml
--- a/tests/main/change-errors/task.yaml
+++ b/tests/main/change-errors/task.yaml
@@ -1,7 +1,7 @@
 summary: Checks for cli errors of the change command.
 
 execute: |
-  echo "When an invalid ID is given to the change command it shows an error"
-  if snap change 10000000; then
-    echo "Expected error when trying change on invalid ID" && exit 1
-  fi
+    echo "When an invalid ID is given to the change command it shows an error"
+    if snap change 10000000; then
+      echo "Expected error when trying change on invalid ID" && exit 1
+    fi
