avoid running the full run-spread nested test when it is updated
The test will fail but it won't run the full set of tests. Also it has
been removed the full variant as it is not used and it is triggering a
full run as well.

diff --git a/tests/nested/manual/run-spread/task.yaml b/tests/nested/manual/run-spread/task.yaml
--- a/tests/nested/manual/run-spread/task.yaml
+++ b/tests/nested/manual/run-spread/task.yaml
@@ -14,8 +14,6 @@ warn-timeout: 3m
 kill-timeout: 8h
 
 environment:
-    TESTS/full: "tests/"
-    NESTED_BUILD_SNAPD_FROM_CURRENT/full: true
     TESTS/smoke: "tests/smoke/"
     NESTED_BUILD_SNAPD_FROM_CURRENT/smoke: true
     TESTS/custom: ""
@@ -43,6 +41,10 @@ execute: |
 
     RUN_TESTS="external:$NESTED_SPREAD_SYSTEM:$TESTS"
     if [ "$SPREAD_VARIANT" = "custom" ]; then
+        if [ -z "$NESTED_SPREAD_TESTS" ]; then
+            echo "When using the custom variant, it is required to set the NESTED_SPREAD_TESTS env var"
+            exit 1
+        fi
         RUN_TESTS="$NESTED_SPREAD_TESTS"
         remote.refresh full
     fi
