Adding more info to the debug log

diff --git a/tests/main/interfaces-openvswitch/task.yaml b/tests/main/interfaces-openvswitch/task.yaml
--- a/tests/main/interfaces-openvswitch/task.yaml
+++ b/tests/main/interfaces-openvswitch/task.yaml
@@ -47,6 +47,8 @@ debug: |
     tail -n100 /var/log/syslog || echo "failed"
     echo "------------------------------"
     ifconfig || echo failed
+    echo "------------------------------"
+    journalctl -xu openvswitch.service || echo "failed"
     echo "=============================="
 
 execute: |
