address review feedback, improve tests

diff --git a/tests/main/snap-set-core-w-no-core/task.yaml b/tests/main/snap-set-core-w-no-core/task.yaml
--- a/tests/main/snap-set-core-w-no-core/task.yaml
+++ b/tests/main/snap-set-core-w-no-core/task.yaml
@@ -14,3 +14,9 @@ execute: |
 
     echo "Check that we can set core config nevertheless"
     snap set core system.power-key-action="ignore"
+
+    echo "Ensure that unknown options are rejected"
+    if snap set core unknown.option=1; then
+        echo "snap set core must error for unknown options"
+        exit 1
+    fi
