Iterate until it is possible to umount /tmp

diff --git a/tests/main/install-store-laaaarge/task.yaml b/tests/main/install-store-laaaarge/task.yaml
--- a/tests/main/install-store-laaaarge/task.yaml
+++ b/tests/main/install-store-laaaarge/task.yaml
@@ -15,7 +15,17 @@ restore: |
     . "$TESTSLIB/systemd.sh"
 
     systemd_stop_units snapd.service snapd.socket
-    umount /tmp
+    # Iterate trying to umount /tmp which could be busy
+    for i in $(seq 10); do
+        if [ $i -eq 10 ]; then
+            echo "Failed to umount /tmp"
+            exit 1
+        fi
+        if umount /tmp; then
+            break
+        fi
+        sleep 1
+    done
     systemctl start snapd.{socket,service}
 
 execute: |
