tests: add xdg-settings test

diff --git a/tests/main/xdg-settings/task.yaml b/tests/main/xdg-settings/task.yaml
--- a/tests/main/xdg-settings/task.yaml
+++ b/tests/main/xdg-settings/task.yaml
@@ -18,7 +18,11 @@ restore: |
 execute: |
     . "$TESTSLIB/pkgdb.sh"
     . "$TESTSLIB/dirs.sh"
+    . "$TESTSLIB/snaps.sh"
 
+    install_local test-snapd-xdg-settings
+
+    # setup dbus
     dbus-launch > dbus.env
     export $(cat dbus.env | xargs)
 
@@ -45,23 +49,40 @@ execute: |
     touch /usr/bin/xdg-settings
     mount --bind /tmp/xdg-settings /usr/bin/xdg-settings
 
-    # ensure zenity always answers "yes"
-    touch /usr/bin/zenity
-    mount --bind /bin/true /usr/bin/zenity
-
     ensure_xdg_settings_output() {
         rm -f /tmp/xdg-settings-output
         export DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS
-        $SNAP_MOUNT_DIR/core/current/usr/bin/xdg-settings $1 $2 $3
+
+        # run xdg-settings from inside the snap
+        test-snapd-xdg-settings.set-default-web-browser browser.desktop
+
+        # verify that the command was transmited corrected via dbus
         test -e /tmp/xdg-settings-output
-        test "$(cat /tmp/xdg-settings-output)" = "$1 $2 $3"
+        test "$(cat /tmp/xdg-settings-output)" = "set default-web-browser test-snapd-xdg-settings_browser.desktop"
     }
 
-    ensure_xdg_settings_output "set" "default-web-browser" "foo.desktop"
+    # ensure zenity answers "yes"
+    touch /usr/bin/zenity
+    mount --bind /bin/true /usr/bin/zenity
+
+    ensure_xdg_settings_output "set" "default-web-browser" "browser.desktop"
 
     # Ensure settings whitelist for settings and values works
     rm /tmp/xdg-settings-output
     ! $SNAP_MOUNT_DIR/core/current/usr/bin/xdg-settings set random-settting something
     test ! -e /tmp/xdg-settings-output
     ! $SNAP_MOUNT_DIR/core/current/usr/bin/xdg-settings set default-web-browser inälid
+    test ! -e /tmp/xdg-settings-output
+
+
+    # ensure zenity answers "no"
+    umount /usr/bin/zenity
+    mount --bind /bin/false /usr/bin/zenity
+
+    rm -f /tmp/xdg-settings-output
+    if test-snapd-xdg-settings.set-default-web-browser browser.desktop; then
+        echo "setting the browser should fails if zenity returns false"
+        echo "test broken"
+        exit 1
+    fi
     test ! -e /tmp/xdg-settings-output
