tests/main/xdg-settings: tweak cgroupv2 checks
Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>

diff --git a/tests/main/xdg-settings/task.yaml b/tests/main/xdg-settings/task.yaml
--- a/tests/main/xdg-settings/task.yaml
+++ b/tests/main/xdg-settings/task.yaml
@@ -73,7 +73,10 @@ execute: |
 
     if is_cgroupv2 ; then
         # we are expecting the test to fail on a cgroup v2 system
-        not ensure_xdg_settings_output "set" "default-web-browser" "browser.desktop"
+        if ensure_xdg_settings_output "http://smoke-test-cgroupv2.com" 2> stderr.log ; then
+            echo "expected failure, but none happened"
+            exit 1
+        fi
         MATCH 'WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement' < stderr.log
         MATCH 'cannot find snap for connection: not supported' < stderr.log
         exit 0
