tests/core20-kernel-failover: some fixes for new tests
* For "nolink", test for link before trying to remove (install is
  --no-wait)
* Don't wait for reboot for some tests, as that won't happen in the
  case when keys cannot be re-sealed.

diff --git a/tests/nested/core/core20-kernel-failover/task.yaml b/tests/nested/core/core20-kernel-failover/task.yaml
--- a/tests/nested/core/core20-kernel-failover/task.yaml
+++ b/tests/nested/core/core20-kernel-failover/task.yaml
@@ -65,11 +65,19 @@ execute: |
   echo "Install it and get the ID for the change"
   REMOTE_CHG_ID=$(tests.nested exec sudo snap install --dangerous panicking-initramfs-kernel.snap --no-wait)
   if [ "$PROBLEM_TYPE" = "nolink" ]; then
+      while ! tests.nested exec test -f /run/mnt/ubuntu-boot/EFI/ubuntu/try-kernel.efi
+      do sleep 5
+      done
       tests.nested exec sudo rm /run/mnt/ubuntu-boot/EFI/ubuntu/try-kernel.efi
   fi
 
-  # wait for a reboot
-  tests.nested wait-for reboot "${boot_id}"
+  # wait for a reboot. Note that failure is immediate for kernel.efi
+  # files with invalid PE headers in the FDE case, as snapd is not
+  # able to reseal the encryption key in that case ("cannot compute
+  # load verification event").
+  if [ "$PROBLEM_TYPE" != "empty" ] && [ "$PROBLEM_TYPE" != "zeros" ]; then
+      tests.nested wait-for reboot "${boot_id}"
+  fi
 
   # Wait for the change to finish - note it will exit with non-zero since the 
   # change will fail, so don't let that kill the test here
@@ -80,7 +88,14 @@ execute: |
 
   echo "Check that the refresh failed"
   tests.nested exec sudo snap changes | grep "${REMOTE_CHG_ID}" | MATCH Error
-  tests.nested exec sudo snap tasks "${REMOTE_CHG_ID}" | MATCH "cannot finish .* installation, there was a rollback across reboot"
+  case "$PROBLEM_TYPE" in
+      empty|zeros)
+          tests.nested exec sudo snap tasks "${REMOTE_CHG_ID}" | MATCH "cannot set next boot: cannot reseal the encryption key:"
+          ;;
+      *)
+          tests.nested exec sudo snap tasks "${REMOTE_CHG_ID}" | MATCH "cannot finish .* installation, there was a rollback across reboot"
+          ;;
+  esac
 
   echo "Check We should be on the same revision of the kernel snap"
   if [ "$(tests.nested exec sudo snap list pc-kernel | grep pc-kernel | awk '{print $3}')" != "${startRevision}" ]; then
