tests/main/snapd-snap: test installing the snapd snap and connecting interfaces
This is originally from the work to vendor apparmor 3 into the snapd snap, but
is more useful generally as it ensures we can install/use the snapd snap on
classic.

Having this test here will make it easier to propose some changes to the snapd
snap and ensure those are adequately tested.

Signed-off-by: Ian Johnson <ian.johnson@canonical.com>

diff --git a/tests/main/snapd-snap/task.yaml b/tests/main/snapd-snap/task.yaml
--- a/tests/main/snapd-snap/task.yaml
+++ b/tests/main/snapd-snap/task.yaml
@@ -32,30 +32,29 @@ systems:
 
 # Start early as it takes a long time.
 priority: 100
+kill-timeout: 35m
 
 environment:
     # the destructive build mode runs only on xenial, but we also run lxd on
     # xenial to make sure it builds there too
     SNAPCRAFT_BUILD_ENVIRONMENT/destructive: host
     SNAPCRAFT_BUILD_ENVIRONMENT/lxd: lxd
+    CONSUMER_SNAP: test-snapd-policy-app-consumer
 
 prepare: |
     # shellcheck source=tests/lib/systems.sh
     . "$TESTSLIB/systems.sh"
-
     # only run the destructive mode variant on xenial
     if ! os.query is-xenial && [ "$SNAPCRAFT_BUILD_ENVIRONMENT" = "host" ]; then
         echo "Skipping destructive mode build on non-xenial"
         exit 0
     fi
-
     if is_cgroupv2 && [ "$SNAPCRAFT_BUILD_ENVIRONMENT" = "lxd" ]; then
         # snapd snap uses core build base (16.04) which cannot be booted
         # properly on a host using unified hierarchy
         echo "Skipping LXD build with unified cgroup hierarchy"
         exit 0
     fi
-
     if os.query is-fedora || os.query is-arch-linux || os.query is-centos; then
         # in order to install classic snaps, we need to setup the /snap 
         # symlink on these distros
@@ -63,11 +62,9 @@ prepare: |
         ln -sf "$SNAP_MOUNT_DIR" /snap
         tests.cleanup defer rm -f /snap
     fi
-
     echo "Install snapcraft from 4.x/candidate"
     snap install snapcraft --channel=4.x/candidate --classic
     tests.cleanup defer snap remove --purge snapcraft
-
     if [ "$SNAPCRAFT_BUILD_ENVIRONMENT" = "lxd" ]; then
         echo "Remove any installed debs (some images carry them) to ensure we test the snap"
         # apt -v to test if apt is usable
@@ -79,19 +76,15 @@ prepare: |
                 apt-get autoremove -y lxd-client
             fi
         fi
-
         # load the fuse kernel module before installing lxd
         modprobe fuse
-
         echo "Install lxd"
         snap install lxd --channel="$LXD_SNAP_CHANNEL"
         tests.cleanup defer snap remove --purge lxd
-
         echo "Setup the lxd snap"
         snap set lxd waitready.timeout=240
         lxd waitready
         lxd init --auto
-
         echo "Setting up proxy for lxc"
         if [ -n "${http_proxy:-}" ]; then
             lxd.lxc config set core.proxy_http "$http_proxy"
@@ -99,7 +92,6 @@ prepare: |
         if [ -n "${https_proxy:-}" ]; then
             lxd.lxc config set core.proxy_https "$http_proxy"
         fi
-
         echo "Switch the core snap back due to spread system prepare shenanigans"
         # When we run spread, we will repack the core snap that is installed on
         # the system to match the binaries that we built on this system so that
@@ -115,48 +107,64 @@ prepare: |
         # As such, we need to switch the modified core snap on the system back 
         # with the original core snap on the system that is unmodified and will
         # match the expected assertions that snapcraft calculates
-
         # the easy way is to trick snapd is to just mount back the original file
         # on top of the repacked one, then snapd will just serve the correct
         # file over HTTP to snapcraft when it asks for it
-
-        # When the SRU validation tests are executed, the core snap is not repacked
-        # and the var MODIFY_CORE_SNAP_FOR_REEXEC is 0
-        if [ "$MODIFY_CORE_SNAP_FOR_REEXEC" = 1 ]; then
-            CORE_SNAP_REV=$(snap list core | grep -v Name | awk '{print $3}')
-            CORE_SNAP="/var/lib/snapd/snaps/core_${CORE_SNAP_REV}.snap"
-            ORIG_CORE_SNAP=${CORE_SNAP}.orig
-
-            mount --bind "$ORIG_CORE_SNAP" "$CORE_SNAP"
-            tests.cleanup defer umount "$CORE_SNAP"
-        fi
+        CORE_SNAP_REV=$(snap list core | grep -v Name | awk '{print $3}')
+        CORE_SNAP="/var/lib/snapd/snaps/core_${CORE_SNAP_REV}.snap"
+        ORIG_CORE_SNAP=${CORE_SNAP}.orig
+        
+        mount --bind "$ORIG_CORE_SNAP" "$CORE_SNAP"
+        tests.cleanup defer umount "$CORE_SNAP"
     fi
-
+debug: |
+    # get the snapd sandbox features
+    snap debug sandbox-features
+    # get the full journal to see any out-of-memory errors
+    # shellcheck disable=SC2119
+    "$TESTSTOOLS"/journal-state get-log
 execute: |
     # shellcheck source=tests/lib/systems.sh
     . "$TESTSLIB/systems.sh"
-
     # only run the destructive mode variant on xenial
     if ! os.query is-xenial && [ "$SNAPCRAFT_BUILD_ENVIRONMENT" = "host" ]; then
         echo "Skipping destructive mode build on non-xenial"
         exit 0
     fi
-
     if is_cgroupv2 && [ "$SNAPCRAFT_BUILD_ENVIRONMENT" = "lxd" ]; then
         # snapd snap uses core build base (16.04) which cannot be booted
         # properly on a host using unified hierarchy
         echo "Skipping LXD build with unified cgroup hierarchy"
         exit 0
     fi
-
+    if [ "$SPREAD_REBOOT" != "0" ]; then
+      if os.query is-trusty; then
+        # seems we have to kick trusty along
+        systemctl restart snapd
+      fi
+      snap list | MATCH snapd
+      systemctl status snapd.service
+      if ! os.query is-trusty && ! os.query is-xenial; then
+        systemctl status snapd.apparmor.service
+      fi
+      echo "Rebooted successfully"
+      exit 0
+    fi
     # shellcheck disable=SC2164
     pushd "$PROJECT_PATH"
+    echo "Ensure we use the correct version when host is 14.04"
+    if os.query is-trusty; then
+      # prepare-restore.sh will only have updated
+      # packaging/ubuntu-14.04/changelog so make sure this is also done for
+      # the ubuntu-16.04 packaging as well as this is what will be used to
+      # build the snapd snap
+      # Use fake version to ensure we are always bigger than anything else
+      dch --changelog packaging/ubuntu-16.04/changelog --newversion "1337.$(dpkg-parsechangelog --show-field Version)" "testing build"
+    fi
     echo "Build the snap"
     snap run snapcraft snap --output=snapd_spread-test.snap
     popd
-
     mv "$PROJECT_PATH/snapd_spread-test.snap" "$PWD/snapd_spread-test.snap"
-
     # meh it doesn't work well to use quotas and "&&" in the arguments to sh -c
     # with defer, so just put what we want to run in a script and execute that
     cat >> snapcraft-cleanup.sh <<EOF
@@ -166,19 +174,142 @@ execute: |
     EOF
     chmod +x snapcraft-cleanup.sh
     tests.cleanup defer sh -c "$PWD/snapcraft-cleanup.sh"
-
     echo "Ensure we have the fc-cache binaries"
     unsquashfs -ll snapd_spread-test.snap | MATCH bin/fc-cache-v6
     unsquashfs -ll snapd_spread-test.snap | MATCH bin/fc-cache-v7
-
     echo "Ensure we have xdelta3"
     unsquashfs -ll snapd_spread-test.snap | MATCH bin/xdelta3
-
     echo "Ensure we have mksquashfs (and the dependencies)"
     unsquashfs -ll snapd_spread-test.snap | MATCH bin/mksquashfs
     unsquashfs -ll snapd_spread-test.snap | MATCH liblzma.so.5
-
     echo "Ensure we have ld.so.conf"
     unsquashfs -ll snapd_spread-test.snap | MATCH etc/ld.so.conf
     echo "Ensure we have libc"
     unsquashfs -ll snapd_spread-test.snap | MATCH libc.so
+    echo "Ensure we can install the snapd snap"
+    snap install --dangerous snapd_spread-test.snap
+    cat >> snapd-cleanup.sh <<EOF
+    #!/bin/sh
+    if [ $(find /snap/snapd/ -maxdepth 1 -type d 2>/dev/null | wc -l) -gt 2 ]; then
+      snap revert snapd
+    fi
+    EOF
+    chmod +x snapd-cleanup.sh
+    tests.cleanup defer sh -c "$PWD/snapd-cleanup.sh"
+    echo "Ensure we restarted into the snapd snap"
+    "$TESTSTOOLS"/journal-state match-log  'restarting into "/snap/snapd/'
+    echo "Then we should be able to successfully install a snap"
+    snap install hello-world
+    tests.cleanup defer snap remove --purge hello-world
+    echo "Then hello-world.evil should fail due to snap confinement"
+    if hello-world.evil; then
+        echo "hello-world.evil should fail due to snap confinement"
+        exit 1
+    fi
+    # Replicate the tests from tests/main/interfaces-many-core-provided so
+    # we can exercise that apparmor policy is still effective/correct when using
+    # the snapd snap
+    echo "Given a snap is installed"
+    "$TESTSTOOLS"/snaps-state install-local "$CONSUMER_SNAP"
+    tests.cleanup defer snap remove --purge "$CONSUMER_SNAP"
+    # If possible, prepare a session for the test user. On many systems this
+    # will allow running all tests as the unprivileged user. This shields us
+    # from accidentally triggering any additional processes from run in the
+    # session of the root user and stay behind after this test terminates.
+    if tests.session has-session-systemd-and-dbus; then
+        tests.session -u test prepare
+        tests.cleanup defer tests.session -u test restore
+    fi
+    echo "For each core-provided slot"
+    SNAP_MOUNT_DIR="$(os.paths snap-mount-dir)"
+    for plugcmd in "$SNAP_MOUNT_DIR"/bin/"$CONSUMER_SNAP".* ; do
+        # Only connect 1/8 of the interfaces on xenial - the Xenial GA
+        # kernel has a bad memory leak (LP: #1939915) triggered by
+        # reloading apparmor profiles too much and the test fails
+        # (kill-timeout) trying either to remove interfaces or removing the
+        # snap whilst waiting for apparmor_parser to finish, so avoid this
+        # by only touching some of the interfaces overall - there also
+        # seems to be another smaller leak on Bionic etc too so only do
+        # half the interfaces on other systems
+        if os.query is-xenial && [ "$((RANDOM % 8))" != 0 ] || [ "$((RANDOM % 2))" != 0 ]; then
+            echo "skipping plug: $plugcmd"
+            continue
+        fi
+        plugcmd_bn=$(basename "$plugcmd")
+        plug_iface=$(echo "$plugcmd_bn" | tr '.' ':')
+        #shellcheck disable=SC2001
+        slot_iface=$(echo "$plug_iface" | sed "s/$CONSUMER_SNAP//")
+        # we test browser-support two different ways, so account for that
+        if [ "$plug_iface" = "$CONSUMER_SNAP:browser-sandbox" ]; then
+            slot_iface=":browser-support"
+        fi
+        CONNECTED_PATTERN="$slot_iface +.*$CONSUMER_SNAP"
+        DISCONNECTED_PATTERN="$slot_iface +-"
+        if [ "$SNAPCRAFT_BUILD_ENVIRONMENT" = "lxd" ]; then
+            # with lxd snap installed these slot will be connected to the lxd
+            # snap already
+            if [ "$slot_iface" = ":lxd-support" ] || [ "$slot_iface" = ":system-observe" ]; then
+                DISCONNECTED_PATTERN="$slot_iface +lxd"
+            fi
+        fi
+        # Skip any interfaces that core doesn't ship
+        if ! snap interfaces | grep -E -q "$slot_iface +"; then
+            echo "$slot_iface not present, skipping"
+            continue
+        fi
+        echo "When slot $slot_iface is connected"
+        if snap interfaces | grep -E -q "$DISCONNECTED_PATTERN"; then
+            if [ "$SNAPCRAFT_BUILD_ENVIRONMENT" = "lxd" ]; then
+                # we have the lxd snap installed so it provides the lxd slot -
+                # connect to that explicitly
+                if [ "$slot_iface" = ":lxd" ]; then
+                    slot_iface="lxd:lxd"
+                fi
+            fi
+            if [ "$slot_iface" = ":broadcom-asic-control" ] || [ "$slot_iface" = ":firewall-control" ] || [ "$slot_iface" = ":kubernetes-support" ] || [ "$slot_iface" = ":openvswitch-support" ] || [ "$slot_iface" = ":ppp" ]; then
+                # TODO: when the kmod backend no longer fails on missing
+                # modules, we can remove this
+                snap connect "$plug_iface" "$slot_iface" || true
+            else
+                snap connect "$plug_iface" "$slot_iface"
+            fi
+        fi
+        snap interfaces | MATCH "$CONNECTED_PATTERN"
+        echo "Then $plugcmd should succeed"
+        if tests.session has-session-systemd-and-dbus; then
+            tests.session -u test exec "$plugcmd" | MATCH PASS
+        else
+            # If we cannot run the plug command as the test user, in the
+            # relative safety of the user session which gets torn down, then
+            # run the test directly EXCEPT when testing the desktop interface.
+            #
+            # The desktop interface causes, at minimum, XDG document portal to
+            # activate in the root users's session, which is not cleaned up.
+            # Since that interface will only be used in a real session, leaving
+            # it out is acceptable.
+            if [ "$plugcmd" != "${CONSUMER_SNAP}.desktop" ]; then
+                "$plugcmd" | MATCH PASS
+            else
+                echo "skipping $plugcmd on an unsupported system"
+            fi
+        fi
+        echo "Finally disconnect the interface"
+        if snap interfaces | grep -E -q "$CONNECTED_PATTERN"; then
+            if [ "$plug_iface" = "$CONSUMER_SNAP:browser-sandbox" ]; then
+                snap disconnect "$CONSUMER_SNAP:browser-support" "$slot_iface"
+            else
+                snap disconnect "$plug_iface" "$slot_iface"
+            fi
+        fi
+    done
+    # also check that snapd-apparmor service works
+    if ! os.query is-trusty && ! os.query is-xenial; then
+      systemctl status snapd.apparmor.service
+    fi
+    # reboot to ensure snapd.apparmor still works then too
+    if [ "$SPREAD_REBOOT" = "0" ]; then
+        systemctl stop snapd
+        rm -f /var/lib/snapd/system-key
+        echo "Rebooting to re-generate system-key..."
+        REBOOT
+    fi
