tests/main/snapd-snap: Handle incompatibilities in trusty and xenial
shared-memory interface is not supported on trusty and neither can downgrade to
snapd from the archive as in both cases snapd comes from ESM and spread
instances do not have ESM credentials.

Signed-off-by: Alex Murray <alex.murray@canonical.com>

diff --git a/tests/main/snapd-snap/task.yaml b/tests/main/snapd-snap/task.yaml
--- a/tests/main/snapd-snap/task.yaml
+++ b/tests/main/snapd-snap/task.yaml
@@ -270,6 +270,15 @@ execute: |
 
     # Replicate the tests from tests/main/interfaces-many-core-provided so
     # we can exercise the vendored appamor_parser etc within the snapd snap
+
+    # We remove the shared-memory plug and interface in trusty because it fails with the
+    # following error since adding private /dev/shm support to shared-memory interface:
+    # shared-memory plug with "private: true" cannot be connected if "/dev/shm" is a symlink)
+    if os.query is-trusty; then
+        cp -r "$TESTSLIB/snaps/$CONSUMER_SNAP" .
+        sed -e '/shared-memory:/,+2d' -i $CONSUMER_SNAP/meta/snap.yaml
+    fi
+
     echo "Given a snap is installed"
     "$TESTSTOOLS"/snaps-state install-local "$CONSUMER_SNAP"
     tests.cleanup defer snap remove --purge "$CONSUMER_SNAP"
@@ -382,14 +391,18 @@ execute: |
         # downgrade the snapd deb from the distro package to test that we can
         # still handle the generated apparmor profiles etc from the snapd snap
         echo "Downgrading snapd to distro packaged version..."
-        apt install -y --allow-downgrades "snapd/$(lsb_release -sc)"
-        tests.cleanup defer apt install -y "$PROJECT_PATH/../"snapd_1337.*_amd64.deb
-
-        # check snapd.apparmor is still working after downgrade
+        # this fails on ubuntu-16.04 and 14.04 since the distro installed
+        # version of snapd comes from esm.ubuntu.com but the spread instances do
+        # not have credentials for esm.ubuntu.com
         if ! os.query is-trusty && ! os.query is-xenial; then
-          systemctl status snapd.apparmor.service
-        fi
+            apt install -y --allow-downgrades "snapd/$(lsb_release -sc)"
+            tests.cleanup defer apt install -y "$PROJECT_PATH/../"snapd_1337.*_amd64.deb
 
-        echo "Rebooting to re-generate system-key..."
-        REBOOT
+            # check snapd.apparmor is still working after downgrade
+            if ! os.query is-trusty && ! os.query is-xenial; then
+                systemctl status snapd.apparmor.service
+            fi
+            echo "Rebooting to re-generate system-key..."
+            REBOOT
+        fi
     fi
