tests/core/snapd-failover: enable for UC16, join with snapd-failover16 test
Join both of these tests together as the logic for the snapd-failover test is
rather complicated and we don't want to maintain that complexity in multiple
places.

Signed-off-by: Ian Johnson <ian.johnson@canonical.com>

diff --git a/tests/core/snapd-failover/task.yaml b/tests/core/snapd-failover/task.yaml
--- a/tests/core/snapd-failover/task.yaml
+++ b/tests/core/snapd-failover/task.yaml
@@ -2,40 +2,77 @@ summary: Check that snapd failure handling works
 
 # TODO:UC20: enable for UC20, currently snapd.failure.service does not work on
 #            UC20, it currently isn't activated for some reason
-# UC16 still uses the core snap rather than the snapd snap, so disable this test
-# for UC16
-systems: [-ubuntu-core-20-*, -ubuntu-core-16-*]
+systems: [-ubuntu-core-20-*]
 
 debug: |
+    # shellcheck source=tests/lib/systems.sh
+    . "$TESTSLIB/systems.sh"
     # dump failure data
     journalctl -u snapd.failure.service
     journalctl -u snapd.socket || true
-    ls -l /snap/snapd/
+    if is_core16_system; then
+        ls -l /snap/core/
+    fi
+
+    # the snapd snap could accidentally still be around even on UC16
+    ls -l /snap/snapd/ || true
 
 execute: |
     # shellcheck source=tests/lib/journalctl.sh
     . "$TESTSLIB/journalctl.sh"
 
+    # shellcheck source=tests/lib/systems.sh
+    . "$TESTSLIB/systems.sh"
+
     echo "Testing failover handling of the snapd snap"
-    current=$(readlink /snap/snapd/current)
-    SNAPD_SNAP=$(ls /var/lib/snapd/snaps/snapd_"$current".snap)
 
     # for debugging
     snap list --all
 
-    echo "Verify that a random signal does not trigger the failure handling"
-    echo "and snapd is just restarted"
-    systemctl kill --signal=SIGSEGV snapd.service
-    systemctl is-active snapd.failure.service | MATCH inactive
-    echo "Snap list is working still"
-    snap list | MATCH "^snapd .* $current .*"
-
-    # get the number of times that snapd.failure was started
+    # get the number of times that snapd.failure was started before we do 
+    # anything
     started_before="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
+
+    # only test that random signals don't trigger snapd-failure on UC18+, 
+    # because snapd.failure does not exist on UC16 by default so there's nothing
+    # to test with this on UC16
+    if ! is_core16_system; then
+        current=$(readlink /snap/snapd/current)
+
+        echo "Verify that a random signal does not trigger the failure handling"
+        echo "and snapd is just restarted"
+        systemctl kill --signal=SIGSEGV snapd.service
+
+        started_after_rand_sig="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
+
+        if [ "$started_after_rand_sig" -gt "$started_before" ] ; then
+            echo "snapd.failure inadvertently started with a random signal!"
+            exit 1
+        fi
+
+        echo "Snap list is working still"
+        snap list | MATCH "^snapd .* $current .*"
+
+        SNAPD_SNAP=$(ls /var/lib/snapd/snaps/snapd_"$current".snap)
+    else
+        # this will be used for uc16 tests a bit later
+        current=$(readlink /snap/core/current)
+
+        snap download snapd --basename=snapd
+        SNAPD_SNAP=$(pwd)/snapd.snap
+    fi
+
 
     echo "Break snapd"
     unsquashfs -d ./snapd-broken "$SNAPD_SNAP"
     echo "" > ./snapd-broken/usr/lib/snapd/snapd
+
+    if is_core16_system; then
+        # pick up snap-failure from the current core snap as that's where the 
+        # updated code under test is located
+        cp -a /usr/lib/snapd/snap-failure ./snapd-broken/usr/lib/snapd/snap-failure
+    fi
+
     (cd ./snapd-broken && snap pack .)
     echo "Now install the broken snapd"
     if snap install --dangerous ./snapd-broken/snapd_*.snap; then
@@ -56,11 +93,32 @@ execute: |
     # just because snapd.failure.service is active doesn't mean that we are 
     # fully ready; we should wait until the snap command shows up again
     echo "And verify that snap commands still work and snapd is reverted"
-    retry-tool -n 60 --wait 1 bash -c 'snap list | MATCH "^snapd .* $current .*"'
+    echo "Verify that we were rolled back to the previous snapd"
+    if is_core16_system; then
+        retry-tool -n 30 --wait 1 bash -c 'snap list | MATCH "^core .* $current .*"'
+    else
+        retry-tool -n 30 --wait 1 bash -c 'snap list | MATCH "^snapd .* $current .*"'
+    fi
 
     echo "Verify we got the expected error message"
     snap change --last=install|MATCH "there was a snapd rollback across the restart"
 
     echo "restart snapd and ensure we can still talk to it"
     systemctl restart snapd.socket snapd.service
-    snap list | MATCH "^snapd .* $current .*"
+
+    if is_core16_system; then
+        # on UC16 we should have rolled back to the core snap, and there should
+        # be no snapd snap left installed
+        snap list | MATCH "^core .* $current .*"
+
+        echo "No snapd snap is installed"
+        not snap list snapd
+
+        test ! -e /etc/systemd/system/snapd.service
+        test ! -e /etc/systemd/system/usr-lib-snapd.mount
+        test ! -e /snap/snapd/x1
+    else
+        # on UC18+ we should still have the snapd snap and it should have the 
+        # revision we had before the broken one was installed
+        snap list | MATCH "^snapd .* $current .*"
+    fi
