tests/snapd-failover: install snapd on uc16 in prepare section
This simplifies the rest of the test significantly, and also lets us isolate the
case of going from core -> snapd to a different test, which will be less
complicated.

This does introduce a bit of tricky setup code, where we repack the currently
installed core snap into the snapd snap, using the current set of files from the
snapd snap on the edge channel, but there isn't currently a better way to do
this other than perhaps hard-coding the full list of snapd snap files somewhere.

Signed-off-by: Ian Johnson <ian.johnson@canonical.com>

diff --git a/tests/core/snapd-failover/task.yaml b/tests/core/snapd-failover/task.yaml
--- a/tests/core/snapd-failover/task.yaml
+++ b/tests/core/snapd-failover/task.yaml
@@ -4,13 +4,58 @@ summary: Check that snapd failure handling works
 #            UC20, it currently isn't activated for some reason
 systems: [-ubuntu-core-20-*]
 
+prepare: |
+    # shellcheck source=tests/lib/systems.sh
+    . "$TESTSLIB/systems.sh"
+
+    # on UC16, we should transition to using the snapd snap before running the 
+    # test because it by default uses the core snap
+    # there is a different test for the transition between the core snap and the
+    # snapd snap
+    if is_core16_system; then
+        # FIXME: maybe build the snapd snap from the deb in prepare_ubuntu_core
+        # and include it somewhere in the image so we don't need to do this hack
+        # here?
+
+        # get the snap.yaml and a list of all the snapd snap files using edge
+        # NOTE: this may break if a spread run adds files to the snapd snap that
+        # don't exist in the snapd snap on edge and those files are necessary
+        # for snapd to run or revert, etc.
+        snap download snapd --basename=snapd-upstream --edge
+        unsquashfs -d ./snapd-upstream snapd-upstream.snap
+        ( cd snapd-upstream; find . \( -type l -o -type f \) | cut -c3- > ../files.txt )
+        
+        current=$(readlink /snap/core/current)
+        CORE_SNAP=$(ls /var/lib/snapd/snaps/core_"$current".snap)
+
+        # only unpack files from the core snap that are in the snapd snap - this
+        # is kosher because the set of files in the core snap is a superset of 
+        # all the files in the snapd snap
+        unsquashfs -d ./snapd-local "$CORE_SNAP" $(cat files.txt)
+        
+        # replace snap.yaml from the core snap with the snapd snap
+        cp snapd-upstream/meta/snap.yaml snapd-local/meta/snap.yaml
+
+        # pack and install
+        snap pack snapd-local --filename=snapd-from-core.snap
+        snap install --dangerous $PWD/snapd-from-core.snap
+
+        # cleanup the snaps we downloaded and built
+        rm -rf snapd-local snapd-upstream* files.txt
+    fi
+    # ensure we are in snapd snap world
+    snap list snapd
+    ls -l /snap/snapd/
+
 debug: |
     # shellcheck source=tests/lib/systems.sh
     . "$TESTSLIB/systems.sh"
+
     # dump failure data
     journalctl -u snapd.failure.service
     journalctl -u snapd.socket || true
     if is_core16_system; then
+        # might be useful to know what's up with the core snap too on uc16
         ls -l /snap/core/
     fi
     ls -l /snap/snapd/
@@ -18,8 +63,7 @@ debug: |
     cat /etc/systemd/system/snapd.service
     cat /etc/systemd/system/usr-lib-snapd.mount
     /snap/snapd/x1/usr/bin/snap debug state /var/lib/snapd/state.json || true
-    /snap/snapd/x1/usr/bin/snap debug state --change="$(snap debug state /var/lib/snapd/state.json|tail -n1|awk '{print $1}')" /var/lib/snapd/state.json || true
-
+    /snap/snapd/x1/usr/bin/snap debug state --change="$(/snap/snapd/x1/usr/bin/snap debug state /var/lib/snapd/state.json|tail -n1|awk '{print $1}')" /var/lib/snapd/state.json || true
 
 execute: |
     # shellcheck source=tests/lib/journalctl.sh
@@ -37,46 +81,28 @@ execute: |
     # anything
     started_before="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
 
-    # only test that random signals don't trigger snapd-failure on UC18+, 
-    # because snapd.failure does not exist on UC16 by default so there's nothing
-    # to test with this on UC16
-    if ! is_core16_system; then
-        current=$(readlink /snap/snapd/current)
+    # test that random signals don't trigger snapd-failure
+    current=$(readlink /snap/snapd/current)
 
-        echo "Verify that a random signal does not trigger the failure handling"
-        echo "and snapd is just restarted"
-        systemctl kill --signal=SIGSEGV snapd.service
+    echo "Verify that a random signal does not trigger the failure handling"
+    echo "and snapd is just restarted"
+    systemctl kill --signal=SIGSEGV snapd.service
 
-        started_after_rand_sig="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
+    started_after_rand_sig="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
 
-        if [ "$started_after_rand_sig" -gt "$started_before" ] ; then
-            echo "snapd.failure inadvertently started with a random signal!"
-            exit 1
-        fi
-
-        echo "Snap list is working still"
-        snap list | MATCH "^snapd .* $current .*"
-
-        SNAPD_SNAP=$(ls /var/lib/snapd/snaps/snapd_"$current".snap)
-    else
-        # this will be used for uc16 tests a bit later
-        current=$(readlink /snap/core/current)
-
-        snap download snapd --basename=snapd
-        SNAPD_SNAP=$(pwd)/snapd.snap
+    if [ "$started_after_rand_sig" -gt "$started_before" ] ; then
+        echo "snapd.failure inadvertently started with a random signal!"
+        exit 1
     fi
 
+    echo "Snap list is working still"
+    snap list | MATCH "^snapd .* $current .*"
+
+    SNAPD_SNAP=$(ls /var/lib/snapd/snaps/snapd_"$current".snap)
 
     echo "Break snapd"
     unsquashfs -d ./snapd-broken "$SNAPD_SNAP"
     echo "" > ./snapd-broken/usr/lib/snapd/snapd
-
-    if is_core16_system; then
-        # pick up snap-failure from the current core snap as that's where the 
-        # updated code under test is located
-        cp -a /usr/lib/snapd/snap-failure ./snapd-broken/usr/lib/snapd/snap-failure
-    fi
-
     (cd ./snapd-broken && snap pack .)
     echo "Now install the broken snapd"
     if snap install --dangerous ./snapd-broken/snapd_*.snap; then
@@ -97,12 +123,7 @@ execute: |
     # just because snapd.failure.service is active doesn't mean that we are 
     # fully ready; we should wait until the snap command shows up again
     echo "And verify that snap commands still work and snapd is reverted"
-    echo "Verify that we were rolled back to the previous snapd"
-    if is_core16_system; then
-        retry-tool -n 30 --wait 1 bash -c 'snap list | MATCH "^core .* $current .*"'
-    else
-        retry-tool -n 30 --wait 1 bash -c 'snap list | MATCH "^snapd .* $current .*"'
-    fi
+    retry-tool -n 30 --wait 1 bash -c 'snap list | MATCH "^snapd .* $current .*"'
 
     echo "Verify we got the expected error message"
     snap change --last=install|MATCH "there was a snapd rollback across the restart"
@@ -110,19 +131,6 @@ execute: |
     echo "restart snapd and ensure we can still talk to it"
     systemctl restart snapd.socket snapd.service
 
-    if is_core16_system; then
-        # on UC16 we should have rolled back to the core snap, and there should
-        # be no snapd snap left installed
-        snap list | MATCH "^core .* $current .*"
-
-        echo "No snapd snap is installed"
-        not snap list snapd
-
-        test ! -e /etc/systemd/system/snapd.service
-        test ! -e /etc/systemd/system/usr-lib-snapd.mount
-        test ! -e /snap/snapd/x1
-    else
-        # on UC18+ we should still have the snapd snap and it should have the 
-        # revision we had before the broken one was installed
-        snap list | MATCH "^snapd .* $current .*"
-    fi
+    # we should still have the snapd snap and it should have the revision we had
+    # before the broken one was installed
+    snap list | MATCH "^snapd .* $current .*"
