snapd.failure.service.in: don't set RemainAfterExit
This specifically will cause snapd.failure to kick in if 2 broken snapd's are
installed without a reboot or explicitly stopping the snapd.failure service so
that on the second time, snapd.failure will actually be started.

Because of this, it's no longer sufficient to check to see if the snapd.failure
service is active after a broken snapd is installed, we have to look at the logs
to see that it was actually activated/started more times after the broken snapd
was installed than before.

Also since it's always basically inactive, remove the restore section since
there's no point to stopping it now as it will always be inactive essentially.

Signed-off-by: Ian Johnson <ian.johnson@canonical.com>

diff --git a/tests/core/snapd-failover/task.yaml b/tests/core/snapd-failover/task.yaml
--- a/tests/core/snapd-failover/task.yaml
+++ b/tests/core/snapd-failover/task.yaml
@@ -12,13 +12,10 @@ debug: |
     journalctl -u snapd.socket || true
     ls -l /snap/snapd/
 
-restore: |
-    # Stop snapd.failure.service in case it is active
-    if systemctl is-active snapd.failure.service | MATCH active; then
-        systemctl stop snapd.failure.service
-    fi
-
 execute: |
+    # shellcheck source=tests/lib/journalctl.sh
+    . "$TESTSLIB/journalctl.sh"
+
     echo "Testing failover handling of the snapd snap"
     current=$(readlink /snap/snapd/current)
     SNAPD_SNAP=$(ls /var/lib/snapd/snaps/snapd_"$current".snap)
@@ -33,6 +30,9 @@ execute: |
     echo "Snap list is working still"
     snap list | MATCH "^snapd .* $current .*"
 
+    # get the number of times that snapd.failure was started
+    started_before="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
+
     echo "Break snapd"
     unsquashfs -d ./snapd-broken "$SNAPD_SNAP"
     echo "" > ./snapd-broken/usr/lib/snapd/snapd
@@ -43,11 +43,19 @@ execute: |
         exit 1
     fi
 
-    echo "And verify that snap commands still work and snapd is reverted"
-    retry-tool -n 30 --wait 5 systemctl is-active snapd.failure.service
+    echo "Verify that snapd.failure was activated when we tried to install a broken snapd"
+    for _ in $(seq 60); do
+        # get the number of times that snapd.failure was started
+        started_after="$(get_journalctl_log -u snapd.failure | grep -c 'Started Failure handling of the snapd snap.' || true)"
+        if [ "$started_after" -gt "$started_before" ] ; then
+            break
+        fi
+        sleep 1
+    done
 
     # just because snapd.failure.service is active doesn't mean that we are 
     # fully ready; we should wait until the snap command shows up again
+    echo "And verify that snap commands still work and snapd is reverted"
     retry-tool -n 60 --wait 1 bash -c 'snap list | MATCH "^snapd .* $current .*"'
 
     echo "Verify we got the expected error message"
