tests/core/snapd-failover: encode systemd unit failure behavior in the test
When running the test on UC6, verify that snapd.failure.service was indeed
triggered in the simplest scenario.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

diff --git a/tests/core/snapd-failover/task.yaml b/tests/core/snapd-failover/task.yaml
--- a/tests/core/snapd-failover/task.yaml
+++ b/tests/core/snapd-failover/task.yaml
@@ -83,21 +83,36 @@ execute: |
             kill -9 $(cat /sys/fs/cgroup/system.slice/snapd.service/cgroup.procs)
         fi
 
-        # TODO this check is incorrect and is essentially racing with systemd
-        # which could try to active the failure service, as we're essentially
-        # testing that an event does not happen
         sleep 5
         started_after_rand_sig="$("$TESTSTOOLS"/journal-state get-log -u snapd.failure | grep -c 'Starting Failure handling of the snapd snap.' || true)"
 
-        if [ "$started_after_rand_sig" -gt "$started_before" ] ; then
-            echo "snapd.failure inadvertently started with a random signal!"
-            exit 1
+        if os.query is-core16; then
+            # on UC16 systemd triggers OnFailure dependencies and snapd gets
+            # started by snap-failure
+            if [ "$started_after_rand_sig" -eq "$started_before" ] ; then
+                echo "snapd.failure did not start snapd"
+                exit 1
+            fi
+
+            # make sure that snapd is being executed within the cgroup assigned to snapd.service
+            echo "Verify behavior on UC16, where snapd process runs under snapd.failure.service unit"
+            # shellcheck disable=SC2046,SC2002
+            cat /proc/$(pidof snapd)/cgroup | MATCH /snapd.failure.service
+        else
+            # TODO this check is incorrect and is essentially racing with systemd
+            # which could try to active the failure service, as we're essentially
+            # testing that an event does not happen
+            if [ "$started_after_rand_sig" -gt "$started_before" ] ; then
+                echo "snapd.failure inadvertently started with a random signal!"
+                exit 1
+            fi
+
+            # make sure that snapd is being executed within the cgroup assigned to snapd.service
+            echo "Ensure snapd is still running as part of the snapd.service unit"
+            # shellcheck disable=SC2046,SC2002
+            cat /proc/$(pidof snapd)/cgroup | MATCH /snapd.service
         fi
 
-        # make sure that snapd is being executed within the cgroup assigned to snapd.service
-        echo "Ensure snapd is still running as part of the snapd.service unit"
-        # shellcheck disable=SC2046,SC2002
-        cat /proc/$(pidof snapd)/cgroup | MATCH /snapd.service
 
         echo "Snap list is working still"
         snap list | MATCH "^snapd .* $current .*"
