Fix for issues when snad service is canceled and cleanup for snaps on trusty
Three issues are fixed/improved with change.

The first is how the snapd service is stopped. To avoid the error "Job
canceled" when the snapd service is stopped but it is in "activating"
state. To deal with that, the solution is to wait until the state change
to active, to stop it.

The second is how the services are stopped in the postrm scritps. The
idea of this change is to avoid call "systemctl stop service" many times
when the services take some time to be stopped. This was causing some
services like the lxd or neutron are stopped many times.

The third is that the postrm script will fail in case the final cleanup
is not completed properly.

The last once is a change in the install-snaps test to remove the snap
as part of the test and check the snap is properly removed.

diff --git a/packaging/ubuntu-16.04/snapd.postrm b/packaging/ubuntu-16.04/snapd.postrm
--- a/packaging/ubuntu-16.04/snapd.postrm
+++ b/packaging/ubuntu-16.04/snapd.postrm
@@ -4,13 +4,19 @@ set -e
 
 systemctl_stop() {
     unit="$1"
-    for i in $(seq 10); do
+    if ! systemctl is-active -q "$unit"; then
+        echo "$unit is stopped."
+        return
+    fi
+    echo "Stoping $unit [attempt $i]"
+    systemctl stop -q "$unit" || true
+
+    for i in $(seq 20); do
+        echo "Waiting until unit $unit is stopped [attempt $i]"
         if ! systemctl is-active -q "$unit"; then
             echo "$unit is stopped."
-            break
+            return
         fi
-        echo "Stoping $unit [attempt $i]"
-        systemctl stop -q "$unit" || true
         sleep .1
     done
 }
@@ -79,6 +85,10 @@ if [ "$1" = "purge" ]; then
     for d in "/snap/bin" "/snap" "/var/snap"; do
         if [ -d "$d" ]; then
             rmdir --ignore-fail-on-non-empty $d
+        fi
+        if [ -d "$d" ]; then
+            echo "Failed cleaning dir $d"
+            exit 1
         fi
     done
 
