packaging: bring down the delta between 14.04 and 16.04.
This is rather aggressive, and needs further testing before we're sure
it's the way to go, but one can hope.

diff --git a/packaging/ubuntu-16.04/snapd.postrm b/packaging/ubuntu-16.04/snapd.postrm
--- a/packaging/ubuntu-16.04/snapd.postrm
+++ b/packaging/ubuntu-16.04/snapd.postrm
@@ -12,14 +12,17 @@ systemctl_stop() {
 
 if [ "$1" = "purge" ]; then
     # undo any bind mount to /snap that resulted from LP:#1668659
+    # (that bug can't happen in trusty -- and doing this would mess up snap.mount.service there)
     if grep -q "/snap /snap" /proc/self/mountinfo; then
         umount -l /snap || true
     fi
 
-    mounts=$(systemctl list-unit-files --full | grep '^snap[-.].*\.mount' | cut -f1 -d ' ')
-    services=$(systemctl list-unit-files --full | grep '^snap[-.].*\.service' | cut -f1 -d ' ')
+    units=$(systemctl list-unit-files --full | grep '^snap[-.]' | cut -f1 -d ' ' | grep -vF snap.mount.service)
+    mounts=$(echo "$units" | grep '^snap[-.].*\.mount$')
+    services=$(echo "$units" | grep '^snap[-.].*\.service$')
+
     for unit in $services $mounts; do
-        # ensure its really a snapp mount unit or systemd unit
+        # ensure its really a snap mount unit or systemd unit
         if ! grep -q 'What=/var/lib/snapd/snaps/' "/etc/systemd/system/$unit" && ! grep -q 'X-Snappy=yes' "/etc/systemd/system/$unit"; then
             echo "Skipping non-snapd systemd unit $unit"
             continue
@@ -43,7 +46,8 @@ if [ "$1" = "purge" ]; then
             rm -f "/snap/bin/$snap"
             rm -f "/snap/bin/$snap".*
             # snap mount dir
-            umount -l "/snap/$snap/$rev" 2> /dev/null || true
+            # we pass -d (clean up loopback devices) for trusty compatibility
+            umount -d -l "/snap/$snap/$rev" 2> /dev/null || true
             rm -rf "/snap/$snap/$rev"
             rm -f "/snap/$snap/current"
             # snap data dir
@@ -53,7 +57,7 @@ if [ "$1" = "purge" ]; then
             # opportunistic remove (may fail if there are still revisions left
             for d in "/snap/$snap" "/var/snap/$snap"; do
                 if [ -d "$d" ]; then
-                    rmdir --ignore-fail-on-non-empty "$d"
+                    rmdir --ignore-fail-on-non-empty "$d" || true
                 fi
             done
         fi
