tests: make sure keyboards cannot be accessed via device-buttons
This test makes sure that regardless if the device-buttons interface
is connected for a snap it cannot access the keyboard devices.

diff --git a/tests/main/security-dev-input-event-denied/task.yaml b/tests/main/security-dev-input-event-denied/task.yaml
--- a/tests/main/security-dev-input-event-denied/task.yaml
+++ b/tests/main/security-dev-input-event-denied/task.yaml
@@ -32,6 +32,8 @@ execute: |
         exit 0
     fi
 
+    # 1. Joystick
+
     echo "The joystick plug is not connected by default"
     snap interfaces -i joystick | MATCH '\- +test-snapd-event:joystick'
 
@@ -62,4 +64,38 @@ execute: |
     # device cgroup is 'Operation not permitted' which is expected when the
     # joystick interface is connected since a keyboard shouldn't be added to
     # the device cgroup.
+    MATCH "Operation not permitted" < call.error
+
+    # 2. Device Buttons
+
+    echo "The device-buttons plug is not connected by default"
+    snap interfaces -i device-buttons | MATCH '\- +test-snapd-event:device-buttons'
+
+    if [ "$(snap debug confinement)" != "strict" ]; then
+        exit 0
+    fi
+
+    echo "Then the snap is not able to access an evdev keyboard"
+    if test-snapd-event "-event-kbd" 2>"${PWD}"/call.error; then
+        echo "Expected permission error calling evtest with disconnected plug"
+        exit 1
+    fi
+    # AppArmor is 'Permission denied' which is expected with default policy
+    MATCH "Permission denied" < call.error
+
+    echo "When the device-buttons plug is connected"
+    snap connect test-snapd-event:device-buttons
+    udevadm settle
+
+    # Note, '-event-kbd' devices aren't device buttons (those are
+    # -gpio-keys-even (evdev event*) and therefore shouldn't be added to
+    # the device cgroup when the device-buttons interface is plugged.
+    echo "Then the snap is still not able to access an evdev keyboard"
+    if test-snapd-event "-event-kbd" 2>"${PWD}"/call.error; then
+        echo "Expected permission error calling evtest with connected device-buttons plug"
+        exit 1
+    fi
+    # device cgroup is 'Operation not permitted' which is expected when the
+    # device-buttons interface is connected since a keyboard shouldn't be added
+    # to the device cgroup.
     MATCH "Operation not permitted" < call.error
