tests/nested/manual: fix other cloud-init test checks too
These tests suffered from the same problem as the tests for the cloud-init
vulnerability, so fix them too.

Signed-off-by: Ian Johnson <ian.johnson@canonical.com>

diff --git a/tests/nested/manual/grade-signed-cloud-init-testkeys/task.yaml b/tests/nested/manual/grade-signed-cloud-init-testkeys/task.yaml
--- a/tests/nested/manual/grade-signed-cloud-init-testkeys/task.yaml
+++ b/tests/nested/manual/grade-signed-cloud-init-testkeys/task.yaml
@@ -140,12 +140,19 @@ execute: |
   # of this test
 
   echo "Waiting for snapd to react to cloud-init"
+  seen=0
   for i in $(seq 60); do
-    if tests.nested exec "journalctl --no-pager -u snapd" | MATCH "Cloud-init reported"; then
-        break
-    fi
-    sleep 1
+      if tests.nested exec "sudo journalctl --no-pager -u snapd" | MATCH "cloud-init reported"; then
+          seen=1
+          break
+      fi
+      sleep 1
   done
+
+  if [ "$seen" = "0" ]; then
+      echo "snapd did not restrict cloud-init, test failed"
+      exit 1
+  fi
 
   echo "Ensuring that cloud-init got disabled after running"
   tests.nested exec "cloud-init status" | MATCH "status: disabled"
