tests/lib/tools/tests.invariant: look for unexpected snap cgroups (#15145)
* tests/lib/tools/tests.invariant: look for unexpected snap cgroups

Snap cgroups should be cleaned up as a result of removing the snaps
during restore.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/lib/tools/tests.invariant: skip snap.mount

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests: remove test snaps and quotas

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/lib/tools/cleanup-state: remove freezer and device cgroups in restore

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* cmd, packaging: systemctl kill remaining processes during removal

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/services-stop-mode-sigkill: move testing os sigterm stop-modes into separate snap

Split out testing of sigterm{,-all} stop modes into a separate snap. The
sigterm stop mode has a tendency to leak processes, which is a direct
effect of the requested KillMode=process and so requires additional
cleanup. However, the original snap test-snapd-service is used in a
number of tests, so in order to avoid additional changes for cleanup
needing to be added to each of those tests, the patchs splits out
relevant parts of the original snap into a new one which is used only in
a specific test targeting the stop-mode feature.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main: remove snaps with user services

Make sure to remove snaps with user services, as those may have been
started in user sessions that are not directly related to the tests and
removal gives us a chance to stop them.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/snap-mgmt: add a workaround for stopping user services

User services cannot be stopped during purge, so work around that by
stopping the processes manually.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/snap-quota: clean up leaking systemd slices

On Ubuntu 18.04 and 20.04, despite removing the quota groups and snaps,
systemd slices with resource configuration were still leaking from the
tests. Clean them up manually.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/services-stop-mode-sigkill: fix sunchronization between test and snap service

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/lib/tools/cleanup-state: clean up leftover user services

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/snap-mgmt: workaround kernel compatibility

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/lib/tools/tests.invariant: skip socket units, leave TODO

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/postrm-purge: snap user service slices do not necessarily exist in all setups

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main: cleanup cgroups on old Ubuntu releases in lxd/docker/microk8s tests

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests: cleanup cgroups on 16.04 and 18.04

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/postrm-purge: drop incorrect check

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/lib/tools/cleanup-state: fix indentation

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/canonical-livepatch: cleanup remaining cgroups

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

---------

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

diff --git a/tests/main/interfaces-microstack-support/task.yaml b/tests/main/interfaces-microstack-support/task.yaml
--- a/tests/main/interfaces-microstack-support/task.yaml
+++ b/tests/main/interfaces-microstack-support/task.yaml
@@ -10,6 +10,15 @@ environment:
 prepare: |
     "$TESTSTOOLS"/snaps-state install-local test-snapd-sh
 
+restore: |
+    snap remove --purge test-snapd-sh
+    if os.query is-xenial || os.query is-bionic; then
+        # old system is not doing cleanups
+        find /sys/fs/cgroup/ -type d -name "snap.*" -prune | while read -r svc; do
+             rmdir "$svc" || true
+        done
+    fi
+
 execute: |
     echo "When the interface is connected"
     snap connect "$SNAP_NAME":microstack-support
diff --git a/tests/main/services-stop-mode-sigkill/task.yaml b/tests/main/services-stop-mode-sigkill/task.yaml
--- a/tests/main/services-stop-mode-sigkill/task.yaml
+++ b/tests/main/services-stop-mode-sigkill/task.yaml
@@ -11,9 +11,17 @@ backends: [-autopkgtest]
 kill-timeout: 10m
 
 restore: |
+    snap stop test-snapd-service-sigterm
+    # ensure thaere are no runaway processes
+    refresh_modes="sigterm sigterm-all"
+    for s in $refresh_modes; do
+        systemctl kill "snap.test-snapd-service-sigterm.test-snapd-${s}-service"
+    done
     # remove to ensure all services are stopped
-    snap remove --purge test-snapd-service || true
-    pkill sleep || true
+    snap remove --purge test-snapd-service-sigterm
+    # clean up any remaining cgroups, if anything leaks here, the invariant
+    # checks will catch it
+    find /sys/fs/cgroup/ -type d -name 'snap.*.service' -prune -exec rmdir \{\} \; || true
 
 debug: |
     ps afx
@@ -23,24 +31,24 @@ execute: |
     pkill sleep || true
 
     echo "When the service snap is installed"
-    "$TESTSTOOLS"/snaps-state install-local test-snapd-service
+    "$TESTSTOOLS"/snaps-state install-local test-snapd-service-sigterm
     # Because we cannot use daemon: notify easily yet just wait for a "ready"
     # file to show up.  The file is removed when the service is stopped. This
     # pattern repeats around the test without additional comments.
-    retry -n 20 --wait 1 sh -c 'test -f /var/snap/test-snapd-service/common/ready'
-
-    refresh_modes="sigterm sigterm-all"
-    for s in $refresh_modes; do
-        systemctl show -p ActiveState "snap.test-snapd-service.test-snapd-${s}-service" | MATCH "ActiveState=active"
-    done
+    retry -n 20 --wait 1 sh -c 'test -f /var/snap/test-snapd-service-sigterm/common/ready'
+    retry -n 20 --wait 1 sh -c 'test -f /var/snap/test-snapd-service-sigterm/common/ready-all'
 
     echo "we expect two sleep processes (children) from the two sigterm services"
     n=$(pgrep -c -f 3133731337)
     [ "$n" = "2" ]
 
+    rm -f /var/snap/test-snapd-service-sigterm/common/ready
+    rm -f /var/snap/test-snapd-service-sigterm/common/ready-all
+
     echo "When it is re-installed one process uses sigterm, the other sigterm-all"
-    "$TESTSTOOLS"/snaps-state install-local test-snapd-service
-    retry -n 20 --wait 1 sh -c 'test -f /var/snap/test-snapd-service/common/ready'
+    "$TESTSTOOLS"/snaps-state install-local test-snapd-service-sigterm
+    retry -n 20 --wait 1 sh -c 'test -f /var/snap/test-snapd-service-sigterm/common/ready'
+    retry -n 20 --wait 1 sh -c 'test -f /var/snap/test-snapd-service-sigterm/common/ready-all'
 
     echo "After reinstall the sigterm-all service and all children got killed"
     echo "but the sigterm service only got a kill for the main process "
