t/m/snapctl-async: fix spread test

diff --git a/tests/main/snapctl-async/task.yaml b/tests/main/snapctl-async/task.yaml
--- a/tests/main/snapctl-async/task.yaml
+++ b/tests/main/snapctl-async/task.yaml
@@ -45,12 +45,13 @@ execute: |
 
   echo "Wait for change to complete"
   while true; do
-    snap run --shell test-snapctl-async.app -c "snapctl is-ready $CHANGE_ID" || EXIT_CODE=$?
-    if [ "$EXIT_CODE" -eq 0 ]; then
+    exit_code=0
+    snap run --shell test-snapctl-async.app -c "snapctl is-ready $CHANGE_ID" || exit_code=$?
+    if [ "$exit_code" -eq 0 ]; then
       echo "Change $CHANGE_ID is ready."
       break
-    elif [ "$EXIT_CODE" -ge 2 ]; then
-      echo "Change $CHANGE_ID completed with error (exit $EXIT_CODE)"
+    elif [ "$exit_code" -ge 2 ]; then
+      echo "Change $CHANGE_ID completed with error (exit $exit_code)"
       return 1
     fi
   done
