Use retry instead of wait for file

diff --git a/tests/lib/tools/fs-state b/tests/lib/tools/fs-state
--- a/tests/lib/tools/fs-state
+++ b/tests/lib/tools/fs-state
@@ -1,27 +1,10 @@
 #!/bin/bash
 
 show_help() {
-    echo "usage: fs-state wait-for-file [filename] [iterations] [sleep-time]"
     echo "usage: fs-state mock-dir [dirname]"
     echo "usage: fs-state restore-dir [dirname]"
     echo "usage: fs-state mock-file [filename]"
     echo "usage: fs-state restore-file [filename]"
-}
-
-wait_for_file() {
-    local file="$1"
-    local iters="$2"
-    local sleep_time="$3"
-
-    for _ in $(seq "$iters"); do
-        if [ -e "$file" ]; then
-            echo "File exists: $file"
-            return 0
-        fi
-        sleep "$sleep_time"
-    done
-    echo "File does not exist: $file"
-    return 1
 }
 
 _mock_dir() {
@@ -61,15 +44,15 @@ _mock_file() {
     local file="$1"
     if ! [ -e "$file" ]; then
         echo "Creating file: $file"
-        echo "content for $file" > "$file"
-        echo "content for fake $file" > "$file.fake"
+        echo "The file is a mock file used by fs-state." > "$file"
+        echo "The .fake file is a marker file used by fs-state." > "$file.fake"
     fi
 }
 
 mock_file() {
     local file="$1"
     if [ -e "$file" ]; then
-        echo "Backuping file: $file"
+        echo "fs-state: backing up original file: $file"
         mv "$file" "$file.back"
     fi
     # ensure the parent dir is available
@@ -81,12 +64,12 @@ mock_file() {
 
 restore_file() {
     local file="$1"
-    echo "Cleaning file: $file"
+    echo "fs-state: restoring mocked file: $file"
     if [ -e "$file.fake" ]; then
         rm -f "$file"
         rm -f "$file.fake"
     else
-        echo "The file $file is not mocked"
+        echo "fs-state: cannot restore file non-mocked file: $file" >&2
         exit 1
     fi
     if [ -e "$file.back" ]; then
