tests/nested/manual/core20-fde-dbx: add scenario with a full update cycle followed by reboot
Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

diff --git a/tests/nested/manual/core20-fde-dbx/task.yaml b/tests/nested/manual/core20-fde-dbx/task.yaml
--- a/tests/nested/manual/core20-fde-dbx/task.yaml
+++ b/tests/nested/manual/core20-fde-dbx/task.yaml
@@ -24,9 +24,9 @@ prepare: |
     grep -c 'List ' efi-dbx-state-initial.log > initial-dbx-entries-count
 
     keys_dir="$(tests.nested get assets-path)/ovmf/secboot/"
-    # generate 2 dbx updates
+    # generate 3 dbx updates
     MYGUID="11111111-0000-1111-0000-000000000000"
-    for i in 1 2; do
+    for i in 1 2 3; do
         # generate a key
         openssl req -new -x509 -newkey rsa:2048 -subj "/CN=bad key $i/" \
             -keyout "bad-key-$i.key" -out "bad-key-$i.crt" -days 3650 -nodes -sha256
@@ -149,7 +149,11 @@ execute: |
 
     fetch_and_check_reseal_count_equal "$((reseal_count_start + 6))"
 
-    echo "Attempt a valid 'prepare' request, followed by a reboot"
+    #
+    # real DBX update, with reboot between prepare and cleanup
+    #
+
+    echo "Attempt a valid 'prepare' request, followed by a DBX update and then a reboot"
     echo "{\"action\":\"efi-secureboot-update-db-prepare\",\"key-database\":\"DBX\",\"payload\":\"$update_payload\"}" | \
         remote.exec "sudo snap debug api -X POST -H 'Content-Type: application/json' /v2/system-secureboot" > prepare.out
     jq -r .status < prepare.out | MATCH "OK"
@@ -168,11 +172,11 @@ execute: |
     remote.exec "sudo chattr -i /sys/firmware/efi/efivars/dbx-*"
     # update dbx
     remote.exec sudo test-snapd-efitools.tool efi-readvar -v dbx 2>&1 | tee efi-dbx-before.log
-    # expecting 2 entries in the list
+    # expecting no additional entries in the list
     grep -c 'List ' efi-dbx-before.log | MATCH "$initial_dbx_entries_count"
     remote.exec sudo test-snapd-efitools.tool efi-updatevar -a -f dbx-1-update.auth dbx
     remote.exec sudo test-snapd-efitools.tool efi-readvar -v dbx 2>&1 | tee efi-dbx-after.log
-    # expecting 3 entries in the list
+    # expecting one additional entry in the list
     grep -c 'List ' efi-dbx-after.log | MATCH "$((initial_dbx_entries_count + 1))"
 
     # reboot
@@ -191,17 +195,59 @@ execute: |
 
     fetch_and_check_reseal_count_equal "$((reseal_count_start + 8))"
 
-    echo "Push a DBX update without notifying snapd, which should result in requesting a recovery key on boot"
+    #
+    # real DBX update, with reboot after completing the prepare/cleanup cycle
+    #
+
+    echo "Another DBX update with snapd notification, followed by a reboot"
+    update_payload_2="$(base64 -w0 dbx-2-update.auth)"
+    echo "{\"action\":\"efi-secureboot-update-db-prepare\",\"key-database\":\"DBX\",\"payload\":\"$update_payload_2\"}" | \
+        remote.exec "sudo snap debug api -X POST -H 'Content-Type: application/json' /v2/system-secureboot" > prepare.out
+    jq -r .status < prepare.out | MATCH "OK"
+
+    fetch_and_check_reseal_count_equal "$((reseal_count_start + 9))"
 
     remote.push dbx-2-update.auth
     remote.exec "sudo chattr -i /sys/firmware/efi/efivars/dbx-*"
+    # update dbx
     remote.exec sudo test-snapd-efitools.tool efi-readvar -v dbx 2>&1 | tee efi-dbx-before-2.log
-    # 3 entries based on the previous update
+    # one additional entry from previous scenario
     grep -c 'List ' efi-dbx-before-2.log | MATCH "$((initial_dbx_entries_count + 1))"
     remote.exec sudo test-snapd-efitools.tool efi-updatevar -a -f dbx-2-update.auth dbx
     remote.exec sudo test-snapd-efitools.tool efi-readvar -v dbx 2>&1 | tee efi-dbx-after-2.log
-    # a new key appeared as well
+    # and one more, 2 in total
     grep -c 'List ' efi-dbx-after-2.log | MATCH "$((initial_dbx_entries_count + 2))"
+
+    echo '{"action":"efi-secureboot-update-db-cleanup"}' | \
+        remote.exec "sudo snap debug api -X POST -H 'Content-Type: application/json' /v2/system-secureboot" > cleanup.out
+    jq -r .status < prepare.out | MATCH "OK"
+    remote.exec snap change --last=fde-efi-secureboot-db-update | MATCH 'Done .* Reseal after external EFI DBX update'
+
+    fetch_and_check_reseal_count_equal "$((reseal_count_start + 10))"
+
+    # reboot
+    boot_id="$( tests.nested boot-id )"
+    remote.exec "sudo reboot" || true
+    remote.wait-for reboot "${boot_id}"
+
+    # the system should come up
+    remote.exec "snap list"
+
+    #
+    # real DBX update without notifying snapd, stops asking for recovery key during boot
+    #
+
+    echo "Push a DBX update without notifying snapd, which should result in requesting a recovery key on boot"
+
+    remote.push dbx-3-update.auth
+    remote.exec "sudo chattr -i /sys/firmware/efi/efivars/dbx-*"
+    remote.exec sudo test-snapd-efitools.tool efi-readvar -v dbx 2>&1 | tee efi-dbx-before-3.log
+    # 2 entries based on the previous updates
+    grep -c 'List ' efi-dbx-before-3.log | MATCH "$((initial_dbx_entries_count + 2))"
+    remote.exec sudo test-snapd-efitools.tool efi-updatevar -a -f dbx-3-update.auth dbx
+    remote.exec sudo test-snapd-efitools.tool efi-readvar -v dbx 2>&1 | tee efi-dbx-after-3.log
+    # a new key appeared as well
+    grep -c 'List ' efi-dbx-after-3.log | MATCH "$((initial_dbx_entries_count + 3))"
 
     # get the recovery key first
     recovery_key=$(remote.exec "sudo snap recovery --show-keys" | sed 's/^recovery: *//')
