snap-bootstrap: update encryption test to use uc20 gadget
We were using a previous version of the pc gadget in our spread
tests, so update our encryption test to use the uc20 gadget. This
also exposed us to some scenarios that don't happen in our only
use case, such as creating a seed partition or attempting to
add partitions to a disk with encrypted partitions already added.
Addressing the first case is trivial so we fixed it here, the
other is still not possible and can be fixed in a forthcoming
PR if necessary.

Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>

diff --git a/tests/main/uc20-snap-recovery-encrypt/task.yaml b/tests/main/uc20-snap-recovery-encrypt/task.yaml
--- a/tests/main/uc20-snap-recovery-encrypt/task.yaml
+++ b/tests/main/uc20-snap-recovery-encrypt/task.yaml
@@ -13,7 +13,7 @@ restore: |
 
 prepare: |
     echo "Create a fake block device image"
-    truncate --size=2GB fake.img
+    truncate --size=6GB fake.img
 
     echo "Setup the image as a block device"
     # without -P this test will not work, then /dev/loop1p? will be missing
@@ -24,25 +24,43 @@ prepare: |
     echo "Create an empty partition header"
     echo "label: gpt" | sfdisk "$LOOP"
 
-    # XXX: update to the UC20 gadget when it's available
-    echo "Get the UC16 gadget"
-    snap download pc
+    echo "Get the UC20 gadget"
+    snap download --channel=20/edge pc
     unsquashfs -d gadget-dir pc_*.snap
 
 execute: |
     LOOP="$(cat loop.txt)"
     echo "Run the snap-bootstrap tool"
-    /usr/lib/snapd/snap-bootstrap create-partitions ./gadget-dir "$LOOP"
+    /usr/lib/snapd/snap-bootstrap create-partitions --encrypt --key-file keyfile ./gadget-dir "$LOOP"
 
-    echo "And check that the partitions are created"
+    echo "Check that the key file was created"
+    test "$(stat --printf="%s" ./keyfile)" = 32
+
+    echo "Check that the partitions are created"
     sfdisk -l "$LOOP" | MATCH '1M\s+BIOS boot'
-    sfdisk -l "$LOOP" | MATCH '50M\s+EFI System'
+    sfdisk -l "$LOOP" | MATCH '1\.2G\s+EFI System'
+
+    not cryptsetup isLuks "${LOOP}p1"
+    not cryptsetup isLuks "${LOOP}p2"
+    not cryptsetup isLuks "${LOOP}p3"
+    cryptsetup isLuks "${LOOP}p4"
+
     # we used "lsblk --fs" here but it was unreliable
     mkdir -p ./mnt
     mount "${LOOP}p2" ./mnt
     df -T "${LOOP}p2" | MATCH vfat
     umount ./mnt
-    file -s "${LOOP}p2" | MATCH 'label: "system-boot"'
+    file -s "${LOOP}p2" | MATCH 'label: "ubuntu-seed"'
+
+    mount "${LOOP}p3" ./mnt
+    df -T "${LOOP}p3" | MATCH ext4
+    umount ./mnt
+    file -s "${LOOP}p3" | MATCH 'volume name "ubuntu-boot"'
+
+    mount /dev/mapper/ubuntu-data ./mnt
+    df -T /dev/mapper/ubuntu-data | MATCH ext4
+    umount ./mnt
+    POSIXLY_CORRECT=1 file -s /dev/mapper/ubuntu-data | MATCH 'volume name "ubuntu-data"'
 
     echo "Check that the non-fs content was deployed"
     dd if="${LOOP}p1" of=bios-boot.img
@@ -53,10 +71,6 @@ execute: |
     # and verify that its the same
     cmp bios-boot.img ./gadget-dir/pc-core.img
 
-    echo "Check that the filesystem was not auto-mounted"
-    mount
-    mount | not MATCH /run/mnt/system-boot
-
     echo "Check that the filesystem content was deployed"
     mkdir -p ./mnt
     mount "${LOOP}p2" ./mnt
@@ -65,56 +79,21 @@ execute: |
     ls ./mnt/EFI/ubuntu/grub.cfg
     umount ./mnt
 
-    # debug message to see if the udev database is correctly updated
-    udevadm info --query=property "${LOOP}p2" | grep ID_FS_TYPE ||:
-
-    echo "now add a partition"
-    cat >> gadget-dir/meta/gadget.yaml <<EOF
-          - name: Other ext4
-            type: 83,0FC63DAF-8483-4772-8E79-3D69D8477DE4
-            filesystem: ext4
-            filesystem-label: other-ext4
-            size: 110M
-          - name: Boot partition
-            type: 83,0FC63DAF-8483-4772-8E79-3D69D8477DE4
-            role: system-boot
-            filesystem: ext4
-            size: 120M
-          - name: Data partition
-            type: 83,0FC63DAF-8483-4772-8E79-3D69D8477DE4
-            role: system-data
-            filesystem: ext4
-            size: 130M
-    EOF
-    /usr/lib/snapd/snap-bootstrap create-partitions --encrypt --key-file=keyfile --mount ./gadget-dir "$LOOP"
-    sfdisk -l "$LOOP" | MATCH '110M\s* Linux filesystem'
-    sfdisk -l "$LOOP" | MATCH '120M\s* Linux filesystem'
-    sfdisk -l "$LOOP" | MATCH '130M\s* Linux filesystem'
-
-    echo "check that the filesystems are created and mounted"
-    mount
-
-    mount | MATCH /run/mnt/other-ext4
-    df -T "${LOOP}p3" | MATCH ext4
-    file -s "${LOOP}p3" | MATCH 'volume name "other-ext4"'
-    umount /run/mnt/other-ext4
-
-    mount | MATCH /run/mnt/ubuntu-boot
-    df -T "${LOOP}p4" | MATCH ext4
-    file -s "${LOOP}p4" | MATCH 'volume name "ubuntu-boot"'
-    umount /run/mnt/ubuntu-boot
-
-    cryptsetup isLuks "${LOOP}p5"
-
-    mount | MATCH /run/mnt/ubuntu-data
-    df -T /dev/mapper/ubuntu-data | MATCH ext4
-    POSIXLY_CORRECT=1 file -s /dev/mapper/ubuntu-data | MATCH 'volume name "ubuntu-data"'
-    umount /run/mnt/ubuntu-data
+    mount "${LOOP}p3" ./mnt
+    ls ./mnt/EFI/boot/grubx64.efi
+    ls ./mnt/EFI/boot/bootx64.efi
+    ls ./mnt/EFI/ubuntu/grub.cfg
+    umount ./mnt
 
     echo "ensure that we can open the encrypted device using the key"
     cryptsetup close /dev/mapper/ubuntu-data
-    cryptsetup open --key-file keyfile "${LOOP}p5" test-udata
+    cryptsetup open --key-file keyfile "${LOOP}p4" test-udata
     mount /dev/mapper/test-udata ./mnt
     umount ./mnt
     cryptsetup close /dev/mapper/test-udata
 
+    # debug message to see if the udev database is correctly updated
+    udevadm info --query=property "${LOOP}p2" | grep ID_FS_TYPE ||:
+
+    # XXX: can't add more partitions after an encrypted partition is created
+    # (gadget compatibility tests fail)
