hardcoded task ids; checked commands expected to fail

diff --git a/tests/abort/task.yaml b/tests/abort/task.yaml
--- a/tests/abort/task.yaml
+++ b/tests/abort/task.yaml
@@ -14,27 +14,27 @@ execute: |
   echo "Abort with invalid id"
   invalidID="10000000"
   expected="error: cannot find change with id \"$invalidID\""
-  actual=$(sudo snap abort $invalidID 2>&1) || true
+  actual=$(sudo snap abort $invalidID 2>&1) || FAILED="abort-invalid"
+  [ "$FAILED" != "abort-invalid" ] && exit 1
   echo "$actual" | grep -Pq "$expected" || exit 1
 
   echo "Abort with valid id - error"
   subdirPath="/snap/$SNAP_NAME/current/foo"
   sudo mkdir -p $subdirPath
-  snap install $SNAP_NAME || true
-  idPattern="\d+(?= +Error.*?Install \"$SNAP_NAME\" snap)"
-  changes=$(snap changes)
-  id=$(echo "$changes" | grep -Pzo "$idPattern")
+  snap install $SNAP_NAME || FAILED=install
+  [ "$FAILED" != "install" ] && exit 1
+  id="1"
   expected="error: cannot abort change $id with nothing pending"
-  actual=$(sudo snap abort $id 2>&1) || true
+  actual=$(sudo snap abort $id 2>&1) || FAILED="abort-error"
+  [ "$FAILED" != "abort-error" ] && exit 1
   echo "$actual" | grep -Pq "$expected" || exit 1
 
   sudo rm -rf $subdirPath
 
   echo "Abort with valid id - done"
   sudo snap install $SNAP_NAME
-  idPattern="\d+(?= +Done.*?Install \"$SNAP_NAME\" snap)"
-  changes=$(snap changes)
-  id=$(echo "$changes" | grep -Pzo "$idPattern")
+  id="2"
   expected="error: cannot abort change $id with nothing pending"
-  actual=$(sudo snap abort $id 2>&1) || true
+  actual=$(sudo snap abort $id 2>&1) || FAILED="abort-done"
+  [ "$FAILED" != "abort-done" ] && exit 1
   echo "$actual" | grep -Pq "$expected" || exit 1
