fixed summary; error checking simplified; removed restore step (in favor of restore-each)

diff --git a/tests/abort/task.yaml b/tests/abort/task.yaml
--- a/tests/abort/task.yaml
+++ b/tests/abort/task.yaml
@@ -1,32 +1,23 @@
-summary: Check task abort
+summary: Check change abort
 environment:
   SNAP_NAME: hello-world
-restore: |
-  echo Resetting snapd state...
-  systemctl stop snapd || true
-  umount /var/lib/snapd/snaps/*.snap 2>&1 || true
-  rm -rf /snap/*
-  rm -rf /var/lib/snapd/*
-  rm -f /etc/systemd/system/snap-*.{mount,service}
-  rm -f /etc/systemd/system/multi-user.target.wants/snap-*.mount
-  systemctl start snapd
 execute: |
   echo "Abort with invalid id"
   invalidID="10000000"
   expected="error: cannot find change with id \"$invalidID\""
-  actual=$(sudo snap abort $invalidID 2>&1) || FAILED="abort-invalid"
-  [ "$FAILED" != "abort-invalid" ] && exit 1
+  actual=$(sudo snap abort $invalidID 2>&1) || EXPECTED_FAILED="abort-invalid"
+  [ "$EXPECTED_FAILED" = "abort-invalid" ] || exit 1
   echo "$actual" | grep -Pq "$expected" || exit 1
 
   echo "Abort with valid id - error"
   subdirPath="/snap/$SNAP_NAME/current/foo"
   sudo mkdir -p $subdirPath
-  snap install $SNAP_NAME || FAILED=install
-  [ "$FAILED" != "install" ] && exit 1
+  snap install $SNAP_NAME || EXPECTED_FAILED=install
+  [ "$EXPECTED_FAILED" = "install" ] || exit 1
   id="1"
   expected="error: cannot abort change $id with nothing pending"
-  actual=$(sudo snap abort $id 2>&1) || FAILED="abort-error"
-  [ "$FAILED" != "abort-error" ] && exit 1
+  actual=$(sudo snap abort $id 2>&1) || EXPECTED_FAILED="abort-error"
+  [ "$EXPECTED_FAILED" == "abort-error" ] || exit 1
   echo "$actual" | grep -Pq "$expected" || exit 1
 
   sudo rm -rf $subdirPath
@@ -35,6 +26,6 @@ execute: |
   sudo snap install $SNAP_NAME
   id="2"
   expected="error: cannot abort change $id with nothing pending"
-  actual=$(sudo snap abort $id 2>&1) || FAILED="abort-done"
-  [ "$FAILED" != "abort-done" ] && exit 1
+  actual=$(sudo snap abort $id 2>&1) || EXPECTED_FAILED="abort-done"
+  [ "$EXPECTED_FAILED" = "abort-done" ] || exit 1
   echo "$actual" | grep -Pq "$expected" || exit 1
