tests/core/failover: verify failover handling with the kernel snap
Extend the test to support the kernel snap.

Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>

diff --git a/tests/core/failover/task.yaml b/tests/core/failover/task.yaml
--- a/tests/core/failover/task.yaml
+++ b/tests/core/failover/task.yaml
@@ -21,30 +21,58 @@ environment:
     INJECT_FAILURE/emptysystemd: inject_emptysystemd_failure
     # FIXME: disabled until we find what to do!
     # fails with:  ERROR cannot replace signed kernel snap with an unasserted one
-    #INJECT_FAILURE/emptyinitrd: inject_emptyinitrd_failure
+    INJECT_FAILURE/emptyinitrd: inject_emptyinitrd_failure
     TARGET_SNAP/rclocalcrash: core
     TARGET_SNAP/emptysystemd: core
-    #TARGET_SNAP/emptyinitrd: kernel
+    TARGET_SNAP/emptyinitrd: kernel
     BUILD_DIR: /home/tmp
     # uploading the core or otherwise large snap triggers OOM
     SNAPD_NO_MEMORY_LIMIT: 1
+    BLOB_DIR: $(pwd)/fake-store-blobdir
+
+    SNAP_ID_core20: DLqre5XGLbDqg9jPtiAhRRjDuPVa5X1q
+    SNAP_ID_core18: CSO04Jhav2yK0uz97cr0ipQRyqg0qQL6
+    SNAP_ID_core: 99T7MUlRhtI3U0QFgl5mXXESAiSwt776
+    SNAP_ID_pc_kernel: pYVQrBcKmBa0mZ4CCN7ExT6jH8rY1hza
 
 prepare: |
     mkdir -p "$BUILD_DIR"
+    if [ "$TRUST_TEST_KEYS" = "false" ]; then
+        echo "This test needs test keys to be trusted"
+        exit
+    fi
+    snap install jq
+    snap install remarshal
+
+    snap ack "$TESTSLIB/assertions/testrootorg-store.account-key"
+    snap ack "$TESTSLIB/assertions/developer1.account"
+    snap ack "$TESTSLIB/assertions/developer1.account-key"
+    #shellcheck source=tests/lib/store.sh
+    . "$TESTSLIB"/store.sh
+
+    setup_fake_store "$BLOB_DIR"
 
 restore: |
+    if [ "$TRUST_TEST_KEYS" = "false" ]; then
+        echo "This test needs test keys to be trusted"
+        exit
+    fi
+    #shellcheck source=tests/lib/store.sh
+    . "$TESTSLIB"/store.sh
+    teardown_fake_store "$BLOB_DIR"
     rm -rf "$BUILD_DIR"
 
-    # FIXME: remove the unset when we reset properly snap_try_{core,kernel} on rollback
-    "$TESTSTOOLS"/boot-state bootenv unset snap_try_core
-    "$TESTSTOOLS"/boot-state bootenv unset snap_try_kernel
-
 debug: |
-    "$TESTSTOOLS"/boot-state bootenv show
+    snap debug boot-vars
     snap list
     snap changes
 
 execute: |
+    if [ "$TRUST_TEST_KEYS" = "false" ]; then
+        echo "This test needs test keys to be trusted"
+        exit
+    fi
+
     inject_rclocalcrash_failure(){
         chmod a+x "$BUILD_DIR/unpack/etc/rc.local"
         cat <<EOF > "$BUILD_DIR/unpack/etc/rc.local"
@@ -71,24 +99,31 @@ execute: |
     . "$TESTSLIB"/names.sh
     #shellcheck source=tests/lib/snaps.sh
     . "$TESTSLIB"/snaps.sh
+    #shellcheck source=tests/lib/store.sh
+    . "$TESTSLIB"/store.sh
 
     core_name="core"
+    core_snap_id="$SNAP_ID_core"
     if os.query is-core18; then
         core_name="core18"
+        core_snap_id="$SNAP_ID_core18"
     elif os.query is-core20; then
         core_name="core20"
+        core_snap_id="$SNAP_ID_core20"
     fi
 
     if [ "$TARGET_SNAP" = kernel ]; then
-        TARGET_SNAP_NAME=$kernel_name
+        TARGET_SNAP_NAME=pc-kernel
+        SNAP_ID="$SNAP_ID_pc_kernel"
     else
         TARGET_SNAP_NAME="$core_name"
+        SNAP_ID="$core_snap_id"
     fi
 
     if [ "$SPREAD_REBOOT" = 0 ]; then
         # first pass, save current target snap revision
         snap list | awk "/^${TARGET_SNAP_NAME} / {print(\$3)}" > prevBoot
-
+        START_REVISION=$(($(cat prevBoot) + 1))
         # unpack current target snap
         unsquashfs -no-progress -d "$BUILD_DIR/unpack" "/var/lib/snapd/snaps/${TARGET_SNAP_NAME}_$(cat prevBoot).snap"
 
@@ -97,6 +132,17 @@ execute: |
 
         # repack new target snap
         mksnap_fast "$BUILD_DIR/unpack" failing.snap
+        cat <<EOF > decl-headers.json
+    {"snap-id": "$SNAP_ID"}
+    EOF
+        cat <<EOF > rev-headers.json
+    {"snap-id": "$SNAP_ID", "snap-revision": "$START_REVISION"}
+    EOF
+
+        p=$(new_snap_declaration "$BLOB_DIR" failing.snap --snap-decl-json decl-headers.json)
+        snap ack "$p"
+        p=$(new_snap_revision "$BLOB_DIR" failing.snap --snap-rev-json rev-headers.json)
+        snap ack "$p"
 
         # use journalctl wrapper to grep only the logs collected while the test is running
         if "$TESTSTOOLS"/journal-state get-log | MATCH "Waiting for system reboot"; then
@@ -105,29 +151,28 @@ execute: |
         fi
 
         # install new target snap
-        snap install --no-wait --dangerous failing.snap
+        snap install --no-wait failing.snap
 
         # use journalctl wrapper to grep only the logs collected while the test is running
         # waiting up to 100s to reach waiting for reboot
-        for _ in $(seq 50); do
-            if "$TESTSTOOLS"/journal-state match-log "Waiting for system reboot"; then
-                 break
-            fi
-            sleep 2
-        done
-
-        if ! "$TESTSTOOLS"/journal-state match-log "Waiting for system reboot"; then
-            echo "Taking too long to reach waiting for reboot"
-            exit 1
-        fi
+        retry -n 20 --wait 2 "$TESTSTOOLS"/journal-state match-log "Waiting for system reboot"
 
         # check boot env vars
-        readlink "/snap/$core_name/current" > failBoot
-        test "$("$TESTSTOOLS"/boot-state bootenv show snap_"${TARGET_SNAP}")" = "${TARGET_SNAP_NAME}_$(cat prevBoot).snap"
-        test "$("$TESTSTOOLS"/boot-state bootenv show snap_try_"${TARGET_SNAP}")" = "${TARGET_SNAP_NAME}_$(cat failBoot).snap"
-
+        readlink "/snap/$TARGET_SNAP_NAME/current" > failBoot
+        snap debug boot-vars > before-reboot.bootenv
+        if [ "$TARGET_SNAP" = kernel ]; then
+            MATCH "snap_kernel=${TARGET_SNAP_NAME}_$(cat prevBoot).snap\$"  < before-reboot.bootenv
+            MATCH "snap_try_kernel=${TARGET_SNAP_NAME}_$(cat failBoot).snap\$"  < before-reboot.bootenv
+        else
+            MATCH "snap_core=${TARGET_SNAP_NAME}_$(cat prevBoot).snap\$"  < before-reboot.bootenv
+            MATCH "snap_try_core=${TARGET_SNAP_NAME}_$(cat failBoot).snap\$"  < before-reboot.bootenv
+        fi
         REBOOT
     fi
+
+    # since the change fails snap watch will have non-0 exit status too, so we
+    # need to ignore the exit status
+    snap watch --last=install? || true
 
     # after rollback, we have the original target snap for a while
     # wait until the kernel and core snap revisions are in place
@@ -144,10 +189,11 @@ execute: |
     #shellcheck disable=SC2016
     retry -n 200 --wait 1 sh -c 'snap debug boot-vars | MATCH "snap_mode=\$"'
 
+    snap debug boot-vars > after-reboot.bootenv
     if [ "$TARGET_SNAP" = kernel ]; then
-        snap debug boot-vars | MATCH 'snap_try_kernel=$'
-        snap debug boot-vars | MATCH "snap_kernel=${TARGET_SNAP_NAME}_$(cat prevBoot).snap\$"
+        MATCH 'snap_try_kernel=$' < after-reboot.bootenv
+        MATCH "snap_kernel=${TARGET_SNAP_NAME}_$(cat prevBoot).snap\$" < after-reboot.bootenv
     else
-        snap debug boot-vars | MATCH 'snap_try_core=$'
-        snap debug boot-vars | MATCH "snap_core=${TARGET_SNAP_NAME}_$(cat prevBoot).snap\$"
+        MATCH 'snap_try_core=$' < after-reboot.bootenv
+        MATCH "snap_core=${TARGET_SNAP_NAME}_$(cat prevBoot).snap\$" < after-reboot.bootenv
     fi
