Further improvements of the spread test.

diff --git a/tests/main/snap-get/task.yaml b/tests/main/snap-get/task.yaml
--- a/tests/main/snap-get/task.yaml
+++ b/tests/main/snap-get/task.yaml
@@ -47,7 +47,7 @@ execute: |
     fi
 
     echo "Test number formats"
-    if ! snap set snapctl-hooks command=test-get-int intnumber=1234567890; then
+    if ! snap set snapctl-hooks command=test-get-int intnumber=1234567890 intnumber2="{\"a\":9876543210}"; then
         echo "snap set unexpectedly failed"
         exit 1
     fi
@@ -59,6 +59,11 @@ execute: |
         echo "Expected 'intnumber' to be '$expected', but it was '$output'"
         exit 1
     fi
+
+    if ! output=$(snap get snapctl-hooks intnumber2); then
+        echo "snap get unexpectedly failed"
+    fi
+    echo "$output" | MATCH ".*\"a\": 9876543210.*"
 
     echo "Ensure config value has correct format"
     jq ".data[\"config\"][\"snapctl-hooks\"].intnumber" /var/lib/snapd/state.json | MATCH "1234567890"
