Two more checks in the test.

diff --git a/tests/lib/snaps/basic-iface-hooks-consumer/meta/hooks/connect-plug-foo b/tests/lib/snaps/basic-iface-hooks-consumer/meta/hooks/connect-plug-foo
--- a/tests/lib/snaps/basic-iface-hooks-consumer/meta/hooks/connect-plug-foo
+++ b/tests/lib/snaps/basic-iface-hooks-consumer/meta/hooks/connect-plug-foo
@@ -48,6 +48,12 @@ if [ "$output" != "$expected_output" ]; then
     exit 1
 fi
 
+# Failure on unknown plug
+if snapctl get :unknown target; then
+    echo "Expected snapctl get to fail on unknown plug"
+    exit 1
+fi
+
 # Attributes cannot be set in connect- hooks
 if snapctl set :foo target=slottarget; then
     echo "Expected snapctl set to fail when run from connect-plug hook"
diff --git a/tests/lib/snaps/basic-iface-hooks-producer/meta/hooks/connect-slot-bar b/tests/lib/snaps/basic-iface-hooks-producer/meta/hooks/connect-slot-bar
--- a/tests/lib/snaps/basic-iface-hooks-producer/meta/hooks/connect-slot-bar
+++ b/tests/lib/snaps/basic-iface-hooks-producer/meta/hooks/connect-slot-bar
@@ -35,6 +35,12 @@ if [ "$output" != "$expected_output" ]; then
     exit 1
 fi
 
+# Failure on unknown slot
+if snapctl get :unknown target; then
+    echo "Expected snapctl get to fail on unknown slot"
+    exit 1
+fi
+
 # Attributes cannot be set in connect- hooks
 if snapctl set :bar target=slottarget; then
     echo "Expected snapctl set to fail when run from connect-slot hook"
