Remove PWD use and normalize interfaces tests

diff --git a/tests/main/interfaces-fuse_support/task.yaml b/tests/main/interfaces-fuse_support/task.yaml
--- a/tests/main/interfaces-fuse_support/task.yaml
+++ b/tests/main/interfaces-fuse_support/task.yaml
@@ -50,15 +50,6 @@ execute: |
     echo "The interface is disconnected by default"
     snap interfaces -i fuse-support | MATCH "^- +$NAME:fuse-support"
 
-    if [ "$(snap debug confinement)" = strict ] ; then
-        echo "Then the snap is not able to create a fuse file system"
-        if "$NAME.create" -f "$MOUNT_POINT" 2> fuse.error; then
-            echo "Expected permission error creating fuse filesystem with disconnected plug"
-            exit 1
-        fi
-        MATCH "Permission denied" < fuse.error
-    fi
-
     echo "When the plug is connected"
     snap connect "$NAME:fuse-support"
 
@@ -96,3 +87,16 @@ execute: |
                 grep "$(basename "$MOUNT_POINT") fuse" | cut -f2 -d' ')
     test -n "$mountpath"
 
+    if [ "$(snap debug confinement)" = partial ] ; then
+        exit 0
+    fi
+
+    echo "When the plug is disconnected"
+    snap disconnect "$NAME:fuse-support"
+
+    echo "Then the snap is not able to create a fuse file system"
+    if "$NAME.create" -f "$MOUNT_POINT" 2> fuse.error; then
+        echo "Expected permission error creating fuse filesystem with disconnected plug"
+        exit 1
+    fi
+    MATCH "Permission denied" < fuse.error
diff --git a/tests/main/interfaces-system-observe/task.yaml b/tests/main/interfaces-system-observe/task.yaml
--- a/tests/main/interfaces-system-observe/task.yaml
+++ b/tests/main/interfaces-system-observe/task.yaml
@@ -42,26 +42,29 @@ execute: |
         su -l -c "test-snapd-system-observe-consumer.dbus-introspect" test | MATCH "$expected"
     fi
 
-    if [ "$(snap debug confinement)" = strict ] ; then
-        echo "And the policy has the ptrace suppression rule"
-        MATCH '^deny ptrace \(trace\),' < /var/lib/snapd/apparmor/profiles/snap.test-snapd-system-observe-consumer.consumer
+    if [ "$(snap debug confinement)" = partial ] ; then
+        exit 0
+    fi
 
-        echo "When the plug is disconnected"
-        snap disconnect test-snapd-system-observe-consumer:system-observe
+    echo "And the policy has the ptrace suppression rule"
+    MATCH '^deny ptrace \(trace\),' < /var/lib/snapd/apparmor/profiles/snap.test-snapd-system-observe-consumer.consumer
 
-        echo "Then the snap is not able to get system information"
-        if su -l -c "test-snapd-system-observe-consumer.consumer" test 2>"${PWD}/consumer.error"; then
+    echo "When the plug is disconnected"
+    snap disconnect test-snapd-system-observe-consumer:system-observe
+
+    echo "Then the snap is not able to get system information"
+    if su -l -c "test-snapd-system-observe-consumer.consumer" test 2> consumer.error"; then
+        echo "Expected error with plug disconnected"
+        exit 1
+    fi
+    MATCH "Permission denied" < consumer.error
+
+    if [[ "$SPREAD_SYSTEM" != ubuntu-14.04-* ]]; then
+        echo "And the snap is not able to introspect hostname1"
+        if su -l -c "test-snapd-system-observe-consumer.dbus-introspect" test 2> introspect.error"; then
             echo "Expected error with plug disconnected"
             exit 1
         fi
-        MATCH "Permission denied" < consumer.error
-
-        if [[ "$SPREAD_SYSTEM" != ubuntu-14.04-* ]]; then
-            echo "And the snap is not able to introspect hostname1"
-            if su -l -c "test-snapd-system-observe-consumer.dbus-introspect" test 2>"${PWD}/introspect.error"; then
-                echo "Expected error with plug disconnected"
-                exit 1
-            fi
-            MATCH "Permission denied" < introspect.error
-        fi
+        MATCH "Permission denied" < introspect.error
     fi
+
