Fix failing tests and update comments

diff --git a/tests/main/interfaces-fuse_support/task.yaml b/tests/main/interfaces-fuse_support/task.yaml
--- a/tests/main/interfaces-fuse_support/task.yaml
+++ b/tests/main/interfaces-fuse_support/task.yaml
@@ -19,7 +19,7 @@ environment:
     MOUNT_POINT_OUTSIDE/regular: /var/snap/test-snapd-fuse-consumer/current/mount_point
     NAME/regular: test-snapd-fuse-consumer
     # snap with instance key 'foo'
-    MOUNT_POINT/parallel: /var/snap/test-snapd-fuse-consumer/current/mount_point
+    MOUNT_POINT/parallel: /var/snap/test-snapd-fuse-consumer_foo/current/mount_point
     MOUNT_POINT_OUTSIDE/parallel: /var/snap/test-snapd-fuse-consumer_foo/current/mount_point
     NAME/parallel: test-snapd-fuse-consumer_foo
 
@@ -49,6 +49,15 @@ restore: |
 execute: |
     echo "The interface is disconnected by default"
     snap interfaces -i fuse-support | MATCH "^- +$NAME:fuse-support"
+
+    if [ "$(snap debug confinement)" = strict ]; then
+        echo "The snap is not able to create a fuse file system with the plug disconnected"
+        if "$NAME.create" -f "$MOUNT_POINT" 2> fuse.error; then
+            echo "Expected permission error creating fuse filesystem with disconnected plug"
+            exit 1
+        fi
+        MATCH "Permission denied" < fuse.error
+    fi
 
     echo "When the plug is connected"
     snap connect "$NAME:fuse-support"
@@ -86,17 +95,3 @@ execute: |
     mountpath=$(nsenter "--mount=/run/snapd/ns/$NAME.mnt" cat /proc/mounts | \
                 grep "$(basename "$MOUNT_POINT") fuse" | cut -f2 -d' ')
     test -n "$mountpath"
-
-    if [ "$(snap debug confinement)" = partial ] ; then
-        exit 0
-    fi
-
-    echo "When the plug is disconnected"
-    snap disconnect "$NAME:fuse-support"
-
-    echo "Then the snap is not able to create a fuse file system"
-    if "$NAME.create" -f "$MOUNT_POINT" 2> fuse.error; then
-        echo "Expected permission error creating fuse filesystem with disconnected plug"
-        exit 1
-    fi
-    MATCH "Permission denied" < fuse.error
