overlord/snapstate, daemon, client, cmd/snap: devmode override (aka confined)

diff --git a/tests/main/install-sideload/task.yaml b/tests/main/install-sideload/task.yaml
--- a/tests/main/install-sideload/task.yaml
+++ b/tests/main/install-sideload/task.yaml
@@ -1,7 +1,7 @@
 summary: Checks for snap sideload install
 
 prepare: |
-    for snap in basic test-snapd-tools basic-desktop
+    for snap in basic test-snapd-tools basic-desktop basic-devmode
     do
         snapbuild $TESTSLIB/snaps/$snap .
     done
@@ -31,3 +31,20 @@ execute: |
     Comment=It echos stuff\n\
     Exec=\/snap\/bin\/basic-desktop.echo\n"
     cat /var/lib/snapd/desktop/applications/basic-desktop_echo.desktop | grep -Pzq "$expected"
+
+    echo "Sideload devmode snap fails without flags"
+    expected="devmode .* not requested nor overridden"
+    ( snap install ./basic-devmode_1.0_all.snap 2>&1 || true ) | grep -Pzq "$expected"
+
+    echo "Sideload devmode snap succeeds with --devmode"
+    expected="^basic-devmode +.* +devmode"
+    snap install --devmode ./basic-devmode_1.0_all.snap | grep -Pq "$expected"
+
+    echo "Sideload devmode snap succeeds with --confined"
+    expected="^basic-devmode +.* +confined"
+    snap install --confined ./basic-devmode_1.0_all.snap | grep -Pq "$expected"
+
+    echo "Sideload devmode snap fails with both --devmode and --confined"
+    expected="cannot request both DevMode and Confined"
+    ( snap install --devmode --confined ./basic-devmode_1.0_all.snap 2>&1 || true ) | grep -Pzq "$expected"
+
