tests: add user mounts (in addition to snapctl mounts)

diff --git a/tests/main/snapshot-excludes-mounts/task.yaml b/tests/main/snapshot-excludes-mounts/task.yaml
--- a/tests/main/snapshot-excludes-mounts/task.yaml
+++ b/tests/main/snapshot-excludes-mounts/task.yaml
@@ -1,10 +1,11 @@
-summary: Snapshot excludes active mount-control mount points
+summary: Snapshot excludes active mount points under snap data directories
 
 details: |
-    When taking a snapshot of a snap that has active mount-control mounts
-    under its global data directories ($SNAP_DATA, $SNAP_COMMON), snapd
-    automatically excludes those mount points from the snapshot. This
-    prevents capturing data that was mounted into snap's data directories.
+    When taking a snapshot of a snap that has active mount points under its
+    data directories ($SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA,
+    $SNAP_USER_COMMON), snapd automatically excludes those mount points from
+    the snapshot. This prevents capturing data that was mounted into snap's
+    data directories.
 
 systems: [-ubuntu-14.04-*]
 
@@ -12,9 +13,15 @@ environment:
     SNAP_NAME: test-snapd-mount-control
     SNAP_COMMON: /var/snap/$SNAP_NAME/common
     SNAP_DATA: /var/snap/$SNAP_NAME/x1
+    SNAP_USER_COMMON: /root/snap/$SNAP_NAME/common
+    SNAP_USER_DATA: /root/snap/$SNAP_NAME/x1
     MOUNT_SRC: /var/tmp/$SNAP_NAME
-    MOUNT_DEST_COMMON: $SNAP_COMMON/target1
-    MOUNT_DEST_DATA: $SNAP_DATA/target1
+    SNAPCTL_MOUNT_DEST_COMMON: $SNAP_COMMON/target1
+    SNAPCTL_MOUNT_DEST_DATA: $SNAP_DATA/target1
+    USER_MOUNT_DEST_COMMON: $SNAP_COMMON/target2
+    USER_MOUNT_DEST_DATA: $SNAP_DATA/target2
+    USER_MOUNT_DEST_USER_COMMON: $SNAP_USER_COMMON/target2
+    USER_MOUNT_DEST_USER_DATA: $SNAP_USER_DATA/target2
     # tar invoked when creating snapshots triggers OOM
     SNAPD_NO_MEMORY_LIMIT: 1
     TEST_CASE/v1: snap_save
@@ -35,21 +42,50 @@ prepare: |
     echo "snap-common-data" > "${SNAP_COMMON}/data.txt"
     echo "snap-data-data" > "${SNAP_DATA}/data.txt"
 
-    echo "Create mount target dirs and bind mount the source into them"
-    mkdir -p "${MOUNT_DEST_COMMON}" "${MOUNT_DEST_DATA}"
-    tests.cleanup defer rm -rf "${MOUNT_DEST_COMMON}" "${MOUNT_DEST_DATA}"
-    "${SNAP_NAME}".cmd snapctl mount -o bind,rw "${MOUNT_SRC}" "${MOUNT_DEST_COMMON}"
-    tests.cleanup defer "\"${SNAP_NAME}\".cmd snapctl umount \"${MOUNT_DEST_COMMON}\" || true"
-    "${SNAP_NAME}".cmd snapctl mount -o bind,rw "${MOUNT_SRC}" "${MOUNT_DEST_DATA}"
-    tests.cleanup defer "\"${SNAP_NAME}\".cmd snapctl umount \"${MOUNT_DEST_DATA}\" || true"
+    echo "Create snapctl mounts in global data directories"
+    mkdir -p "${SNAPCTL_MOUNT_DEST_COMMON}" "${SNAPCTL_MOUNT_DEST_DATA}"
+    tests.cleanup defer rm -rf "${SNAPCTL_MOUNT_DEST_COMMON}" "${SNAPCTL_MOUNT_DEST_DATA}"
+    "${SNAP_NAME}".cmd snapctl mount -o bind,rw "${MOUNT_SRC}" "${SNAPCTL_MOUNT_DEST_COMMON}"
+    tests.cleanup defer "\"${SNAP_NAME}\".cmd snapctl umount \"${SNAPCTL_MOUNT_DEST_COMMON}\" || true"
+    "${SNAP_NAME}".cmd snapctl mount -o bind,rw "${MOUNT_SRC}" "${SNAPCTL_MOUNT_DEST_DATA}"
+    tests.cleanup defer "\"${SNAP_NAME}\".cmd snapctl umount \"${SNAPCTL_MOUNT_DEST_DATA}\" || true"
 
-    echo "Verify mounts are active in the host namespace"
-    MATCH "${MOUNT_DEST_COMMON}" < /proc/self/mountinfo
-    MATCH "${MOUNT_DEST_DATA}" < /proc/self/mountinfo
+    echo "Verify snapctl global data dir mounts are active in the host namespace"
+    MATCH "${SNAPCTL_MOUNT_DEST_COMMON}" < /proc/self/mountinfo
+    MATCH "${SNAPCTL_MOUNT_DEST_DATA}" < /proc/self/mountinfo
 
-    echo "Write some files into the mount points; this data should NOT be snapshotted"
-    echo "should-not-appear-in-snapshot" > "${MOUNT_DEST_COMMON}/excluded-file.txt"
-    echo "should-not-appear-in-snapshot" > "${MOUNT_DEST_DATA}/excluded-file.txt"
+    echo "Write some files into the snapctl global data mount points; this data should NOT be snapshotted"
+    echo "should-not-appear-in-snapshot" > "${SNAPCTL_MOUNT_DEST_COMMON}/excluded-file-common.txt"
+    echo "should-not-appear-in-snapshot" > "${SNAPCTL_MOUNT_DEST_DATA}/excluded-file-data.txt"
+
+    # Note: user mounts are intentionally not set up for the snap_remove test
+    # case because `snap remove` will fail if there are any non-snapctl mounts under the
+    # snap's data directories, which will forget the automatic snapshot.
+    if [ "${TEST_CASE}" = "snap_save" ]; then
+        echo "Set up user (non-snapctl) mounts in global and user data directories"
+        mkdir -p "${USER_MOUNT_DEST_COMMON}" "${USER_MOUNT_DEST_DATA}" "${USER_MOUNT_DEST_USER_COMMON}" "${USER_MOUNT_DEST_USER_DATA}"
+        tests.cleanup defer rm -rf "${USER_MOUNT_DEST_COMMON}" "${USER_MOUNT_DEST_DATA}" "${USER_MOUNT_DEST_USER_COMMON}" "${USER_MOUNT_DEST_USER_DATA}"
+        mount -o bind,rw "${MOUNT_SRC}" "${USER_MOUNT_DEST_COMMON}"
+        tests.cleanup defer "umount \"${USER_MOUNT_DEST_COMMON}\" || true"
+        mount -o bind,rw "${MOUNT_SRC}" "${USER_MOUNT_DEST_DATA}"
+        tests.cleanup defer "umount \"${USER_MOUNT_DEST_DATA}\" || true"
+        mount -o bind,rw "${MOUNT_SRC}" "${USER_MOUNT_DEST_USER_COMMON}"
+        tests.cleanup defer "umount \"${USER_MOUNT_DEST_USER_COMMON}\" || true"
+        mount -o bind,rw "${MOUNT_SRC}" "${USER_MOUNT_DEST_USER_DATA}"
+        tests.cleanup defer "umount \"${USER_MOUNT_DEST_USER_DATA}\" || true"
+
+        echo "Verify user mounts are active in the host namespace"
+        MATCH "${USER_MOUNT_DEST_COMMON}" < /proc/self/mountinfo
+        MATCH "${USER_MOUNT_DEST_DATA}" < /proc/self/mountinfo
+        MATCH "${USER_MOUNT_DEST_USER_COMMON}" < /proc/self/mountinfo
+        MATCH "${USER_MOUNT_DEST_USER_DATA}" < /proc/self/mountinfo
+
+        echo "Write some files into the user mount points; this data should NOT be snapshotted"
+        echo "should-not-appear-in-snapshot" > "${USER_MOUNT_DEST_COMMON}/excluded-file-common.txt"
+        echo "should-not-appear-in-snapshot" > "${USER_MOUNT_DEST_DATA}/excluded-file-data.txt"
+        echo "should-not-appear-in-snapshot" > "${USER_MOUNT_DEST_USER_COMMON}/excluded-file-user-common.txt"
+        echo "should-not-appear-in-snapshot" > "${USER_MOUNT_DEST_USER_DATA}/excluded-file-user-data.txt"
+    fi
 
 execute: |
     then_snapshot_is_valid() {
@@ -62,13 +98,23 @@ execute: |
 
     then_snapshot_has_mount_point_excludes() {
         local set_id=$1
-        echo "Verify snapshot ${set_id} has excludes for active mount-control mount points"
+        echo "Verify snapshot ${set_id} has excludes for active mount points"
         timeout 5 snap debug api "/v2/snapshots?set=${set_id}" | gojq -r '.result[0].snapshots[0].options.exclude[]' > options-exclude
         tests.cleanup defer rm -f options-exclude
         #shellcheck disable=SC2016
         MATCH '^\$SNAP_COMMON/target1$' < options-exclude
         #shellcheck disable=SC2016
         MATCH '^\$SNAP_DATA/target1$' < options-exclude
+        if [ "${TEST_CASE}" = "snap_save" ]; then
+            #shellcheck disable=SC2016
+            MATCH '^\$SNAP_COMMON/target2$' < options-exclude
+            #shellcheck disable=SC2016
+            MATCH '^\$SNAP_DATA/target2$' < options-exclude
+            #shellcheck disable=SC2016
+            MATCH '^\$SNAP_USER_COMMON/target2$' < options-exclude
+            #shellcheck disable=SC2016
+            MATCH '^\$SNAP_USER_DATA/target2$' < options-exclude
+        fi
     }
 
     then_restore_and_verify_excludes() {
@@ -77,10 +123,17 @@ execute: |
         snap restore "${set_id}" "${SNAP_NAME}"
         MATCH "snap-common-data" < "${SNAP_COMMON}/data.txt"
         MATCH "snap-data-data" < "${SNAP_DATA}/data.txt"
-        
-        echo "and data inside mount points was not captured"
-        not test -e "${MOUNT_DEST_COMMON}/excluded-file.txt"
-        not test -e "${MOUNT_DEST_DATA}/excluded-file.txt"
+
+        echo "and data inside snapctl mount points was not captured"
+        not test -e "${SNAPCTL_MOUNT_DEST_COMMON}/excluded-file-common.txt"
+        not test -e "${SNAPCTL_MOUNT_DEST_DATA}/excluded-file-data.txt"
+        if [ "${TEST_CASE}" = "snap_save" ]; then
+            echo "and data inside user mount points was not captured"
+            not test -e "${USER_MOUNT_DEST_COMMON}/excluded-file-common.txt"
+            not test -e "${USER_MOUNT_DEST_DATA}/excluded-file-data.txt"
+            not test -e "${USER_MOUNT_DEST_USER_COMMON}/excluded-file-user-common.txt"
+            not test -e "${USER_MOUNT_DEST_USER_DATA}/excluded-file-user-data.txt"
+        fi
     }
 
     test_snap_save() {
@@ -93,8 +146,12 @@ execute: |
         then_snapshot_has_mount_point_excludes "${set_id}"
 
         echo "Unmount before restoring snapshot"
-        "${SNAP_NAME}".cmd snapctl umount "${MOUNT_DEST_COMMON}"
-        "${SNAP_NAME}".cmd snapctl umount "${MOUNT_DEST_DATA}"
+        "${SNAP_NAME}".cmd snapctl umount "${SNAPCTL_MOUNT_DEST_COMMON}"
+        "${SNAP_NAME}".cmd snapctl umount "${SNAPCTL_MOUNT_DEST_DATA}"
+        umount "${USER_MOUNT_DEST_COMMON}"
+        umount "${USER_MOUNT_DEST_DATA}"
+        umount "${USER_MOUNT_DEST_USER_COMMON}"
+        umount "${USER_MOUNT_DEST_USER_DATA}"
         echo "Remove files to test restore"
         rm "${SNAP_COMMON}/data.txt" "${SNAP_DATA}/data.txt"
 
