github: write no go channels resolved error on stderr

diff --git a/.github/workflows/ci-test.yaml b/.github/workflows/ci-test.yaml
--- a/.github/workflows/ci-test.yaml
+++ b/.github/workflows/ci-test.yaml
@@ -30,7 +30,7 @@ jobs:
         run: |
           echo "Resolved Go channels: ${{ steps.resolve-go-channels.outputs.go-channels }}"
           if [ -z "${{ steps.resolve-go-channels.outputs.go-channels }}" ]; then
-            echo "Error: No Go channels resolved"
+            echo "Error: No Go channels resolved" >&2
             exit 1
           fi
 
