fail when the output http code is not 200

diff --git a/.github/workflows/spread-tests.yaml b/.github/workflows/spread-tests.yaml
--- a/.github/workflows/spread-tests.yaml
+++ b/.github/workflows/spread-tests.yaml
@@ -577,13 +577,18 @@ jobs:
       run: |
         if [ -f results.json ]; then
             echo "Sending results to Test-Predictor"
-            JOB_ID=$(gh api --paginate repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs --jq ".jobs[] | select(.name == \"${{ github.workflow }}\") | .id")
+            JOB_ID=$(gh api --paginate repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs --jq ".jobs[] | select(.name | contains(\"${{ inputs.group }}\")) | .id")
 
-            curl -X POST http://test-predictor.canonical.com:5000/ingest \
+            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://test-predictor.canonical.com:5000/ingest \
               -F "file=@./results.json" \
               -F "attempt=${{ github.run_attempt }}" \
               -F "job_id=$JOB_ID" \
-              -F "run_id=${{ github.run_id }}"
+              -F "run_id=${{ github.run_id }}")
+
+              if [ "$HTTP_CODE" -ne 200 ]; then
+                echo "Request failed with status $HTTP_CODE"
+                exit 1
+              fi
         else
             echo "No spread results log found, skipping sending results to Test-Predictor"
         fi
