github: when retrieving artifacts, fail tests without successful artifact download (#15773)
* github: only prepare artifact data if the artifact folder is set and ignore upload if no files are found

* github: during artifact retrieval, if some data is missing, then add the tests with missing data to the list of failed

* github: reverse check and exit early on artifact dir preparation

* github: use printf instead of echo -n when appending new test failures to ensure no extra line breaks

diff --git a/.github/workflows/spread-tests.yaml b/.github/workflows/spread-tests.yaml
--- a/.github/workflows/spread-tests.yaml
+++ b/.github/workflows/spread-tests.yaml
@@ -413,6 +413,20 @@ jobs:
               echo "Running spread log analyzer"
               ./tests/lib/external/snapd-testing-tools/utils/log-analyzer list-reexecute-tasks "$RUN_TESTS" spread-results.json > "$FAILED_TESTS_FILE"
 
+              if [ -n "${{ inputs.upload-artifacts }}" ] && \
+                  [ -d "$ARTIFACTS_FOLDER" ] && \
+                  grep -Eq "Failed (task|suite|project) restore: " spread.log; then
+                  
+                  # Restore encountered some errors, so check the retrieved data for any missing tests.
+                  # If any data is missing, add the corresponding test to the list of failed tests.
+                  for test in $RUN_TESTS; do
+                      dir="$(find $ARTIFACTS_FOLDER -name "$(sed 's/\//--/g' <<<$test)" -type d 2>/dev/null || true)"
+                      if [ -z "$dir" ] && ! grep -q "$test" "$FAILED_TESTS_FILE"; then
+                          printf "%s %s\n" "$(< $FAILED_TESTS_FILE)" "$test" > "$FAILED_TESTS_FILE"
+                      fi
+                  done
+              fi
+
               echo "List of failed tests saved"
               cat "$FAILED_TESTS_FILE"
           else
@@ -428,6 +442,11 @@ jobs:
     - name: Prepare artifact upload
       if: always() && fromJSON(inputs.upload-artifacts)
       run: |
+        if [ -z "${ARTIFACTS_FOLDER}" ]; then
+            echo "No artifacts folder found"
+            exit 0
+        fi
+
         echo "${{ github.run_attempt }}" > "${ARTIFACTS_FOLDER}/run-attempt.txt"
         cp "$FAILED_TESTS_FILE" "${ARTIFACTS_FOLDER}/failed-tests.txt"
         echo "SPREAD_EXPERIMENTAL_FEATURES=${SPREAD_EXPERIMENTAL_FEATURES}" > "${ARTIFACTS_FOLDER}/env-variables.txt"
@@ -440,6 +459,7 @@ jobs:
       with:
         name: "spread-artifacts-${{ inputs.group }}-${{ inputs.systems }}_${{ github.run_id }}_${{ github.run_attempt }}"
         path: "spread-artifacts-${{ inputs.group }}-${{ inputs.systems }}_${{ github.run_id }}_${{ github.run_attempt }}.tar.gz"
+        if-no-files-found: ignore
 
     - name: Save spread test results to cache
       if: always()
