tests, github, spread: add pre-built packages for spread CI workflow (#15740)
* spread, tests: add the ability to use pre-built packages in spread

* github, tests: add workflow for RPM builds

* github, tests: add deb build workflow

* github, tests: add arch builds

* github: add packging use in CI spread workflow

* for testing only - only run one spread test

* github, tests: make tarballs in an external step

* tests: fix shellcheck error

* github, tests: add separate workflow for opensuse 15.6

* github: remove dependency on packaging for spread jobs

* github: remove source rpm packages from build artifacts

* tests, github: use osc when building opensuse packages

* github: use osc for building opensuse

* github: fix cache usage for mock dependencies

* tests: use version from version file in previous job

* tests: use dependencies from PKGBUILD file on arch

* github: remove tarballs from package uploads

* github: add missing testkeys to build for openssue

* github, tests: use mock to build SRPMs

* github, tests: use vendor packages in deb builds

* github, tests: set version outside of build script

* github, tests: use rpmbuild for opensuse instead of osc

* github: remove fakeroot dependency for centos

* github, tests: add comment; rename workflow; remove srpm build

* github: remove fakeroot manipulation

* github: rename workflows to rpm-mock/rpm-rpmbuild

* tests: add newline to dockerfile

* github: remove single-test run in spread

* github: use prebuilt-packages also for core

* tests: add glibc-static to opensuse, fedora, and amazon and libcap-devel to fedora

* github: update action version

* github, tests: remove go version

* tests: use fedora latest container for mock

* github: use correct debian directory for build

* github: add message when prebuilt packages are disabled

* tests: use snapd deb in GOHOME instead of SPREAD_PATH

* tests: set the snapd version for core

* tests: correct snapd deb path

* github: add read/write permission for everybody rather than 777

* tests: use GOHOME instead of GOPATH when copying packages

* tests: add comments

diff --git a/.github/workflows/spread-tests.yaml b/.github/workflows/spread-tests.yaml
--- a/.github/workflows/spread-tests.yaml
+++ b/.github/workflows/spread-tests.yaml
@@ -248,6 +248,68 @@ jobs:
           # Add start line to filtered log
           echo "GRAFANA START: pr ${CHANGE_ID} attempt ${{ github.run_attempt }} run ${{ github.run_id }} group ${{ inputs.group }}" > "$FILTERED_LOG_FILE"
 
+    - name: Download and extract pre-built packages if they exist
+      if: ${{ env.SKIP_SPREAD_LABEL != 'true' }}
+      env:
+        SYSTEMS: ${{ inputs.systems }}
+      uses: actions/github-script@v7
+      with:
+        script: |
+          let fs = require('fs');
+          let path = require('path');
+          let os = require('os');
+          let child_process = require('child_process');
+          let systems = process.env.SYSTEMS.split(' ');
+
+          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            run_id: context.runId,
+          });
+          
+          for (let system of systems) {
+            let artifactName = `package-${system}`;
+            const match = system.match(/^ubuntu-core-(\d+)(-arm)?-64$/);
+            if (match) {
+              const version = match[1];
+              const arch = match[2] || '';
+              artifactName = `package-ubuntu-${version}.04${arch}-64`;
+            }
+            let artifact = allArtifacts.data.artifacts.find(a => a.name === artifactName);
+            if (!artifact) {
+              console.log(`Artifact not found for system: ${system}`);
+              continue;
+            }
+            console.log(`Found artifact "${artifactName}" with id ${artifact.id}, downloading...`);
+
+            const download = await github.rest.actions.downloadArtifact({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              artifact_id: artifact.id,
+              archive_format: 'zip',
+            });
+
+            const artifactZipPath = path.join(process.env.GITHUB_WORKSPACE, `${artifactName}.zip`);
+            fs.writeFileSync(artifactZipPath, Buffer.from(download.data));
+
+            const extractDir = path.join(process.env.GITHUB_WORKSPACE, 'built-pkgs', system);
+            fs.mkdirSync(extractDir, { recursive: true });
+            child_process.execSync(`unzip -q -o ${artifactZipPath} -d ${extractDir}`);
+
+            fs.unlinkSync(artifactZipPath);
+          }
+
+    - name: Set whether to use pre-built packages in spread
+      run: |
+        SPREAD_USE_PREBUILT_PACKAGES=true
+        for system in ${{ inputs.systems }}; do
+          if ! [ -d built-pkgs/"$system" ]; then
+            SPREAD_USE_PREBUILT_PACKAGES=false
+            echo "Disabling prebuilt packages due to missing $system directory"
+          fi
+        done
+        echo "SPREAD_USE_PREBUILT_PACKAGES=$SPREAD_USE_PREBUILT_PACKAGES" >> $GITHUB_ENV
+
     - name: Download built snap (amd64)
       uses: actions/download-artifact@v4
       if: "${{ env.SKIP_SPREAD_LABEL != 'true' && !inputs.use-snapd-snap-from-master && !contains(inputs.group, '-arm64') && !contains(inputs.group, '-fips') }}"
