Improve python code and use pipefail while running spread tests

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -259,6 +259,10 @@ jobs:
               FAILED_TESTS="$(cat $FAILED_TESTS_FILE)"
           fi
 
+          # Set pipefail to make step fail when the spread run fails
+          set -o pipefail
+
+          # Run spread tests
           if [ -z "$FAILED_TESTS" ] ; then
               spread -abend google:${{ matrix.system }}:tests/... | tee spread.log
           else
