s/config-changing/configure/
Signed-off-by: Kyle Fazzari <kyle@canonical.com>

diff --git a/tests/main/snap-run-hook/task.yaml b/tests/main/snap-run-hook/task.yaml
--- a/tests/main/snap-run-hook/task.yaml
+++ b/tests/main/snap-run-hook/task.yaml
@@ -17,14 +17,14 @@ execute: |
 
     echo "Test that snap run can call valid hooks"
 
-    if ! output="$(snap run --hook=config-changing basic-hooks)"; then
-        echo "Failed to run config-changing hook"
+    if ! output="$(snap run --hook=configure basic-hooks)"; then
+        echo "Failed to run configure hook"
         exit 1
     fi
 
-    expected_output="config-changing hook"
+    expected_output="configure hook"
     if [ "$output" != "$expected_output" ]; then
-        echo "Expected config-changing output to be '$expected_output', but it was '$output'"
+        echo "Expected configure output to be '$expected_output', but it was '$output'"
         exit 1
     fi
 
